// ── New-build coastal data (server-only) ────────────────────────────────
// Generated by: cargo run --bin spain-discover
// Source: crates/airbnb/src/discover.rs

import { readFileSync } from "fs";
import { join } from "path";

export interface ListingScore {
  id: string;
  total: number;
  price_score: number;
  sea_score: number;
  newness_score: number;
  amenity_score: number;
  size_score: number;
}

export interface ScoredListing {
  id: string;
  name: string;
  description: string;
  property_type: string;
  price_eur: number;
  price_per_sqm: number | null;
  sqm: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  floor: number | null;
  city: string;
  zone: string;
  lat: number;
  lng: number;
  source_url: string;
  source: string;
  amenities: string[];
  is_new_build: boolean;
  build_year: number | null;
  sea_distance_km: number | null;
  has_pool: boolean;
  has_parking: boolean;
  has_terrace: boolean;
  complex_name: string | null;
  image_url: string | null;
  score: ListingScore;
}

export interface NewBuildQuery {
  maxPrice?: number;
  zone?: string;
  minBedrooms?: number;
  hasPool?: boolean;
}

export interface NewBuildData {
  filters: {
    maxPrice: number;
    zone: string | null;
    minBedrooms: number | null;
    hasPool: boolean | null;
  };
  stats: {
    total: number;
    zones: string[];
    priceRange: [number, number];
  };
  listings: ScoredListing[];
}

let _cache: ScoredListing[] | null = null;

function loadListings(): ScoredListing[] {
  if (_cache) return _cache;
  const path = join(process.cwd(), "data", "spain-newbuild-coastal.json");
  const raw = readFileSync(path, "utf-8");
  _cache = JSON.parse(raw) as ScoredListing[];
  return _cache;
}

export function queryNewBuilds(q: NewBuildQuery = {}): NewBuildData {
  const all = loadListings();
  const maxPrice = Math.min(Math.max(q.maxPrice ?? 150_000, 50_000), 500_000);
  const zone = q.zone?.toLowerCase() ?? null;
  const minBedrooms = q.minBedrooms ?? null;
  const hasPool = q.hasPool ?? null;

  let filtered = all.filter((l) => l.price_eur <= maxPrice);

  if (zone) {
    filtered = filtered.filter(
      (l) =>
        l.zone.toLowerCase().includes(zone) ||
        l.city.toLowerCase().includes(zone)
    );
  }

  if (minBedrooms !== null) {
    filtered = filtered.filter((l) => (l.bedrooms ?? 0) >= minBedrooms);
  }

  if (hasPool !== null) {
    filtered = filtered.filter((l) => l.has_pool === hasPool);
  }

  const zones = [...new Set(filtered.map((l) => l.zone))].sort();
  const prices = filtered.map((l) => l.price_eur);
  const priceRange: [number, number] =
    prices.length > 0
      ? [Math.min(...prices), Math.max(...prices)]
      : [0, 0];

  return {
    filters: { maxPrice, zone, minBedrooms, hasPool },
    stats: {
      total: filtered.length,
      zones,
      priceRange,
    },
    listings: filtered,
  };
}
