-- Movie recommendations generated by movies_graph.py.
-- Mirrors recommended_books shape: nullable goal_id / family_member_id, free-form
-- category text, JSON-array stored as TEXT for genres. IMDb / TMDB ids are kept
-- as text so the column tolerates both numeric ids and "tt0123456" prefixes.
-- whyRecommended is stored UPPERCASE-tagged ("EMOTIONAL —", "SIMILAR —", …) the
-- same way books use the "RESEARCH-BACKED — …" prefix; the client strips the
-- prefix when rendering.

BEGIN;

CREATE TABLE IF NOT EXISTS recommended_movies (
  id serial PRIMARY KEY,
  goal_id integer,
  family_member_id integer,
  title text NOT NULL,
  year integer,
  imdb_id text,
  tmdb_id text,
  platform text,
  rating text,
  imdb_rating numeric(3,1),
  age_band text,
  genres text,
  description text NOT NULL,
  why_recommended text NOT NULL,
  category text NOT NULL,
  justwatch_url text,
  generated_at text NOT NULL DEFAULT NOW(),
  created_at text NOT NULL DEFAULT NOW(),
  updated_at text NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recommended_movies_goal ON recommended_movies (goal_id);
CREATE INDEX IF NOT EXISTS idx_recommended_movies_family_member ON recommended_movies (family_member_id);
CREATE INDEX IF NOT EXISTS idx_recommended_movies_category ON recommended_movies (category);

COMMIT;

-- =============================================================================
-- DOWN (copy into psql to roll back):
-- =============================================================================
-- BEGIN;
-- DROP INDEX IF EXISTS idx_recommended_movies_category;
-- DROP INDEX IF EXISTS idx_recommended_movies_family_member;
-- DROP INDEX IF EXISTS idx_recommended_movies_goal;
-- DROP TABLE IF EXISTS recommended_movies;
-- COMMIT;
