"""Canonical skill taxonomy — from _generated_schema.py."""

from typing import FrozenSet

SKILL_TAGS: FrozenSet[str] = frozenset({
    "javascript", "typescript", "python", "java", "csharp", "ruby",
    "php", "go", "rust", "swift", "kotlin", "scala",
    "elixir", "react", "vue", "angular", "svelte", "nextjs",
    "nodejs", "express", "django", "flask", "laravel", "fastapi",
    "spring-boot", "react-native", "flutter", "ios", "android", "postgresql",
    "mysql", "mongodb", "redis", "elasticsearch", "cassandra", "dynamodb",
    "sqlite", "sql", "aws", "gcp", "azure", "docker",
    "kubernetes", "terraform", "ansible", "jenkins", "ci-cd", "circleci",
    "serverless", "microservices", "rest-api", "graphql", "grpc", "websocket",
    "event-driven", "git", "linux", "agile", "tdd", "webpack",
    "jest", "pytest", "tailwind", "machine-learning", "deep-learning", "tensorflow",
    "pytorch", "pandas", "numpy", "scikit", "nlp", "computer-vision",
    "llm", "rag", "prompt-engineering", "fine-tuning", "embeddings", "transformers",
    "agents", "agentic-ai", "langchain", "langgraph", "llamaindex", "openai", "anthropic",
    "vercel-ai-sdk", "vector-db", "pinecone", "weaviate", "chromadb", "mlops",
    "huggingface", "model-evaluation", "structured-output", "function-calling", "mastra", "langfuse",
    "cloudflare-workers", "cloudflare-workers-ai", "cloudflare-d1", "cloudflare-vectorize", "next-auth", "radix-ui",
    "shadcn-ui", "storybook", "playwright", "cypress", "vitest", "react-query",
    "zustand", "apollo-client", "remix", "astro", "drizzle-orm", "prisma",
    "trpc", "hono", "bun", "deno",
})

SKILL_LABELS: dict[str, str] = {
    "javascript": "JavaScript", "typescript": "TypeScript", "python": "Python",
    "java": "Java", "csharp": "C#", "ruby": "Ruby", "php": "PHP",
    "go": "Go", "rust": "Rust", "swift": "Swift", "kotlin": "Kotlin",
    "scala": "Scala", "elixir": "Elixir", "react": "React", "vue": "Vue.js",
    "angular": "Angular", "svelte": "Svelte", "nextjs": "Next.js",
    "nodejs": "Node.js", "express": "Express.js", "django": "Django",
    "flask": "Flask", "laravel": "Laravel", "fastapi": "FastAPI",
    "spring-boot": "Spring Boot", "react-native": "React Native",
    "flutter": "Flutter", "ios": "iOS Development", "android": "Android Development",
    "postgresql": "PostgreSQL", "mysql": "MySQL", "mongodb": "MongoDB",
    "redis": "Redis", "elasticsearch": "Elasticsearch", "cassandra": "Cassandra",
    "dynamodb": "DynamoDB", "sqlite": "SQLite", "sql": "SQL",
    "aws": "Amazon Web Services", "gcp": "Google Cloud Platform",
    "azure": "Microsoft Azure", "docker": "Docker", "kubernetes": "Kubernetes",
    "terraform": "Terraform", "ansible": "Ansible", "jenkins": "Jenkins",
    "ci-cd": "CI/CD", "circleci": "CircleCI", "serverless": "Serverless",
    "microservices": "Microservices", "rest-api": "REST API", "graphql": "GraphQL",
    "grpc": "gRPC", "websocket": "WebSocket",
    "event-driven": "Event-Driven Architecture", "git": "Git", "linux": "Linux",
    "agile": "Agile", "tdd": "Test-Driven Development", "webpack": "Webpack",
    "jest": "Jest", "pytest": "pytest", "tailwind": "Tailwind CSS",
    "machine-learning": "Machine Learning", "deep-learning": "Deep Learning",
    "tensorflow": "TensorFlow", "pytorch": "PyTorch", "pandas": "Pandas",
    "numpy": "NumPy", "scikit": "scikit-learn",
    "nlp": "Natural Language Processing", "computer-vision": "Computer Vision",
    "llm": "Large Language Models", "rag": "Retrieval-Augmented Generation",
    "prompt-engineering": "Prompt Engineering", "fine-tuning": "Fine-Tuning",
    "embeddings": "Embeddings", "transformers": "Transformers",
    "agents": "AI Agents", "agentic-ai": "Agentic AI", "langchain": "LangChain",
    "langgraph": "LangGraph", "llamaindex": "LlamaIndex",
    "openai": "OpenAI", "anthropic": "Anthropic Claude",
    "vercel-ai-sdk": "Vercel AI SDK", "vector-db": "Vector Databases",
    "pinecone": "Pinecone", "weaviate": "Weaviate", "chromadb": "ChromaDB",
    "mlops": "MLOps", "huggingface": "Hugging Face",
    "model-evaluation": "Model Evaluation", "structured-output": "Structured Output",
    "function-calling": "Function Calling", "mastra": "Mastra", "langfuse": "Langfuse",
    "cloudflare-workers": "Cloudflare Workers",
    "cloudflare-workers-ai": "Cloudflare Workers AI",
    "cloudflare-d1": "Cloudflare D1", "cloudflare-vectorize": "Cloudflare Vectorize",
    "next-auth": "NextAuth.js", "radix-ui": "Radix UI", "shadcn-ui": "shadcn/ui",
    "storybook": "Storybook", "playwright": "Playwright", "cypress": "Cypress",
    "vitest": "Vitest", "react-query": "React Query / TanStack Query",
    "zustand": "Zustand", "apollo-client": "Apollo Client", "remix": "Remix",
    "astro": "Astro", "drizzle-orm": "Drizzle ORM", "prisma": "Prisma",
    "trpc": "tRPC", "hono": "Hono", "bun": "Bun", "deno": "Deno",
}
