// This file is auto-generated by GraphQL Code Generator.
// Do not edit manually. Run `pnpm codegen` to regenerate.

export const typeDefs = /* GraphQL */ `
schema {
  query: Query
  mutation: Mutation
}

type ATSBoard {
  board_type: ATSBoardType!
  company_id: Int!
  confidence: Float!
  created_at: String!
  evidence: Evidence!
  first_seen_at: String!
  id: Int!
  is_active: Boolean!
  last_seen_at: String!
  updated_at: String!
  url: String!
  vendor: ATSVendor!
}

enum ATSBoardType {
  BOARD_API
  BOARD_WIDGET
  JOBS_PAGE
  UNKNOWN
}

input ATSBoardUpsertInput {
  board_type: ATSBoardType!
  confidence: Float!
  evidence: EvidenceInput!
  is_active: Boolean!
  last_seen_at: String!
  url: String!
  vendor: ATSVendor!
}

enum ATSVendor {
  ASHBY
  BREEZYHR
  GREENHOUSE
  ICIMS
  JAZZHR
  JOBVITE
  LEVER
  ORACLE_TALEO
  OTHER
  SAP_SUCCESSFACTORS
  SMARTRECRUITERS
  TEAMTAILOR
  WORKABLE
}

type AnalyzeCompanyResponse {
  companyId: Int
  companyKey: String
  message: String
  success: Boolean!
}

type Application {
  companyKey: String
  companyName: String
  createdAt: String!
  email: EmailAddress!
  id: Int!
  jobDescription: String
  jobId: String!
  jobTitle: String
  notes: String
  questions: [QuestionAnswer!]!
  resume: Upload
  status: ApplicationStatus!
}

input ApplicationInput {
  companyName: String
  jobId: String
  jobTitle: String
  questions: [QuestionAnswerInput!]!
  resume: Upload
}

"""
Pipeline status for a tracked job application.
Maps to a kanban column in the UI.
"""
enum ApplicationStatus {
  accepted
  pending
  rejected
  reviewed
  submitted
}

type ApplyEmailPatternResult {
  contacts: [Contact!]!
  contactsUpdated: Int!
  message: String!
  pattern: String
  success: Boolean!
}

type ArchiveEmailResult {
  message: String!
  success: Boolean!
}

type AshbyAddress {
  postalAddress: AshbyPostalAddress
}

type AshbyCompensation {
  compensationTierSummary: String
  compensationTiers: [AshbyCompensationTier!]!
  scrapeableCompensationSalarySummary: String
  summaryComponents: [AshbyCompensationComponent!]!
}

type AshbyCompensationComponent {
  compensationType: String
  currencyCode: String
  id: String
  interval: String
  maxValue: Float
  minValue: Float
  summary: String
}

type AshbyCompensationTier {
  additionalInformation: String
  components: [AshbyCompensationComponent!]!
  id: String
  tierSummary: String
  title: String
}

type AshbyEnrichment {
  company_name: String
  enriched_at: String
  industry_tags: [String!]!
  size_signal: String
  tech_signals: [String!]!
}

type AshbyPostalAddress {
  addressCountry: String
  addressLocality: String
  addressRegion: String
}

type AshbySecondaryLocation {
  address: AshbyPostalAddress
  location: String!
}

input BatchRecipientInput {
  companyId: Int
  contactId: Int
  email: String!
  name: String!
}

type BlockJobsResult {
  message: String!
  success: Boolean!
}

type BlockedCompany {
  createdAt: String!
  id: Int!
  name: String!
  reason: String
}

type CancelCompanyEmailsResult {
  cancelledCount: Int!
  failedCount: Int!
  message: String!
  success: Boolean!
}

type CancelEmailResult {
  error: String
  success: Boolean!
}

type ChatMessage {
  content: String!
  role: String!
}

input ChatMessageInput {
  content: String!
  role: String!
}

"""Confidence level of a classification result."""
enum ClassificationConfidence {
  high
  low
  medium
}

type CompaniesResponse {
  companies: [Company!]!
  totalCount: Int!
}

type Company {
  ai_classification_confidence: Float!
  ai_classification_reason: String
  ai_tier: Int!
  ashby_enrichment: AshbyEnrichment
  ats_boards: [ATSBoard!]!
  category: CompanyCategory!
  contacts: [Contact!]!
  created_at: String!
  deep_analysis: String
  description: String
  email: String
  emailsList: [String!]!
  facts(field: String, limit: Int, offset: Int): [CompanyFact!]!
  facts_count: Int!
  githubUrl: String
  id: Int!
  industries: [String!]!
  industry: String
  is_hidden: Boolean!
  job_board_url: String
  key: String!
  last_seen_capture_timestamp: String
  last_seen_crawl_id: String
  last_seen_source_url: String
  linkedin_url: String
  location: String
  logo_url: String
  name: String!
  opportunities: [Opportunity!]!
  score: Float!
  score_reasons: [String!]!
  service_taxonomy: [String!]!
  services: [String!]!
  size: String
  snapshots(limit: Int, offset: Int): [CompanySnapshot!]!
  snapshots_count: Int!
  tags: [String!]!
  updated_at: String!
  website: String
}

enum CompanyCategory {
  AGENCY
  CONSULTANCY
  DIRECTORY
  OTHER
  PRODUCT
  STAFFING
  UNKNOWN
}

type CompanyContactEmail {
  contactFirstName: String!
  contactId: Int!
  contactLastName: String!
  contactPosition: String
  createdAt: String!
  deliveredAt: String
  errorMessage: String
  followupStatus: String
  fromEmail: String!
  id: Int!
  openedAt: String
  recipientName: String
  replyReceived: Boolean!
  resendId: String!
  scheduledAt: String
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

type CompanyFact {
  company_id: Int!
  confidence: Float!
  created_at: String!
  evidence: Evidence!
  field: String!
  id: Int!
  normalized_value: JSON
  value_json: JSON
  value_text: String
}

input CompanyFactInput {
  confidence: Float!
  evidence: EvidenceInput!
  field: String!
  normalized_value: JSON
  value_json: JSON
  value_text: String
}

input CompanyFilterInput {
  category_in: [CompanyCategory!]
  has_ats_boards: Boolean
  is_hidden: Boolean
  min_ai_tier: Int
  min_score: Float
  service_taxonomy_any: [String!]
  text: String
}

input CompanyImportInput {
  description: String
  email: String
  linkedin_url: String
  location: String
  name: String!
  website: String
}

enum CompanyOrderBy {
  CREATED_AT_DESC
  NAME_ASC
  SCORE_DESC
  UPDATED_AT_DESC
}

type CompanySnapshot {
  capture_timestamp: String
  company_id: Int!
  content_hash: String
  crawl_id: String
  created_at: String!
  evidence: Evidence!
  extracted: JSON
  fetched_at: String!
  http_status: Int
  id: Int!
  jsonld: JSON
  mime: String
  source_url: String!
  text_sample: String
}

type Contact {
  bouncedEmails: [String!]!
  company: String
  companyId: Int
  createdAt: String!
  doNotContact: Boolean!
  email: String
  emailVerified: Boolean
  emails: [String!]!
  firstName: String!
  githubHandle: String
  id: Int!
  lastName: String!
  linkedinUrl: String
  nbExecutionTimeMs: Int
  nbFlags: [String!]!
  nbResult: String
  nbRetryToken: String
  nbStatus: String
  nbSuggestedCorrection: String
  position: String
  tags: [String!]!
  telegramHandle: String
  updatedAt: String!
  userId: String
}

type ContactEmail {
  attachments: JSON
  ccEmails: [String!]!
  companyId: Int
  contactId: Int!
  createdAt: String!
  deliveredAt: String
  errorMessage: String
  followupStatus: String
  fromEmail: String!
  headers: JSON
  htmlContent: String
  id: Int!
  idempotencyKey: String
  openedAt: String
  parentEmailId: Int
  recipientName: String
  replyReceived: Boolean!
  replyReceivedAt: String
  replyToEmails: [String!]!
  resendId: String!
  scheduledAt: String
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  tags: [String!]!
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

input ContactInput {
  company: String
  companyId: Int
  email: String
  emails: [String!]
  firstName: String!
  githubHandle: String
  lastName: String!
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

type ContactsResult {
  contacts: [Contact!]!
  totalCount: Int!
}

input CreateCampaignInput {
  addAntiThreadHeader: Boolean
  addUnsubscribeHeaders: Boolean
  companyId: Int
  createdBy: String
  delayDays: JSON
  fromEmail: String
  mode: String
  name: String!
  recipientEmails: [String!]
  replyTo: String
  sequence: JSON
  totalEmailsPlanned: Int
  unsubscribeUrl: String
}

input CreateCompanyInput {
  ai_classification_confidence: Float
  ai_classification_reason: String
  ai_tier: Int
  category: CompanyCategory
  description: String
  email: String
  emails: [String!]
  github_url: String
  industries: [String!]
  industry: String
  key: String!
  linkedin_url: String
  location: String
  logo_url: String
  name: String!
  service_taxonomy: [String!]
  services: [String!]
  size: String
  tags: [String!]
  website: String
}

input CreateContactInput {
  companyId: Int
  email: String
  emails: [String!]
  firstName: String!
  githubHandle: String
  lastName: String
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

input CreateEmailTemplateInput {
  category: String
  description: String
  htmlContent: String
  name: String!
  subject: String
  tags: [String!]
  textContent: String
  variables: [String!]
}

input CreateLangSmithPromptInput {
  description: String
  isPublic: Boolean
  readme: String
  tags: [String!]
}

input CreateOpportunityInput {
  applicationNotes: String
  companyId: Int
  contactId: Int
  deadline: String
  endDate: String
  rewardText: String
  rewardUsd: Float
  source: String
  startDate: String
  status: String
  tags: [String!]
  title: String!
  url: String
}

input CreatePromptInput {
  chatMessages: [ChatMessageInput!]
  config: PromptConfigInput
  labels: [String!]
  name: String!
  prompt: String
  tags: [String!]
  type: PromptType!
}

input CreateTaskInput {
  description: String
  dueDate: String
  entityId: String
  entityType: String
  priority: String
  status: String
  tags: [String!]
  title: String!
}

scalar DateTime

type DeleteApplicationResponse {
  message: String
  success: Boolean!
}

type DeleteBlockedCompanyResult {
  message: String
  success: Boolean!
}

type DeleteCampaignResult {
  message: String
  success: Boolean!
}

type DeleteCompaniesResult {
  deleted: Int!
  message: String!
  success: Boolean!
}

type DeleteCompanyResponse {
  message: String
  success: Boolean!
}

type DeleteContactResult {
  message: String!
  success: Boolean!
}

type DeleteEmailTemplateResult {
  message: String
  success: Boolean!
}

type DeleteJobResponse {
  message: String
  success: Boolean!
}

type DeleteOpportunityResult {
  message: String
  success: Boolean!
}

type DeleteTaskResult {
  message: String
  success: Boolean!
}

scalar EmailAddress

type EmailCampaign {
  addAntiThreadHeader: Boolean!
  addUnsubscribeHeaders: Boolean!
  companyId: Int
  createdAt: String!
  createdBy: String
  delayDays: JSON
  emailsFailed: Int!
  emailsScheduled: Int!
  emailsSent: Int!
  fromEmail: String
  id: String!
  mode: String
  name: String!
  recipientEmails: [String!]!
  replyTo: String
  sequence: JSON
  startAt: String
  status: String!
  totalEmailsPlanned: Int
  totalRecipients: Int!
  unsubscribeUrl: String
  updatedAt: String!
}

type EmailCampaignsResult {
  campaigns: [EmailCampaign!]!
  totalCount: Int!
}

type EmailPreview {
  drySendResult: String
  htmlContent: String!
  subject: String!
}

type EmailStats {
  bouncedThisMonth: Int!
  bouncedThisWeek: Int!
  bouncedToday: Int!
  deliveredThisMonth: Int!
  deliveredThisWeek: Int!
  deliveredToday: Int!
  openedThisMonth: Int!
  openedThisWeek: Int!
  openedToday: Int!
  scheduledFuture: Int!
  scheduledToday: Int!
  sentThisMonth: Int!
  sentThisWeek: Int!
  sentToday: Int!
  totalSent: Int!
}

type EmailTemplate {
  category: String
  createdAt: String!
  description: String
  htmlContent: String
  id: Int!
  isActive: Boolean!
  name: String!
  subject: String
  tags: [String!]!
  textContent: String
  updatedAt: String!
  userId: String
  variables: [String!]!
}

type EmailTemplatesResult {
  templates: [EmailTemplate!]!
  totalCount: Int!
}

type EnhanceAllContactsResult {
  companiesProcessed: Int!
  errors: [String!]!
  message: String!
  success: Boolean!
  totalContactsProcessed: Int!
  totalEmailsFound: Int!
}

type EnhanceCompanyResponse {
  companyId: Int
  companyKey: String
  message: String
  success: Boolean!
}

"""Response from enhancing a job with ATS data"""
type EnhanceJobResponse {
  """The updated job record with enhanced data from the ATS"""
  job: Job
  """Human-readable message about the operation result"""
  message: String
  """Whether the enhancement was successful"""
  success: Boolean!
}

type Evidence {
  capture_timestamp: String
  content_hash: String
  crawl_id: String
  extractor_version: String
  http_status: Int
  method: ExtractMethod!
  mime: String
  observed_at: String!
  source_type: SourceType!
  source_url: String!
  warc: WarcPointer
}

input EvidenceInput {
  capture_timestamp: String
  content_hash: String
  crawl_id: String
  extractor_version: String
  http_status: Int
  method: ExtractMethod!
  mime: String
  observed_at: String!
  source_type: SourceType!
  source_url: String!
  warc: WarcPointerInput
}

enum ExtractMethod {
  DOM
  HEURISTIC
  JSONLD
  LLM
  META
}

type FindCompanyResult {
  company: Company
  found: Boolean!
}

type FindContactEmailResult {
  candidatesTried: Int!
  email: String
  emailFound: Boolean!
  message: String!
  success: Boolean!
  verified: Boolean
}

input FollowUpBatchInput {
  companyId: Int!
  customInstructions: String
  customSubject: String
  daysAfter: Int!
  sequenceNumber: String!
}

type FollowUpBatchResult {
  contactCount: Int!
  emailIds: [String!]!
  message: String!
  success: Boolean!
}

type FollowUpEmail {
  companyId: Int
  contactId: Int!
  createdAt: String!
  followupStatus: String
  fromEmail: String!
  id: Int!
  recipientName: String
  resendId: String!
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  toEmails: [String!]!
}

type FollowUpEmailsResult {
  emails: [FollowUpEmail!]!
  totalCount: Int!
}

input GenerateEmailInput {
  companyName: String
  purpose: String!
  recipientName: String!
  recipientRole: String
  templateId: Int
  tone: String
}

type GenerateEmailResult {
  html: String!
  subject: String!
  text: String!
}

input GenerateReplyInput {
  additionalDetails: String
  includeCalendly: Boolean
  originalEmailContent: String!
  originalSender: String!
  replyTo: String
  replyType: String
  tone: String
}

type GenerateReplyResult {
  body: String!
  subject: String!
}

type GreenhouseCompliance {
  description: String
  questions: [GreenhouseQuestion!]
  type: String!
}

type GreenhouseDataCompliance {
  demographic_data_consent_applies: Boolean!
  requires_consent: Boolean!
  requires_processing_consent: Boolean!
  requires_retention_consent: Boolean!
  retention_period: Int
  type: String!
}

type GreenhouseDemographicQuestions {
  description: String
  header: String
  questions: [GreenhouseQuestion!]
}

type GreenhouseDepartment {
  child_ids: [String!]
  id: String!
  name: String!
  parent_id: String
}

type GreenhouseMetadata {
  id: String!
  name: String!
  value: String
  value_type: String
}

type GreenhouseOffice {
  child_ids: [String!]
  id: String!
  location: String
  name: String!
  parent_id: String
}

type GreenhouseQuestion {
  description: String
  fields: [GreenhouseQuestionField!]
  label: String!
  required: Boolean!
}

type GreenhouseQuestionField {
  name: String
  type: String!
}

type ImportCompaniesResult {
  errors: [String!]!
  failed: Int!
  imported: Int!
  success: Boolean!
}

type ImportCompanyResult {
  company: Company
  contactsImported: Int!
  contactsSkipped: Int!
  errors: [String!]!
  success: Boolean!
}

input ImportCompanyWithContactsInput {
  companyName: String!
  contacts: [ImportContactInput!]!
  website: String
}

input ImportContactInput {
  linkedinUrl: String
  name: String!
  workEmail: String
}

type ImportContactsResult {
  errors: [String!]!
  failed: Int!
  imported: Int!
  success: Boolean!
}

scalar JSON

type Job {
  absolute_url: String
  applied: Boolean!
  appliedAt: String
  archived: Boolean!
  ashby_address: AshbyAddress
  ashby_apply_url: String
  ashby_compensation: AshbyCompensation
  ashby_department: String
  ashby_employment_type: String
  ashby_is_listed: Boolean
  ashby_is_remote: Boolean
  ashby_job_url: String
  ashby_secondary_locations: [AshbySecondaryLocation!]
  ashby_team: String
  company: Company
  company_id: Int
  company_key: String!
  company_name: String
  compliance: [GreenhouseCompliance!]
  created_at: String!
  data_compliance: [GreenhouseDataCompliance!]
  demographic_questions: GreenhouseDemographicQuestions
  departments: [GreenhouseDepartment!]
  description: String
  external_id: String!
  id: Int!
  internal_job_id: String
  """
  Whether this job is classified as Remote EU — read directly from the DB column.
  """
  is_remote_eu: Boolean!
  language: String
  location: String
  location_questions: [GreenhouseQuestion!]
  metadata: [GreenhouseMetadata!]
  offices: [GreenhouseOffice!]
  """
  Canonical publication date. All ATS sources (Greenhouse, Ashby)
  write to the unified first_published DB column at ingestion time.
  Falls back to posted_at (ingestion timestamp) when no ATS date exists.
  """
  publishedAt: String!
  questions: [GreenhouseQuestion!]
  recruiter: Contact
  remote_eu_confidence: ClassificationConfidence
  remote_eu_reason: String
  requisition_id: String
  score: Float
  score_reason: String
  skillMatch: SkillMatch
  skills: [JobSkill!]
  source_id: String
  source_kind: String!
  status: JobStatus
  title: String!
  updated_at: String!
  url: String!
}

type JobSkill {
  confidence: Float
  evidence: String
  level: String!
  tag: String!
}

"""
Pipeline status for a job posting.
Mirrors workers/process-jobs/src/entry.py JobStatus enum — values must stay in sync.
"""
enum JobStatus {
  enhanced
  error
  eu_remote
  new
  non_eu
  reported
  role_match
  role_nomatch
}

type JobsResponse {
  jobs: [Job!]!
  totalCount: Int!
}

type LangSmithPrompt {
  createdAt: String!
  description: String
  fullName: String!
  id: String!
  isArchived: Boolean!
  isPublic: Boolean!
  lastCommitHash: String
  likedByAuthUser: Boolean!
  numCommits: Int!
  numDownloads: Int!
  numLikes: Int!
  numViews: Int!
  owner: String
  promptHandle: String!
  readme: String
  tags: [String!]!
  tenantId: String!
  updatedAt: String!
}

type LangSmithPromptCommit {
  commitHash: String!
  examples: [JSON!]!
  manifest: JSON!
  owner: String!
  promptName: String!
}

type MarkRepliedResult {
  message: String
  success: Boolean!
}

type MergeCompaniesResult {
  keptCompanyId: Int
  merged: Int!
  message: String!
  success: Boolean!
}

type MergeDuplicateContactsResult {
  mergedCount: Int!
  message: String!
  removedCount: Int!
  success: Boolean!
}

type Mutation {
  add_company_facts(company_id: Int!, facts: [CompanyFactInput!]!): [CompanyFact!]!
  analyzeCompany(id: Int, key: String): AnalyzeCompanyResponse!
  applyEmailPattern(companyId: Int!): ApplyEmailPatternResult!
  archiveEmail(id: Int!): ArchiveEmailResult!
  archiveJob(id: Int!): Job!
  blockCompany(name: String!, reason: String): BlockedCompany!
  blockJobsByCompany(companyName: String!): BlockJobsResult!
  cancelCompanyEmails(companyId: Int!): CancelCompanyEmailsResult!
  cancelScheduledEmail(resendId: String!): CancelEmailResult!
  completeTask(id: Int!): Task!
  createApplication(input: ApplicationInput!): Application!
  createCompany(input: CreateCompanyInput!): Company!
  createContact(input: CreateContactInput!): Contact!
  createDraftCampaign(input: CreateCampaignInput!): EmailCampaign!
  createEmailTemplate(input: CreateEmailTemplateInput!): EmailTemplate!
  createLangSmithPrompt(input: CreateLangSmithPromptInput, promptIdentifier: String!): LangSmithPrompt!
  createOpportunity(input: CreateOpportunityInput!): Opportunity!
  createPrompt(input: CreatePromptInput!): Prompt!
  createTask(input: CreateTaskInput!): Task!
  deleteAllJobs: DeleteJobResponse!
  deleteApplication(id: Int!): DeleteApplicationResponse!
  deleteCampaign(id: String!): DeleteCampaignResult!
  deleteCompanies(companyIds: [Int!]!): DeleteCompaniesResult!
  deleteCompany(id: Int!): DeleteCompanyResponse!
  deleteContact(id: Int!): DeleteContactResult!
  deleteEmailTemplate(id: Int!): DeleteEmailTemplateResult!
  deleteJob(id: Int!): DeleteJobResponse!
  deleteLangSmithPrompt(promptIdentifier: String!): Boolean!
  deleteOpportunity(id: String!): DeleteOpportunityResult!
  deleteStackEntry(name: String!): StackMutationResponse!
  deleteTask(id: Int!): DeleteTaskResult!
  enhanceAllContacts: EnhanceAllContactsResult!
  enhanceCompany(id: Int, key: String): EnhanceCompanyResponse!
  """
  Enhance a job posting by fetching detailed data from the ATS (Applicant Tracking System).
  
  Supported ATS sources:
  - greenhouse: Greenhouse ATS (https://greenhouse.io)
  - ashby: Ashby ATS (https://ashbyhq.com)
  
  For Greenhouse:
  - jobId: The job posting ID from the URL (e.g., "5802159004" from https://job-boards.greenhouse.io/grafanalabs/jobs/5802159004)
  - company: The board token (e.g., "grafanalabs")
  
  For Ashby:
  - jobId: The posting ID
  - company: The board name
  
  The mutation will:
  1. Fetch comprehensive job data from the ATS API
  2. Save enhanced fields (description, departments, offices, questions, etc.)
  3. Return the updated job with full ATS data
  """
  enhanceJobFromATS(company: String!, jobId: String!, source: String!): EnhanceJobResponse!
  findCompanyEmails(companyId: Int!): EnhanceAllContactsResult!
  findContactEmail(contactId: Int!): FindContactEmailResult!
  generateEmail(input: GenerateEmailInput!): GenerateEmailResult!
  generateReply(input: GenerateReplyInput!): GenerateReplyResult!
  importCompanies(companies: [CompanyImportInput!]!): ImportCompaniesResult!
  importCompanyWithContacts(input: ImportCompanyWithContactsInput!): ImportCompanyResult!
  importContacts(contacts: [ContactInput!]!): ImportContactsResult!
  ingestResumeParse(email: String!, filename: String!, job_id: String!): ResumeIngestResult
  ingest_company_snapshot(capture_timestamp: String, company_id: Int!, content_hash: String, crawl_id: String, evidence: EvidenceInput!, extracted: JSON, fetched_at: String!, http_status: Int, jsonld: JSON, mime: String, source_url: String!, text_sample: String): CompanySnapshot!
  launchEmailCampaign(id: String!): EmailCampaign!
  markContactEmailVerified(contactId: Int!, verified: Boolean!): Contact!
  markEmailReplied(resendId: String!): MarkRepliedResult!
  markJobApplied(id: Int!): Job!
  mergeDuplicateCompanies(companyIds: [Int!]!): MergeCompaniesResult!
  mergeDuplicateContacts(companyId: Int!): MergeDuplicateContactsResult!
  previewEmail(input: PreviewEmailInput!): EmailPreview!
  """
  Trigger classification/enhancement of all unprocessed jobs via the Cloudflare Worker.
  Calls the classify-jobs CF worker (POST) which runs DeepSeek-based classification
  for remote-EU eligibility on every unclassified job.
  """
  processAllJobs(limit: Int): ProcessAllJobsResponse!
  pushLangSmithPrompt(input: PushLangSmithPromptInput, promptIdentifier: String!): String!
  rateResumeAnswer(helpful: Boolean!, traceId: ID!): Boolean
  """
  Report a job as irrelevant, spam, or incorrectly classified.
  Sets the job status to "reported" so it can be reviewed or excluded.
  Requires authentication.
  """
  reportJob(id: Int!): Job
  scheduleBatchEmails(input: ScheduleBatchEmailsInput!): ScheduleBatchResult!
  scheduleFollowUpBatch(input: FollowUpBatchInput!): FollowUpBatchResult!
  sendEmail(input: SendEmailInput!): SendEmailResult!
  sendScheduledEmailNow(resendId: String!): SendNowResult!
  syncResendEmails(companyId: Int): SyncResendResult!
  unarchiveEmail(id: Int!): ArchiveEmailResult!
  unarchiveJob(id: Int!): Job!
  unblockCompany(id: Int!): DeleteBlockedCompanyResult!
  unverifyCompanyContacts(companyId: Int!): UnverifyContactsResult!
  updateApplication(id: Int!, input: UpdateApplicationInput!): Application!
  updateCampaign(id: String!, input: UpdateCampaignInput!): EmailCampaign!
  updateCompany(id: Int!, input: UpdateCompanyInput!): Company!
  updateContact(id: Int!, input: UpdateContactInput!): Contact!
  updateEmailTemplate(id: Int!, input: UpdateEmailTemplateInput!): EmailTemplate!
  updateLangSmithPrompt(input: UpdateLangSmithPromptInput!, promptIdentifier: String!): LangSmithPrompt!
  updateOpportunity(id: String!, input: UpdateOpportunityInput!): Opportunity!
  updatePromptLabel(label: String!, name: String!, version: Int!): Prompt!
  updateTask(id: Int!, input: UpdateTaskInput!): Task!
  updateUserSettings(settings: UserSettingsInput!, userId: String!): UserSettings!
  uploadResume(email: String!, filename: String!, resumePdf: String!): ResumeUploadResult
  upsert_company_ats_boards(boards: [ATSBoardUpsertInput!]!, company_id: Int!): [ATSBoard!]!
  verifyContactEmail(contactId: Int!): VerifyEmailResult!
}

type OpportunitiesResult {
  opportunities: [Opportunity!]!
  totalCount: Int!
}

type Opportunity {
  applicationNotes: String
  applicationStatus: String
  applied: Boolean!
  appliedAt: String
  company: Company
  companyId: Int
  contactId: Int
  createdAt: String!
  deadline: String
  endDate: String
  firstSeen: String
  id: String!
  lastSeen: String
  metadata: JSON
  rawContext: String
  rewardText: String
  rewardUsd: Float
  score: Int
  source: String
  startDate: String
  status: String!
  tags: [String!]!
  title: String!
  updatedAt: String!
  url: String
}

input PreviewEmailInput {
  content: String!
  drySend: Boolean
  recipientEmail: String!
  subject: String!
}

"""Response from triggering the classify-jobs Cloudflare Worker"""
type ProcessAllJobsResponse {
  """Number of errors during ATS enhancement"""
  enhanceErrors: Int
  """Number of jobs enhanced with ATS data in this run"""
  enhanced: Int
  """Number of errors encountered during classification"""
  errors: Int
  """Number of jobs classified as EU-remote"""
  euRemote: Int
  message: String
  """Number of jobs classified as non-EU"""
  nonEuRemote: Int
  """Number of jobs classified in this run"""
  processed: Int
  success: Boolean!
}

type Prompt {
  chatMessages: [ChatMessage!]
  config: PromptConfig
  createdAt: String
  createdBy: String
  isUserSpecific: Boolean!
  labels: [String!]
  name: String!
  prompt: String
  tags: [String!]
  type: PromptType!
  updatedAt: String
  version: Int
}

type PromptConfig {
  max_tokens: Int
  model: String
  temperature: Float
  top_p: Float
}

input PromptConfigInput {
  max_tokens: Int
  model: String
  temperature: Float
  top_p: Float
}

enum PromptType {
  CHAT
  TEXT
}

type PromptUsage {
  label: String
  promptName: String!
  traceId: String
  usedAt: String!
  userEmail: String!
  version: Int
}

input PushLangSmithPromptInput {
  description: String
  isPublic: Boolean
  object: JSON
  parentCommitHash: String
  readme: String
  tags: [String!]
}

type Query {
  allCompanyTags: [String!]!
  application(id: Int!): Application
  applications: [Application!]!
  askAboutResume(email: String!, question: String!): ResumeAnswer
  blockedCompanies: [BlockedCompany!]!
  companies(filter: CompanyFilterInput, limit: Int, offset: Int, order_by: CompanyOrderBy): CompaniesResponse!
  company(id: Int, key: String): Company
  companyContactEmails(companyId: Int!): [CompanyContactEmail!]!
  company_ats_boards(company_id: Int!): [ATSBoard!]!
  company_facts(company_id: Int!, field: String, limit: Int, offset: Int): [CompanyFact!]!
  company_snapshots(company_id: Int!, limit: Int, offset: Int): [CompanySnapshot!]!
  contact(id: Int!): Contact
  contactByEmail(email: String!): Contact
  contactEmails(contactId: Int!): [ContactEmail!]!
  contacts(companyId: Int, limit: Int, offset: Int, search: String): ContactsResult!
  emailCampaign(id: String!): EmailCampaign
  emailCampaigns(limit: Int, offset: Int, status: String): EmailCampaignsResult!
  emailStats: EmailStats!
  emailTemplate(id: Int!): EmailTemplate
  emailTemplates(category: String, limit: Int, offset: Int): EmailTemplatesResult!
  emailsNeedingFollowUp(limit: Int, offset: Int): FollowUpEmailsResult!
  executeSql(sql: String!): TextToSqlResult!
  findCompany(name: String, website: String): FindCompanyResult!
  job(id: String!): Job
  jobs(excludedCompanies: [String!], limit: Int, offset: Int, remoteEuConfidence: String, search: String, showAll: Boolean, skills: [String!], sourceType: String, sourceTypes: [String!]): JobsResponse!
  langsmithPrompt(promptIdentifier: String!): LangSmithPrompt
  langsmithPromptCommit(includeModel: Boolean, promptIdentifier: String!): LangSmithPromptCommit
  langsmithPrompts(isArchived: Boolean, isPublic: Boolean, query: String): [LangSmithPrompt!]!
  myPromptUsage(limit: Int): [PromptUsage!]!
  opportunities(companyId: Int, limit: Int, offset: Int, status: String): OpportunitiesResult!
  opportunity(id: String!): Opportunity
  prompt(label: String, name: String!, version: Int): Prompt
  prompts: [RegisteredPrompt!]!
  receivedEmail(id: Int!): ReceivedEmail
  receivedEmails(archived: Boolean, limit: Int, offset: Int): ReceivedEmailsResult!
  resendEmail(resendId: String!): ResendEmailDetail
  resumeStatus(email: String!): ResumeStatus
  task(id: Int!): Task
  tasks(limit: Int, offset: Int, priority: String, status: String): TasksResult!
  textToSql(question: String!): TextToSqlResult!
  userSettings(userId: String!): UserSettings
}

type QuestionAnswer {
  answerText: String!
  questionId: String!
  questionText: String!
}

input QuestionAnswerInput {
  answerText: String!
  questionId: String!
  questionText: String!
}

type ReceivedEmail {
  archivedAt: String
  attachments: JSON
  ccEmails: [String!]!
  createdAt: String!
  fromEmail: String
  htmlContent: String
  id: Int!
  messageId: String
  receivedAt: String!
  replyToEmails: [String!]!
  resendId: String!
  subject: String
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

type ReceivedEmailsResult {
  emails: [ReceivedEmail!]!
  totalCount: Int!
}

type RegisteredPrompt {
  content: JSON
  labels: [String!]!
  lastConfig: JSON
  lastUpdatedAt: String!
  lastUsedBy: String
  name: String!
  tags: [String!]!
  type: String!
  usageCount: Int
  versions: [Int!]!
}

type ResendEmailDetail {
  bcc: [String!]
  cc: [String!]
  createdAt: String!
  from: String!
  html: String
  id: String!
  lastEvent: String
  scheduledAt: String
  subject: String
  text: String
  to: [String!]!
}

type ResumeAnswer {
  answer: String!
  context_count: Int!
  trace_id: String
}

type ResumeIngestResult {
  chunks_stored: Int
  error: String
  job_id: String!
  resume_id: String
  status: String!
  success: Boolean!
}

type ResumeStatus {
  chunk_count: Int
  exists: Boolean!
  filename: String
  ingested_at: String
  resume_id: String
}

type ResumeUploadResult {
  job_id: String!
  status: String!
  success: Boolean!
  tier: String!
}

input ScheduleBatchEmailsInput {
  body: String!
  """Recipients with name and email"""
  recipients: [BatchRecipientInput!]!
  subject: String!
  """Use business day scheduling (Mon-Fri, 8am UTC, random delays)"""
  useScheduler: Boolean
}

type ScheduleBatchResult {
  failed: Int!
  firstSendDate: String
  lastSendDate: String
  message: String!
  scheduled: Int!
  schedulingPlan: String
  success: Boolean!
}

input SendEmailInput {
  from: String
  html: String!
  replyTo: String
  scheduledAt: String
  subject: String!
  text: String
  to: String!
}

type SendEmailResult {
  error: String
  id: String
  success: Boolean!
}

type SendNowResult {
  error: String
  resendId: String
  success: Boolean!
}

type SkillMatch {
  details: [SkillMatchDetail!]!
  jobCoverage: Float!
  matchedCount: Int!
  requiredCoverage: Float!
  score: Float!
  totalPreferred: Int!
  userCoverage: Float!
}

type SkillMatchDetail {
  level: String!
  matched: Boolean!
  tag: String!
}

enum SourceType {
  COMMONCRAWL
  LIVE_FETCH
  MANUAL
  PARTNER
}

type StackMutationResponse {
  message: String
  success: Boolean!
}

type SyncResendResult {
  error: String
  skippedCount: Int!
  success: Boolean!
  totalCount: Int!
  updatedCount: Int!
}

type Task {
  completedAt: String
  createdAt: String!
  description: String
  dueDate: String
  entityId: String
  entityType: String
  id: Int!
  priority: String!
  status: String!
  tags: [String!]!
  title: String!
  updatedAt: String!
}

type TasksResult {
  tasks: [Task!]!
  totalCount: Int!
}

type TextToSqlResult {
  columns: [String!]!
  drilldownSearchQuery: String
  explanation: String
  rows: [[JSON]]!
  sql: String!
}

scalar URL

type UnverifyContactsResult {
  count: Int!
  success: Boolean!
}

input UpdateApplicationInput {
  companyName: String
  jobDescription: String
  notes: String
  status: ApplicationStatus
}

input UpdateCampaignInput {
  addAntiThreadHeader: Boolean
  addUnsubscribeHeaders: Boolean
  delayDays: JSON
  fromEmail: String
  mode: String
  name: String
  recipientEmails: [String!]
  replyTo: String
  sequence: JSON
  startAt: String
  status: String
  totalEmailsPlanned: Int
  unsubscribeUrl: String
}

input UpdateCompanyInput {
  ai_classification_confidence: Float
  ai_classification_reason: String
  ai_tier: Int
  category: CompanyCategory
  description: String
  email: String
  emails: [String!]
  github_url: String
  industries: [String!]
  industry: String
  is_hidden: Boolean
  job_board_url: String
  key: String
  linkedin_url: String
  location: String
  logo_url: String
  name: String
  score: Float
  score_reasons: [String!]
  service_taxonomy: [String!]
  services: [String!]
  size: String
  tags: [String!]
  website: String
}

input UpdateContactInput {
  doNotContact: Boolean
  email: String
  emails: [String!]
  firstName: String
  githubHandle: String
  lastName: String
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

input UpdateEmailTemplateInput {
  category: String
  description: String
  htmlContent: String
  isActive: Boolean
  name: String
  subject: String
  tags: [String!]
  textContent: String
  variables: [String!]
}

input UpdateLangSmithPromptInput {
  description: String
  isArchived: Boolean
  isPublic: Boolean
  readme: String
  tags: [String!]
}

input UpdateOpportunityInput {
  applicationNotes: String
  applicationStatus: String
  applied: Boolean
  appliedAt: String
  companyId: Int
  contactId: Int
  deadline: String
  endDate: String
  rewardText: String
  rewardUsd: Float
  score: Int
  source: String
  startDate: String
  status: String
  tags: [String!]
  title: String
  url: String
}

input UpdateTaskInput {
  description: String
  dueDate: String
  entityId: String
  entityType: String
  priority: String
  status: String
  tags: [String!]
  title: String
}

scalar Upload

type UserSettings {
  created_at: String!
  daily_digest: Boolean!
  dark_mode: Boolean!
  email_notifications: Boolean!
  excluded_companies: [String!]
  id: Int!
  jobs_per_page: Int!
  new_job_alerts: Boolean!
  preferred_locations: [String!]
  preferred_skills: [String!]
  updated_at: String!
  user_id: String!
}

input UserSettingsInput {
  daily_digest: Boolean
  dark_mode: Boolean
  email_notifications: Boolean
  excluded_companies: [String!]
  jobs_per_page: Int
  new_job_alerts: Boolean
  preferred_locations: [String!]
  preferred_skills: [String!]
}

type VerifyEmailResult {
  flags: [String!]
  message: String!
  rawResult: String
  success: Boolean!
  suggestedCorrection: String
  verified: Boolean
}

type WarcPointer {
  digest: String
  filename: String!
  length: Int!
  offset: Int!
}

input WarcPointerInput {
  digest: String
  filename: String!
  length: Int!
  offset: Int!
}
`;