// This file is auto-generated by GraphQL Code Generator.
// Do not edit manually. Run `pnpm codegen` to regenerate.

export const typeDefs = /* GraphQL */ `
schema {
  query: Query
  mutation: Mutation
}

type AIBackendPrep {
  aiMlIntegration: BackendPrepSection
  apiDesign: BackendPrepSection
  authSecurity: BackendPrepSection
  caching: BackendPrepSection
  concurrencyAsync: BackendPrepSection
  databaseDesign: BackendPrepSection
  devops: BackendPrepSection
  distributedSystems: BackendPrepSection
  eventDriven: BackendPrepSection
  generatedAt: String!
  messageQueues: BackendPrepSection
  microservices: BackendPrepSection
  nosqlPatterns: BackendPrepSection
  observability: BackendPrepSection
  performance: BackendPrepSection
  securityOwasp: BackendPrepSection
  serverlessEdge: BackendPrepSection
  sqlOptimization: BackendPrepSection
  systemDesign: BackendPrepSection
  testing: BackendPrepSection
  typescriptNode: BackendPrepSection
}

type AIInterviewPrep {
  generatedAt: String!
  requirements: [AIInterviewPrepRequirement!]!
  summary: String!
}

type AIInterviewPrepRequirement {
  deepDive: String
  questions: [String!]!
  requirement: String!
  sourceQuote: String
  studyTopicDeepDives: [AIStudyTopicDeepDive!]!
  studyTopics: [String!]!
}

type AIInterviewQuestion {
  category: String!
  question: String!
  reason: String!
}

type AIInterviewQuestions {
  companyContext: String!
  recruiterGeneratedAt: String
  recruiterQuestions: [AIInterviewQuestion!]!
  technicalGeneratedAt: String
  technicalQuestions: [AIInterviewQuestion!]!
}

type AIStudyTopicDeepDive {
  deepDive: String!
  topic: String!
}

type ATSBoard {
  board_type: ATSBoardType!
  company_id: Int!
  confidence: Float!
  created_at: String!
  evidence: Evidence!
  first_seen_at: String!
  id: Int!
  is_active: Boolean!
  last_seen_at: String!
  updated_at: String!
  url: String!
  vendor: ATSVendor!
}

enum ATSBoardType {
  BOARD_API
  BOARD_WIDGET
  JOBS_PAGE
  UNKNOWN
}

input ATSBoardUpsertInput {
  board_type: ATSBoardType!
  confidence: Float!
  evidence: EvidenceInput!
  is_active: Boolean!
  last_seen_at: String!
  url: String!
  vendor: ATSVendor!
}

enum ATSVendor {
  ASHBY
  BREEZYHR
  GREENHOUSE
  ICIMS
  JAZZHR
  JOBVITE
  LEVER
  ORACLE_TALEO
  OTHER
  SAP_SUCCESSFACTORS
  SMARTRECRUITERS
  TEAMTAILOR
  WORKABLE
}

type AgenticCoding {
  exercises: [AgenticCodingExercise!]!
  failureModes: [AgenticCodingFailureMode!]
  generatedAt: String!
  measurableOutcomes: [AgenticCodingOutcome!]
  overview: String!
  promptTemplates: [AgenticCodingPromptTemplate!]
  qaApproach: String
  resources: [AgenticCodingResource!]!
  teamPractices: String
  workflowPattern: String
}

type AgenticCodingExercise {
  agentPrompt: String!
  description: String!
  difficulty: String!
  hints: [String!]!
  skills: [String!]!
  title: String!
}

type AgenticCodingFailureMode {
  alternative: String!
  scenario: String!
  why: String!
}

type AgenticCodingOutcome {
  afterTime: String!
  beforeTime: String!
  improvement: String!
  task: String!
}

type AgenticCodingPromptTemplate {
  prompt: String!
  purpose: String!
  stackContext: String!
  title: String!
}

type AgenticCodingResource {
  description: String!
  title: String!
  url: String!
}

type Application {
  agenticCoding: AgenticCoding
  aiBackendPrep: AIBackendPrep
  aiInterviewPrep: AIInterviewPrep
  aiInterviewQuestions: AIInterviewQuestions
  companyKey: String
  companyName: String
  createdAt: String!
  email: EmailAddress!
  id: Int!
  interviewPrep: [Track!]!
  jobDescription: String
  jobId: String!
  jobTitle: String
  notes: String
  questions: [QuestionAnswer!]!
  resume: Upload
  status: ApplicationStatus!
}

input ApplicationInput {
  companyName: String
  jobId: String
  jobTitle: String
  questions: [QuestionAnswerInput!]!
  resume: Upload
}

"""
Pipeline status for a tracked job application.
Maps to a kanban column in the UI.
"""
enum ApplicationStatus {
  accepted
  pending
  rejected
  reviewed
  submitted
}

type ApplyEmailPatternResult {
  contacts: [Contact!]!
  contactsUpdated: Int!
  message: String!
  pattern: String
  success: Boolean!
}

type AshbyAddress {
  postalAddress: AshbyPostalAddress
}

type AshbyCompensation {
  compensationTierSummary: String
  compensationTiers: [AshbyCompensationTier!]!
  scrapeableCompensationSalarySummary: String
  summaryComponents: [AshbyCompensationComponent!]!
}

type AshbyCompensationComponent {
  compensationType: String
  currencyCode: String
  id: String
  interval: String
  maxValue: Float
  minValue: Float
  summary: String
}

type AshbyCompensationTier {
  additionalInformation: String
  components: [AshbyCompensationComponent!]!
  id: String
  tierSummary: String
  title: String
}

type AshbyEnrichment {
  company_name: String
  enriched_at: String
  industry_tags: [String!]!
  size_signal: String
  tech_signals: [String!]!
}

type AshbyPostalAddress {
  addressCountry: String
  addressLocality: String
  addressRegion: String
}

type AshbySecondaryLocation {
  address: AshbyPostalAddress
  location: String!
}

type BackendPrepCodeExample {
  code: String!
  explanation: String!
  language: String!
  title: String!
}

type BackendPrepInterviewQuestion {
  difficulty: String!
  followUps: [String!]!
  idealAnswer: String!
  question: String!
}

type BackendPrepSection {
  codeExamples: [BackendPrepCodeExample!]!
  commonPitfalls: [String!]!
  deepDive: String!
  interviewQuestions: [BackendPrepInterviewQuestion!]!
  keyConcepts: [String!]!
  overview: String!
  researchInsights: String
  talkingPoints: [String!]!
  title: String!
}

type ChatMessage {
  content: String!
  role: String!
}

input ChatMessageInput {
  content: String!
  role: String!
}

"""Confidence level of a classification result."""
enum ClassificationConfidence {
  high
  low
  medium
}

type CompaniesResponse {
  companies: [Company!]!
  totalCount: Int!
}

type Company {
  ai_classification_confidence: Float!
  ai_classification_reason: String
  ai_tier: Int!
  ashby_enrichment: AshbyEnrichment
  ats_boards: [ATSBoard!]!
  category: CompanyCategory!
  contacts: [Contact!]!
  created_at: String!
  description: String
  facts(field: String, limit: Int, offset: Int): [CompanyFact!]!
  facts_count: Int!
  id: Int!
  industries: [String!]!
  industry: String
  is_hidden: Boolean!
  job_board_url: String
  key: String!
  last_seen_capture_timestamp: String
  last_seen_crawl_id: String
  last_seen_source_url: String
  linkedin_url: String
  location: String
  logo_url: String
  name: String!
  opportunities: [Opportunity!]!
  score: Float!
  score_reasons: [String!]!
  service_taxonomy: [String!]!
  services: [String!]!
  size: String
  snapshots(limit: Int, offset: Int): [CompanySnapshot!]!
  snapshots_count: Int!
  tags: [String!]!
  updated_at: String!
  website: String
}

enum CompanyCategory {
  AGENCY
  CONSULTANCY
  DIRECTORY
  OTHER
  PRODUCT
  STAFFING
  UNKNOWN
}

type CompanyFact {
  company_id: Int!
  confidence: Float!
  created_at: String!
  evidence: Evidence!
  field: String!
  id: Int!
  normalized_value: JSON
  value_json: JSON
  value_text: String
}

input CompanyFactInput {
  confidence: Float!
  evidence: EvidenceInput!
  field: String!
  normalized_value: JSON
  value_json: JSON
  value_text: String
}

input CompanyFilterInput {
  category_in: [CompanyCategory!]
  has_ats_boards: Boolean
  is_hidden: Boolean
  min_ai_tier: Int
  min_score: Float
  service_taxonomy_any: [String!]
  text: String
}

enum CompanyOrderBy {
  CREATED_AT_DESC
  NAME_ASC
  SCORE_DESC
  UPDATED_AT_DESC
}

type CompanySnapshot {
  capture_timestamp: String
  company_id: Int!
  content_hash: String
  crawl_id: String
  created_at: String!
  evidence: Evidence!
  extracted: JSON
  fetched_at: String!
  http_status: Int
  id: Int!
  jsonld: JSON
  mime: String
  source_url: String!
  text_sample: String
}

type Contact {
  bouncedEmails: [String!]!
  company: String
  companyId: Int
  createdAt: String!
  doNotContact: Boolean!
  email: String
  emailVerified: Boolean
  emails: [String!]!
  firstName: String!
  githubHandle: String
  id: Int!
  lastName: String!
  linkedinUrl: String
  nbExecutionTimeMs: Int
  nbFlags: [String!]!
  nbResult: String
  nbRetryToken: String
  nbStatus: String
  nbSuggestedCorrection: String
  position: String
  tags: [String!]!
  telegramHandle: String
  updatedAt: String!
  userId: String
}

type ContactEmail {
  contactId: Int!
  createdAt: String!
  fromEmail: String!
  id: Int!
  recipientName: String
  resendId: String!
  sentAt: String
  status: String!
  subject: String!
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

input ContactInput {
  company: String
  companyId: Int
  email: String
  emails: [String!]
  firstName: String!
  githubHandle: String
  lastName: String!
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

type ContactsResult {
  contacts: [Contact!]!
  totalCount: Int!
}

input CreateCompanyInput {
  ai_classification_confidence: Float
  ai_classification_reason: String
  ai_tier: Int
  category: CompanyCategory
  description: String
  industries: [String!]
  industry: String
  key: String!
  linkedin_url: String
  location: String
  logo_url: String
  name: String!
  service_taxonomy: [String!]
  services: [String!]
  size: String
  tags: [String!]
  website: String
}

input CreateContactInput {
  companyId: Int
  email: String
  emails: [String!]
  firstName: String!
  githubHandle: String
  lastName: String
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

input CreateLangSmithPromptInput {
  description: String
  isPublic: Boolean
  readme: String
  tags: [String!]
}

input CreateOpportunityInput {
  applicationNotes: String
  companyId: Int
  contactId: Int
  deadline: String
  endDate: String
  rewardText: String
  rewardUsd: Float
  source: String
  startDate: String
  status: String
  tags: [String!]
  title: String!
  url: String
}

input CreatePromptInput {
  chatMessages: [ChatMessageInput!]
  config: PromptConfigInput
  labels: [String!]
  name: String!
  prompt: String
  tags: [String!]
  type: PromptType!
}

input CreateTrackInput {
  description: String
  level: String
  slug: String!
  title: String!
}

scalar DateTime

type DeleteApplicationResponse {
  message: String
  success: Boolean!
}

type DeleteCompanyResponse {
  message: String
  success: Boolean!
}

type DeleteContactResult {
  message: String!
  success: Boolean!
}

type DeleteJobResponse {
  message: String
  success: Boolean!
}

type DeleteOpportunityResult {
  message: String
  success: Boolean!
}

scalar EmailAddress

type EnhanceAllContactsResult {
  companiesProcessed: Int!
  errors: [String!]!
  message: String!
  success: Boolean!
  totalContactsProcessed: Int!
  totalEmailsFound: Int!
}

type EnhanceCompanyResponse {
  companyId: Int
  companyKey: String
  message: String
  success: Boolean!
}

"""Response from enhancing a job with ATS data"""
type EnhanceJobResponse {
  """The updated job record with enhanced data from the ATS"""
  job: Job
  """Human-readable message about the operation result"""
  message: String
  """Whether the enhancement was successful"""
  success: Boolean!
}

type Evidence {
  capture_timestamp: String
  content_hash: String
  crawl_id: String
  extractor_version: String
  http_status: Int
  method: ExtractMethod!
  mime: String
  observed_at: String!
  source_type: SourceType!
  source_url: String!
  warc: WarcPointer
}

input EvidenceInput {
  capture_timestamp: String
  content_hash: String
  crawl_id: String
  extractor_version: String
  http_status: Int
  method: ExtractMethod!
  mime: String
  observed_at: String!
  source_type: SourceType!
  source_url: String!
  warc: WarcPointerInput
}

enum ExtractMethod {
  DOM
  HEURISTIC
  JSONLD
  LLM
  META
}

type FindContactEmailResult {
  candidatesTried: Int!
  email: String
  emailFound: Boolean!
  message: String!
  success: Boolean!
  verified: Boolean
}

type GreenhouseCompliance {
  description: String
  questions: [GreenhouseQuestion!]
  type: String!
}

type GreenhouseDataCompliance {
  demographic_data_consent_applies: Boolean!
  requires_consent: Boolean!
  requires_processing_consent: Boolean!
  requires_retention_consent: Boolean!
  retention_period: Int
  type: String!
}

type GreenhouseDemographicQuestions {
  description: String
  header: String
  questions: [GreenhouseQuestion!]
}

type GreenhouseDepartment {
  child_ids: [String!]
  id: String!
  name: String!
  parent_id: String
}

type GreenhouseMetadata {
  id: String!
  name: String!
  value: String
  value_type: String
}

type GreenhouseOffice {
  child_ids: [String!]
  id: String!
  location: String
  name: String!
  parent_id: String
}

type GreenhouseQuestion {
  description: String
  fields: [GreenhouseQuestionField!]
  label: String!
  required: Boolean!
}

type GreenhouseQuestionField {
  name: String
  type: String!
}

type ImportContactsResult {
  errors: [String!]!
  failed: Int!
  imported: Int!
  success: Boolean!
}

scalar JSON

type Job {
  absolute_url: String
  ashby_address: AshbyAddress
  ashby_apply_url: String
  ashby_compensation: AshbyCompensation
  ashby_department: String
  ashby_employment_type: String
  ashby_is_listed: Boolean
  ashby_is_remote: Boolean
  ashby_job_url: String
  ashby_secondary_locations: [AshbySecondaryLocation!]
  ashby_team: String
  company: Company
  company_id: Int
  company_key: String!
  company_name: String
  compliance: [GreenhouseCompliance!]
  created_at: String!
  data_compliance: [GreenhouseDataCompliance!]
  demographic_questions: GreenhouseDemographicQuestions
  departments: [GreenhouseDepartment!]
  description: String
  external_id: String!
  id: Int!
  internal_job_id: String
  """
  Whether this job is classified as Remote EU — read directly from the DB column.
  """
  is_remote_eu: Boolean!
  language: String
  location: String
  location_questions: [GreenhouseQuestion!]
  metadata: [GreenhouseMetadata!]
  offices: [GreenhouseOffice!]
  """
  Canonical publication date. All ATS sources (Greenhouse, Ashby)
  write to the unified first_published DB column at ingestion time.
  Falls back to posted_at (ingestion timestamp) when no ATS date exists.
  """
  publishedAt: String!
  questions: [GreenhouseQuestion!]
  remote_eu_confidence: ClassificationConfidence
  remote_eu_reason: String
  requisition_id: String
  score: Float
  score_reason: String
  skillMatch: SkillMatch
  skills: [JobSkill!]
  source_id: String
  source_kind: String!
  status: JobStatus
  title: String!
  updated_at: String!
  url: String!
}

type JobSkill {
  confidence: Float
  evidence: String
  level: String!
  tag: String!
}

"""
Pipeline status for a job posting.
Mirrors workers/process-jobs/src/entry.py JobStatus enum — values must stay in sync.
"""
enum JobStatus {
  enhanced
  error
  eu_remote
  new
  non_eu
  reported
  role_match
  role_nomatch
}

type JobsResponse {
  jobs: [Job!]!
  totalCount: Int!
}

type LangSmithPrompt {
  createdAt: String!
  description: String
  fullName: String!
  id: String!
  isArchived: Boolean!
  isPublic: Boolean!
  lastCommitHash: String
  likedByAuthUser: Boolean!
  numCommits: Int!
  numDownloads: Int!
  numLikes: Int!
  numViews: Int!
  owner: String
  promptHandle: String!
  readme: String
  tags: [String!]!
  tenantId: String!
  updatedAt: String!
}

type LangSmithPromptCommit {
  commitHash: String!
  examples: [JSON!]!
  manifest: JSON!
  owner: String!
  promptName: String!
}

type Mutation {
  add_company_facts(company_id: Int!, facts: [CompanyFactInput!]!): [CompanyFact!]!
  applyEmailPattern(companyId: Int!): ApplyEmailPatternResult!
  createApplication(input: ApplicationInput!): Application!
  createCompany(input: CreateCompanyInput!): Company!
  createContact(input: CreateContactInput!): Contact!
  createLangSmithPrompt(input: CreateLangSmithPromptInput, promptIdentifier: String!): LangSmithPrompt!
  createOpportunity(input: CreateOpportunityInput!): Opportunity!
  createPrompt(input: CreatePromptInput!): Prompt!
  createStudyTopic(category: String, difficulty: String, summary: String, tags: [String!], title: String, topic: String): StudyTopic!
  createTrack(input: CreateTrackInput!): Track!
  deleteAllJobs: DeleteJobResponse!
  deleteApplication(id: Int!): DeleteApplicationResponse!
  deleteCompany(id: Int!): DeleteCompanyResponse!
  deleteContact(id: Int!): DeleteContactResult!
  deleteJob(id: Int!): DeleteJobResponse!
  deleteLangSmithPrompt(promptIdentifier: String!): Boolean!
  deleteOpportunity(id: String!): DeleteOpportunityResult!
  deleteStackEntry(name: String!): StackMutationResponse!
  enhanceAllContacts: EnhanceAllContactsResult!
  enhanceCompany(id: Int, key: String): EnhanceCompanyResponse!
  """
  Enhance a job posting by fetching detailed data from the ATS (Applicant Tracking System).
  
  Supported ATS sources:
  - greenhouse: Greenhouse ATS (https://greenhouse.io)
  - ashby: Ashby ATS (https://ashbyhq.com)
  
  For Greenhouse:
  - jobId: The job posting ID from the URL (e.g., "5802159004" from https://job-boards.greenhouse.io/grafanalabs/jobs/5802159004)
  - company: The board token (e.g., "grafanalabs")
  
  For Ashby:
  - jobId: The posting ID
  - company: The board name
  
  The mutation will:
  1. Fetch comprehensive job data from the ATS API
  2. Save enhanced fields (description, departments, offices, questions, etc.)
  3. Return the updated job with full ATS data
  """
  enhanceJobFromATS(company: String!, jobId: String!, source: String!): EnhanceJobResponse!
  findCompanyEmails(companyId: Int!): EnhanceAllContactsResult!
  findContactEmail(contactId: Int!): FindContactEmailResult!
  generateAgenticCoding(applicationId: Int!): Application!
  generateBackendPrep(applicationId: Int!): Application!
  generateInterviewPrep(applicationId: Int!): Application!
  generateInterviewQuestions(applicationId: Int!, type: String!): Application!
  generateRequirementFromSelection(applicationId: Int!, selectedText: String!): Application!
  generateResearch(goalDescription: String!): [ResearchItem!]!
  generateStudyConceptExplanation(context: String, selectedText: String!, studyTopicId: ID!): StudyConceptExplanation!
  generateStudyDeepDive(force: Boolean, studyTopicId: ID!): StudyTopic!
  generateStudyTopicDeepDive(applicationId: Int!, force: Boolean, requirement: String!, studyTopic: String!): Application!
  generateStudyTopicsForCategory(category: String!, count: Int): [StudyTopic!]!
  generateTopicDeepDive(applicationId: Int!, force: Boolean, requirement: String!): Application!
  importContacts(contacts: [ContactInput!]!): ImportContactsResult!
  ingestResumeParse(email: String!, filename: String!, job_id: String!): ResumeIngestResult
  ingest_company_snapshot(capture_timestamp: String, company_id: Int!, content_hash: String, crawl_id: String, evidence: EvidenceInput!, extracted: JSON, fetched_at: String!, http_status: Int, jsonld: JSON, mime: String, source_url: String!, text_sample: String): CompanySnapshot!
  linkSelectionToRequirement(applicationId: Int!, requirement: String!, sourceQuote: String!): Application!
  linkTrackToApplication(applicationId: Int!, trackSlug: String!): Application!
  """
  Trigger classification/enhancement of all unprocessed jobs via the Cloudflare Worker.
  Calls the classify-jobs CF worker (POST) which runs DeepSeek-based classification
  for remote-EU eligibility on every unclassified job.
  """
  processAllJobs(limit: Int): ProcessAllJobsResponse!
  pushLangSmithPrompt(input: PushLangSmithPromptInput, promptIdentifier: String!): String!
  rateResumeAnswer(helpful: Boolean!, traceId: ID!): Boolean
  """
  Report a job as irrelevant, spam, or incorrectly classified.
  Sets the job status to "reported" so it can be reviewed or excluded.
  Requires authentication.
  """
  reportJob(id: Int!): Job
  unlinkTrackFromApplication(applicationId: Int!, trackSlug: String!): Application!
  unverifyCompanyContacts(companyId: Int!): UnverifyContactsResult!
  updateApplication(id: Int!, input: UpdateApplicationInput!): Application!
  updateCompany(id: Int!, input: UpdateCompanyInput!): Company!
  updateContact(id: Int!, input: UpdateContactInput!): Contact!
  updateLangSmithPrompt(input: UpdateLangSmithPromptInput!, promptIdentifier: String!): LangSmithPrompt!
  updateOpportunity(id: String!, input: UpdateOpportunityInput!): Opportunity!
  updatePromptLabel(label: String!, name: String!, version: Int!): Prompt!
  updateUserSettings(settings: UserSettingsInput!, userId: String!): UserSettings!
  uploadResume(email: String!, filename: String!, resumePdf: String!): ResumeUploadResult
  upsert_company_ats_boards(boards: [ATSBoardUpsertInput!]!, company_id: Int!): [ATSBoard!]!
}

type OpportunitiesResult {
  opportunities: [Opportunity!]!
  totalCount: Int!
}

type Opportunity {
  applicationNotes: String
  applicationStatus: String
  applied: Boolean!
  appliedAt: String
  company: Company
  companyId: Int
  contactId: Int
  createdAt: String!
  deadline: String
  endDate: String
  firstSeen: String
  id: String!
  lastSeen: String
  metadata: JSON
  rawContext: String
  rewardText: String
  rewardUsd: Float
  score: Int
  source: String
  startDate: String
  status: String!
  tags: [String!]!
  title: String!
  updatedAt: String!
  url: String
}

type PrepCategory {
  description: String!
  emoji: String!
  id: String!
  name: String!
  resources: [PrepResource!]!
}

type PrepContent {
  categories: [PrepCategory!]!
  totalResources: Int!
}

type PrepResource {
  category: String!
  description: String!
  href: URL!
  id: String!
  tags: [String!]!
  title: String!
}

"""Response from triggering the classify-jobs Cloudflare Worker"""
type ProcessAllJobsResponse {
  """Number of errors during ATS enhancement"""
  enhanceErrors: Int
  """Number of jobs enhanced with ATS data in this run"""
  enhanced: Int
  """Number of errors encountered during classification"""
  errors: Int
  """Number of jobs classified as EU-remote"""
  euRemote: Int
  message: String
  """Number of jobs classified as non-EU"""
  nonEuRemote: Int
  """Number of jobs classified in this run"""
  processed: Int
  success: Boolean!
}

type Prompt {
  chatMessages: [ChatMessage!]
  config: PromptConfig
  createdAt: String
  createdBy: String
  isUserSpecific: Boolean!
  labels: [String!]
  name: String!
  prompt: String
  tags: [String!]
  type: PromptType!
  updatedAt: String
  version: Int
}

type PromptConfig {
  max_tokens: Int
  model: String
  temperature: Float
  top_p: Float
}

input PromptConfigInput {
  max_tokens: Int
  model: String
  temperature: Float
  top_p: Float
}

enum PromptType {
  CHAT
  TEXT
}

type PromptUsage {
  label: String
  promptName: String!
  traceId: String
  usedAt: String!
  userEmail: String!
  version: Int
}

input PushLangSmithPromptInput {
  description: String
  isPublic: Boolean
  object: JSON
  parentCommitHash: String
  readme: String
  tags: [String!]
}

type Query {
  application(id: Int!): Application
  applications: [Application!]!
  askAboutResume(email: String!, question: String!): ResumeAnswer
  companies(filter: CompanyFilterInput, limit: Int, offset: Int, order_by: CompanyOrderBy): CompaniesResponse!
  company(id: Int, key: String): Company
  company_ats_boards(company_id: Int!): [ATSBoard!]!
  company_facts(company_id: Int!, field: String, limit: Int, offset: Int): [CompanyFact!]!
  company_snapshots(company_id: Int!, limit: Int, offset: Int): [CompanySnapshot!]!
  contact(id: Int!): Contact
  contactByEmail(email: String!): Contact
  contactEmails(contactId: Int!): [ContactEmail!]!
  contacts(companyId: Int, limit: Int, offset: Int, search: String): ContactsResult!
  executeSql(sql: String!): TextToSqlResult!
  job(id: String!): Job
  jobs(excludedCompanies: [String!], limit: Int, offset: Int, remoteEuConfidence: String, search: String, showAll: Boolean, skills: [String!], sourceType: String, sourceTypes: [String!]): JobsResponse!
  langsmithPrompt(promptIdentifier: String!): LangSmithPrompt
  langsmithPromptCommit(includeModel: Boolean, promptIdentifier: String!): LangSmithPromptCommit
  langsmithPrompts(isArchived: Boolean, isPublic: Boolean, query: String): [LangSmithPrompt!]!
  myPromptUsage(limit: Int): [PromptUsage!]!
  opportunities(companyId: Int, limit: Int, offset: Int, status: String): OpportunitiesResult!
  opportunity(id: String!): Opportunity
  prepResources: PrepContent!
  prepResourcesByCategory(category: String!): [PrepResource!]!
  prompt(label: String, name: String!, version: Int): Prompt
  prompts: [RegisteredPrompt!]!
  resendEmail(resendId: String!): ResendEmailDetail
  resumeStatus(email: String!): ResumeStatus
  studyCategories: [String!]!
  studyTopic(category: String!, topic: String!): StudyTopic
  studyTopics(category: String!): [StudyTopic!]!
  textToSql(question: String!): TextToSqlResult!
  track(slug: String!): Track
  tracks(limit: Int = 50): [Track!]!
  userSettings(userId: String!): UserSettings
}

type QuestionAnswer {
  answerText: String!
  questionId: String!
  questionText: String!
}

input QuestionAnswerInput {
  answerText: String!
  questionId: String!
  questionText: String!
}

type RegisteredPrompt {
  content: JSON
  labels: [String!]!
  lastConfig: JSON
  lastUpdatedAt: String!
  lastUsedBy: String
  name: String!
  tags: [String!]!
  type: String!
  usageCount: Int
  versions: [Int!]!
}

type ResearchItem {
  id: String!
  relevance: String
  summary: String!
  title: String!
  url: URL!
}

type ResendEmailDetail {
  bcc: [String!]
  cc: [String!]
  createdAt: String!
  from: String!
  html: String
  id: String!
  lastEvent: String
  scheduledAt: String
  subject: String
  text: String
  to: [String!]!
}

type ResumeAnswer {
  answer: String!
  context_count: Int!
  trace_id: String
}

type ResumeIngestResult {
  chunks_stored: Int
  error: String
  job_id: String!
  resume_id: String
  status: String!
  success: Boolean!
}

type ResumeStatus {
  chunk_count: Int
  exists: Boolean!
  filename: String
  ingested_at: String
  resume_id: String
}

type ResumeUploadResult {
  job_id: String!
  status: String!
  success: Boolean!
  tier: String!
}

type SkillMatch {
  details: [SkillMatchDetail!]!
  jobCoverage: Float!
  matchedCount: Int!
  requiredCoverage: Float!
  score: Float!
  totalPreferred: Int!
  userCoverage: Float!
}

type SkillMatchDetail {
  level: String!
  matched: Boolean!
  tag: String!
}

enum SourceType {
  COMMONCRAWL
  LIVE_FETCH
  MANUAL
  PARTNER
}

type StackMutationResponse {
  message: String
  success: Boolean!
}

type StudyConceptExplanation {
  createdAt: DateTime!
  explanation: String!
  id: ID!
  selectedText: String!
}

type StudyTopic {
  bodyMd: String
  category: String!
  createdAt: DateTime!
  deepDive: String
  difficulty: String!
  id: ID!
  summary: String
  tags: [String!]!
  title: String!
  topic: String!
}

type TextToSqlResult {
  columns: [String!]!
  drilldownSearchQuery: String
  explanation: String
  rows: [[JSON]]!
  sql: String!
}

type Track {
  description: String
  id: ID!
  items: [TrackItem!]!
  level: String
  slug: String!
  title: String!
}

type TrackItem {
  children: [TrackItem!]!
  contentRef: String
  difficulty: Int
  id: ID!
  kind: String!
  position: Int!
  prereqs: [ID!]!
  promptRef: String
  tags: [String!]!
  title: String!
}

scalar URL

type UnverifyContactsResult {
  count: Int!
  success: Boolean!
}

input UpdateApplicationInput {
  companyName: String
  jobDescription: String
  notes: String
  status: ApplicationStatus
}

input UpdateCompanyInput {
  ai_classification_confidence: Float
  ai_classification_reason: String
  ai_tier: Int
  category: CompanyCategory
  description: String
  industries: [String!]
  industry: String
  is_hidden: Boolean
  job_board_url: String
  key: String
  linkedin_url: String
  location: String
  logo_url: String
  name: String
  score: Float
  score_reasons: [String!]
  service_taxonomy: [String!]
  services: [String!]
  size: String
  tags: [String!]
  website: String
}

input UpdateContactInput {
  doNotContact: Boolean
  email: String
  emails: [String!]
  firstName: String
  githubHandle: String
  lastName: String
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

input UpdateLangSmithPromptInput {
  description: String
  isArchived: Boolean
  isPublic: Boolean
  readme: String
  tags: [String!]
}

input UpdateOpportunityInput {
  applicationNotes: String
  applicationStatus: String
  applied: Boolean
  appliedAt: String
  companyId: Int
  contactId: Int
  deadline: String
  endDate: String
  rewardText: String
  rewardUsd: Float
  score: Int
  source: String
  startDate: String
  status: String
  tags: [String!]
  title: String
  url: String
}

scalar Upload

type UserSettings {
  created_at: String!
  daily_digest: Boolean!
  dark_mode: Boolean!
  email_notifications: Boolean!
  excluded_companies: [String!]
  id: Int!
  jobs_per_page: Int!
  new_job_alerts: Boolean!
  preferred_locations: [String!]
  preferred_skills: [String!]
  updated_at: String!
  user_id: String!
}

input UserSettingsInput {
  daily_digest: Boolean
  dark_mode: Boolean
  email_notifications: Boolean
  excluded_companies: [String!]
  jobs_per_page: Int
  new_job_alerts: Boolean
  preferred_locations: [String!]
  preferred_skills: [String!]
}

type WarcPointer {
  digest: String
  filename: String!
  length: Int!
  offset: Int!
}

input WarcPointerInput {
  digest: String
  filename: String!
  length: Int!
  offset: Int!
}
`;