from pydantic import BaseModel, Field
from typing import Literal
from datetime import datetime


class ListingExtraction(BaseModel):
    """Structured data extracted from a listing page by DeepSeek."""
    title: str
    price_eur: int | None = None
    price_local: float | None = None
    currency: str | None = None  # MDL, RON, EUR
    size_m2: float | None = None
    price_per_m2: float | None = None
    rooms: int | None = None
    floor: int | None = None
    total_floors: int | None = None
    zone: str | None = None
    city: str
    condition: Literal["new", "renovated", "good", "needs_renovation", "unknown"] = "unknown"
    features: list[str] = Field(default_factory=list)


class ValuationResult(BaseModel):
    """Valuation verdict generated by Qwen."""
    verdict: Literal["undervalued", "fair", "overvalued"]
    confidence: float = Field(ge=0.0, le=1.0)
    fair_value_eur_per_m2: int | None = None
    price_deviation_pct: float | None = None  # negative = undervalued, positive = overvalued
    reasoning: str
    key_factors: list[str] = Field(default_factory=list)


class ComparableListing(BaseModel):
    title: str
    price_eur: int | None = None
    size_m2: float | None = None
    price_per_m2: float | None = None
    rooms: int | None = None
    zone: str | None = None
    url: str | None = None
    source: str = "999md"
    deviation_pct: float | None = None  # vs analyzed listing (positive = comp is more expensive)


class ZoneStats(BaseModel):
    zone: str | None = None
    avg_price_per_m2: float | None = None
    median_price_per_m2: float | None = None
    min_price_per_m2: float | None = None
    max_price_per_m2: float | None = None
    count: int = 0


class AnalysisRequest(BaseModel):
    url: str


class AnalysisResponse(BaseModel):
    url: str
    source: Literal["999md", "imobiliare", "unknown"]
    listing: ListingExtraction
    valuation: ValuationResult
    analyzed_at: datetime
    comparables: list[ComparableListing] = Field(default_factory=list)
    zone_stats: ZoneStats | None = None
