from pydantic import BaseModel, Field
from typing import Literal
from datetime import datetime


class ListingExtraction(BaseModel):
    """Structured data extracted from a listing page by DeepSeek."""
    title: str
    price_eur: int | None = None
    price_local: float | None = None
    currency: str | None = None  # MDL, RON, EUR
    size_m2: float | None = None
    price_per_m2: float | None = None
    rooms: int | None = None
    floor: int | None = None
    total_floors: int | None = None
    zone: str | None = None
    city: str
    condition: Literal["new", "renovated", "good", "needs_renovation", "unknown"] = "unknown"
    features: list[str] = Field(default_factory=list)
    # Parking
    parking_included: bool | None = None   # True = parking price is in the listed price
    parking_price_eur: int | None = None   # Separate purchase price, or estimated value if included


class ScoreBreakdown(BaseModel):
    price_score: float = Field(ge=0.0, le=10.0)      # how attractive is the price vs fair value
    location_score: float = Field(ge=0.0, le=10.0)   # zone quality, POI access, growth prospects
    condition_score: float = Field(ge=0.0, le=10.0)  # physical state, age, renovation quality
    market_score: float = Field(ge=0.0, le=10.0)     # demand/supply dynamics in zone


class ValuationResult(BaseModel):
    """Valuation verdict generated by the valuator."""
    verdict: Literal["undervalued", "fair", "overvalued"]
    confidence: float = Field(ge=0.0, le=1.0)
    fair_value_eur_per_m2: int | None = None
    # Formula: (listing_price_per_m2 - fair_value_eur_per_m2) / fair_value_eur_per_m2 * 100
    # Negative = listing is cheaper than fair value (undervalued)
    # Positive = listing is more expensive than fair value (overvalued)
    price_deviation_pct: float | None = None
    reasoning: str
    key_factors: list[str] = Field(default_factory=list)
    # Extended evaluation
    investment_score: float | None = Field(default=None, ge=0.0, le=10.0)
    risk_factors: list[str] = Field(default_factory=list)
    opportunity_factors: list[str] = Field(default_factory=list)
    recommendation: Literal["strong_buy", "buy", "hold", "avoid"] | None = None
    market_context: str | None = None
    # Investment metrics
    rental_estimate_eur: int | None = None        # estimated monthly rent in EUR
    rental_yield_pct: float | None = None         # annual gross yield at asking price
    negotiation_margin_pct: float | None = Field(default=None, le=0.0)  # suggested negotiation discount (negative, e.g. -8.0)
    total_cost_eur: int | None = None             # apt + parking (if separate) + acquisition fees (~3%)
    liquidity: Literal["high", "medium", "low"] | None = None
    price_trend: Literal["rising", "stable", "declining"] | None = None
    # Enhanced eval metrics (previous session)
    score_breakdown: ScoreBreakdown | None = None
    fair_price_eur: int | None = None            # fair_value_eur_per_m2 * size_m2
    breakeven_years: float | None = None        # total_cost_eur / (rental_estimate_eur * 12 * 0.75)
    net_yield_pct: float | None = None          # (rental_estimate_eur * 12 * 0.75) / total_cost_eur * 100  [net of 25% expenses]
    appreciation_pct_1y: float | None = None    # expected price change % over next 12 months for this zone
    # Research-grounded additional metrics
    fair_value_low_eur_per_m2: int | None = None   # lower bound of fair value confidence interval
    fair_value_high_eur_per_m2: int | None = None  # upper bound of fair value confidence interval
    price_to_rent_ratio: float | None = None        # total_cost_eur / (rental_estimate_eur * 12)
    time_on_market_weeks: float | None = None       # estimated weeks to sell at listing price
    renovation_upside_pct: float | None = None      # % value gain if brought to euro-renovated standard
    neighborhood_stage: Literal["early_growth", "maturing", "established", "declining"] | None = None


class ComparableListing(BaseModel):
    title: str
    price_eur: int | None = None
    size_m2: float | None = None
    price_per_m2: float | None = None
    rooms: int | None = None
    zone: str | None = None
    url: str | None = None
    source: str = "999md"
    deviation_pct: float | None = None  # vs analyzed listing (positive = comp is more expensive)
    condition: str | None = None
    floor: int | None = None


class ZoneStats(BaseModel):
    zone: str | None = None
    avg_price_per_m2: float | None = None
    median_price_per_m2: float | None = None
    min_price_per_m2: float | None = None
    max_price_per_m2: float | None = None
    count: int = 0


class PriceSnapshot(BaseModel):
    price_eur: int | None = None
    price_per_m2: float | None = None
    scraped_at: datetime


class AnalysisRequest(BaseModel):
    url: str


class FeatureSummary(BaseModel):
    net_adjustment_pct: float = 0.0
    positive_count: int = 0
    negative_count: int = 0
    top_positive: str | None = None
    top_negative: str | None = None


class QualityAssessment(BaseModel):
    quality_score: float = 1.0
    warnings: list[str] = Field(default_factory=list)
    flags: list[str] = Field(default_factory=list)
    recommendation: Literal["proceed", "caution", "avoid"] = "proceed"


class ResearchCitation(BaseModel):
    slug: str
    title: str
    relevance: str
    url: str


class AnalysisCitations(BaseModel):
    method_citations: list[ResearchCitation] = Field(default_factory=list)
    feature_citations: list[ResearchCitation] = Field(default_factory=list)
    market_citations: list[ResearchCitation] = Field(default_factory=list)


class EnvironmentalHazardResponse(BaseModel):
    name: str
    hazard_type: str
    distance_m: float
    impact: str


class EnvironmentalContextResponse(BaseModel):
    hazards: list[EnvironmentalHazardResponse] = Field(default_factory=list)
    noise_level: str = "low"
    air_quality_risk: str = "low"
    adjustment_pct: float = 0.0
    summary: str = ""


class AnalysisMeta(BaseModel):
    """Processing metadata attached to every analysis response."""
    processing_time_ms: int
    scrape_time_ms: int
    analysis_time_ms: int
    model_used: str = "deepseek-chat"
    data_quality_score: float = Field(
        ge=0.0, le=1.0,
        description="0-1 score reflecting how many key fields were extracted",
    )


class ResponseMeta(BaseModel):
    """Metadata for API responses — broader than AnalysisMeta."""
    processing_time_ms: float
    model_used: str = "deepseek-chat"
    data_quality_score: float = Field(
        ge=0.0, le=1.0,
        description="0-1 score reflecting overall data quality",
    )
    comparables_found: int
    timestamp: datetime


class RentalComparable(BaseModel):
    title: str
    monthly_rent_eur: int
    size_m2: float | None = None
    rent_per_m2: float | None = None
    rooms: int | None = None
    zone: str | None = None
    url: str | None = None


class RentalMarketData(BaseModel):
    avg_rent: int
    median_rent: int
    min_rent: int
    max_rent: int
    sample_count: int
    rent_per_m2_avg: float | None = None
    comparables: list[RentalComparable] = Field(default_factory=list)


class ValidatedYield(BaseModel):
    gross_yield_pct: float
    net_yield_pct: float
    market_rent: int
    llm_estimate: int | None
    rent_confidence: str


class RenovationItem(BaseModel):
    category: str
    description: str
    cost_eur: int
    priority: str


class RenovationEstimate(BaseModel):
    scope: str
    items: list[RenovationItem] = Field(default_factory=list)
    total_cost_eur: int
    cost_per_m2: float
    duration_weeks: int
    roi_pct: float | None = None
    post_renovation_value: int | None = None


class AnalysisResponse(BaseModel):
    url: str
    source: Literal["999md", "imobiliare", "unknown"]
    listing: ListingExtraction
    valuation: ValuationResult
    analyzed_at: datetime
    comparables: list[ComparableListing] = Field(default_factory=list)
    zone_stats: ZoneStats | None = None
    price_history: list[PriceSnapshot] = Field(default_factory=list)
    quality: QualityAssessment | None = None
    citations: AnalysisCitations | None = None
    feature_summary: FeatureSummary | None = None
    environmental: EnvironmentalContextResponse | None = None
    rental_market: RentalMarketData | None = None
    validated_yield: ValidatedYield | None = None
    renovation: RenovationEstimate | None = None
    meta: ResponseMeta | None = None


# --- Structured error response ---

class ErrorResponse(BaseModel):
    error: str
    error_code: Literal[
        "invalid_url",
        "scrape_failed",
        "analysis_failed",
        "rate_limited",
        "internal_error",
    ]
    detail: str | None = None
    hint: str | None = None


# --- Stats / Zones endpoint models ---

class VerdictDistribution(BaseModel):
    undervalued: int = 0
    fair: int = 0
    overvalued: int = 0


class AggregateStats(BaseModel):
    total_listings: int
    avg_price_eur: float | None = None
    avg_price_per_m2: float | None = None
    avg_investment_score: float | None = None
    verdict_distribution: VerdictDistribution = Field(default_factory=VerdictDistribution)
    cities: list[str] = Field(default_factory=list)


class ZoneSummary(BaseModel):
    zone: str
    count: int
    avg_price_per_m2: float | None = None
    min_price_per_m2: float | None = None
    max_price_per_m2: float | None = None
    avg_investment_score: float | None = None


# --- Endpoint response models ---

class StatsResponse(BaseModel):
    """Response model for the /stats endpoint."""
    total_listings: int
    by_verdict: dict[str, int]  # e.g. {"undervalued": 5, "fair": 12, "overvalued": 3}
    avg_investment_score: float | None = None
    avg_price_deviation_pct: float | None = None
    markets: list[str] = Field(default_factory=list)  # unique cities
    top_zones: list[dict] = Field(default_factory=list)  # [{zone, avg_price, count}, ...]


class ZoneResponse(BaseModel):
    """Response model for the /zones endpoint."""
    zone: str
    city: str
    avg_price_per_m2: float
    listing_count: int
    avg_investment_score: float | None = None
