"use client";

import { useEffect, useState } from "react";
import {
  Box,
  Flex,
  Heading,
  Text,
  Card,
  Badge,
  Spinner,
  Button,
  Separator,
  Callout,
} from "@radix-ui/themes";
import {
  ArrowLeftIcon,
  MagicWandIcon,
  ExclamationTriangleIcon,
} from "@radix-ui/react-icons";
import { useParams, useRouter } from "next/navigation";
import NextLink from "next/link";
import {
  useGetFamilyMemberQuery,
  useCalmingPlansQuery,
  useGenerateCalmingPlanMutation,
} from "@/app/__generated__/hooks";

const isBogdan = (firstName?: string | null) =>
  (firstName ?? "").trim().toLowerCase() === "bogdan";

function CalmingPlansContent() {
  const params = useParams();
  const router = useRouter();
  const familySlug = params.id as string;
  const isNumeric = /^\d+$/.test(familySlug);
  const familyMemberIdFromRoute = isNumeric ? parseInt(familySlug, 10) : NaN;

  const { data: fmData, loading: fmLoading } = useGetFamilyMemberQuery({
    variables: isNumeric ? { id: familyMemberIdFromRoute } : { slug: familySlug },
  });
  const member = fmData?.familyMember;
  const familyMemberId = member?.id ?? NaN;

  // Bogdan-only — redirect away if someone navigates manually.
  useEffect(() => {
    if (member && !isBogdan(member.firstName)) {
      router.replace(`/family/${member.slug ?? member.id}`);
    }
  }, [member, router]);

  const {
    data: plansData,
    loading: plansLoading,
    refetch,
  } = useCalmingPlansQuery({
    variables: { familyMemberId },
    skip: isNaN(familyMemberId) || !isBogdan(member?.firstName),
    fetchPolicy: "cache-and-network",
  });

  const [generate, { loading: generating }] = useGenerateCalmingPlanMutation();
  const [genError, setGenError] = useState<string | null>(null);

  const plans = plansData?.calmingPlans ?? [];

  const onGenerate = async () => {
    setGenError(null);
    try {
      const res = await generate({
        variables: { familyMemberId, language: "ro" },
      });
      const r = res.data?.generateCalmingPlan;
      if (!r?.success) {
        setGenError(r?.message ?? "Generation failed");
        return;
      }
      await refetch();
      const newId = r.plan?.id;
      if (newId) {
        router.push(
          `/family/${member?.slug ?? member?.id}/calming-plans/${newId}`,
        );
      }
    } catch (e: any) {
      setGenError(e.message ?? String(e));
    }
  };

  if (fmLoading) {
    return (
      <Flex p="6" justify="center">
        <Spinner />
      </Flex>
    );
  }

  if (!member) {
    return (
      <Box p="6">
        <Text color="gray">Family member not found.</Text>
      </Box>
    );
  }

  if (!isBogdan(member.firstName)) {
    // Redirect already in flight via useEffect; render nothing meanwhile.
    return null;
  }

  const memberPath = `/family/${member.slug ?? member.id}`;

  return (
    <Box p={{ initial: "3", md: "5" }} style={{ maxWidth: 980, margin: "0 auto" }}>
      <Flex direction="column" gap="4">
        <Flex align="center" gap="2">
          <NextLink href={memberPath}>
            <Button variant="ghost" size="2">
              <ArrowLeftIcon /> {member.firstName}
            </Button>
          </NextLink>
        </Flex>

        <Flex justify="between" align="end" wrap="wrap" gap="3">
          <Flex direction="column" gap="1">
            <Heading size={{ initial: "5", md: "7" }}>
              Calming plans — {member.firstName}
            </Heading>
            <Text size="2" color="gray">
              Plant-based, non-pharmacologic plans grounded in {member.firstName}
              's issues, characteristics, and allergies. Generated by the deep
              LangGraph (analyze → bundle → synthesize → safety).
            </Text>
          </Flex>
          <Button onClick={onGenerate} disabled={generating} size="3">
            {generating ? <Spinner /> : <MagicWandIcon />}
            Generate new plan
          </Button>
        </Flex>

        {genError && (
          <Callout.Root color="red">
            <Callout.Icon>
              <ExclamationTriangleIcon />
            </Callout.Icon>
            <Callout.Text>{genError}</Callout.Text>
          </Callout.Root>
        )}

        {generating && (
          <Callout.Root color="blue">
            <Callout.Icon>
              <Spinner />
            </Callout.Icon>
            <Callout.Text>
              Running 7-node graph (analyze → search research → 3 parallel
              cluster bundles → synthesize → safety → persist). Typical 2–3
              minutes.
            </Callout.Text>
          </Callout.Root>
        )}

        <Separator size="4" />

        {plansLoading && plans.length === 0 ? (
          <Flex p="6" justify="center">
            <Spinner />
          </Flex>
        ) : plans.length === 0 ? (
          <Card>
            <Flex direction="column" gap="2" p="4">
              <Text>No plans generated yet.</Text>
              <Text size="2" color="gray">
                Click <em>Generate new plan</em> above to run the deep graph
                against {member.firstName}'s current issue + allergy profile.
              </Text>
            </Flex>
          </Card>
        ) : (
          <Flex direction="column" gap="3">
            {plans.map((p) => {
              const dt = new Date(p.generatedAt);
              const headline =
                extractHeadline(p.planMarkdown) || `Plan #${p.id}`;
              return (
                <NextLink
                  key={p.id}
                  href={`${memberPath}/calming-plans/${p.id}`}
                  style={{ textDecoration: "none" }}
                >
                  <Card asChild>
                    <button
                      type="button"
                      style={{
                        cursor: "pointer",
                        textAlign: "left",
                        width: "100%",
                        background: "transparent",
                        border: "none",
                        padding: 0,
                      }}
                    >
                      <Flex direction="column" gap="2" p="4">
                        <Flex justify="between" align="center" wrap="wrap" gap="2">
                          <Heading size="4" style={{ margin: 0 }}>
                            {headline}
                          </Heading>
                          <Flex gap="2" align="center">
                            <Badge color="indigo">{p.language}</Badge>
                            <Text size="1" color="gray">
                              {dt.toLocaleString()}
                            </Text>
                          </Flex>
                        </Flex>
                        <Text size="2" color="gray">
                          {previewLine(p.planMarkdown)}
                        </Text>
                      </Flex>
                    </button>
                  </Card>
                </NextLink>
              );
            })}
          </Flex>
        )}
      </Flex>
    </Box>
  );
}

function extractHeadline(md: string): string | null {
  const m = md.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : null;
}

function previewLine(md: string): string {
  // First non-heading, non-blank line, trimmed to ~200 chars.
  const lines = md.split("\n");
  for (const line of lines) {
    const t = line.trim();
    if (!t || t.startsWith("#") || t.startsWith("---")) continue;
    return t.length > 200 ? t.slice(0, 200) + "…" : t;
  }
  return "";
}

export default function CalmingPlansPage() {
  return <CalmingPlansContent />;
}
