/**
 * Generate worker type constants from the unified schema contracts.
 *
 * Reads Zod enums and the skill taxonomy from src/schema/contracts/
 * and writes generated files for each non-TypeScript runtime:
 *
 *   - workers/process-jobs/src/_generated_schema.py  (Python)
 *   - workers/ashby-crawler/src/generated_schema.rs  (Rust)
 *   - src/schema/__generated__/contracts.json        (JSON Schema)
 *
 * Usage:
 *   pnpm schema:generate
 *   tsx scripts/generate-worker-types.ts
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

// Import contracts (relative for tsx execution)
import {
  JobStatus,
  ClassificationConfidence,
  CompanyCategory,
  SourceType,
  ExtractMethod,
  ApplicationStatus,
  DeepPlannerStatus,
  SkillLevel,
  JOB_STATUS_PYTHON_MAP,
} from "../src/schema/contracts/enums";
import { SKILL_TAXONOMY } from "../src/schema/contracts/skill-taxonomy";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ensureDir(filePath: string) {
  mkdirSync(dirname(filePath), { recursive: true });
}

function getEnumValues(zodEnum: { options: readonly string[] }): readonly string[] {
  return zodEnum.options;
}

const HEADER_PY = `# AUTO-GENERATED by scripts/generate-worker-types.ts
# Do NOT edit manually. Run \`pnpm schema:generate\` to regenerate.
#
# Source of truth: src/schema/contracts/
`;

const HEADER_RS = `// AUTO-GENERATED by scripts/generate-worker-types.ts
// Do NOT edit manually. Run \`pnpm schema:generate\` to regenerate.
//
// Source of truth: src/schema/contracts/
`;

const HEADER_JSON = {
  $comment:
    "AUTO-GENERATED by scripts/generate-worker-types.ts — do NOT edit manually.",
};

// ---------------------------------------------------------------------------
// Python generation
// ---------------------------------------------------------------------------

function generatePython(): string {
  const lines: string[] = [HEADER_PY];

  // Enums as string enums
  function pyEnum(name: string, values: readonly string[]) {
    lines.push(`class ${name}(str, Enum):`);
    for (const v of values) {
      const pyKey = v.toUpperCase().replace(/-/g, "_");
      lines.push(`    ${pyKey} = "${v}"`);
    }
    lines.push("");
  }

  lines.push("from enum import Enum");
  lines.push("from typing import FrozenSet, Dict");
  lines.push("");
  lines.push("");

  // JobStatus: enum VALUES use the DB-native hyphenated format so that
  // `JobStatus.EU_REMOTE.value` returns "eu-remote" (what D1 stores).
  // Enum KEYS use UPPER_SNAKE for Pythonic access (JobStatus.EU_REMOTE).
  lines.push("class JobStatus(str, Enum):");
  lines.push("    \"\"\"Pipeline status — .value returns the D1-native hyphenated form.\"\"\"");
  for (const [canonical, dbValue] of Object.entries(JOB_STATUS_PYTHON_MAP)) {
    const pyKey = canonical.toUpperCase();
    lines.push(`    ${pyKey} = "${dbValue}"`);
  }
  lines.push("");

  // Also emit the canonical ↔ DB mapping dicts
  lines.push("# Canonical (underscore) → DB-native (hyphenated) mapping");
  lines.push("JOB_STATUS_PYTHON_MAP: Dict[str, str] = {");
  for (const [k, v] of Object.entries(JOB_STATUS_PYTHON_MAP)) {
    lines.push(`    "${k}": "${v}",`);
  }
  lines.push("}");
  lines.push("");
  lines.push("# DB-native (hyphenated) → canonical (underscore) mapping");
  lines.push("JOB_STATUS_CANONICAL_MAP: Dict[str, str] = {");
  for (const [k, v] of Object.entries(JOB_STATUS_PYTHON_MAP)) {
    lines.push(`    "${v}": "${k}",`);
  }
  lines.push("}");
  lines.push("");
  lines.push("");

  pyEnum("ClassificationConfidence", getEnumValues(ClassificationConfidence));
  pyEnum("CompanyCategory", getEnumValues(CompanyCategory));
  pyEnum("SourceType", getEnumValues(SourceType));
  pyEnum("ExtractMethod", getEnumValues(ExtractMethod));
  pyEnum("ApplicationStatus", getEnumValues(ApplicationStatus));
  pyEnum("DeepPlannerStatus", getEnumValues(DeepPlannerStatus));
  pyEnum("SkillLevel", getEnumValues(SkillLevel));

  // Skill taxonomy
  lines.push("# Canonical skill taxonomy");
  lines.push("SKILL_TAGS: FrozenSet[str] = frozenset({");
  const tags = Object.keys(SKILL_TAXONOMY);
  for (let i = 0; i < tags.length; i += 6) {
    const chunk = tags.slice(i, i + 6).map((t) => `"${t}"`);
    lines.push(`    ${chunk.join(", ")},`);
  }
  lines.push("})");
  lines.push("");

  lines.push("SKILL_LABELS: Dict[str, str] = {");
  for (const [tag, label] of Object.entries(SKILL_TAXONOMY)) {
    lines.push(`    "${tag}": "${label}",`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Rust generation
// ---------------------------------------------------------------------------

function generateRust(): string {
  const lines: string[] = [HEADER_RS];
  lines.push("");

  function rsEnum(name: string, values: readonly string[]) {
    lines.push(`/// Auto-generated from src/schema/contracts/enums.ts`);
    lines.push(`pub const ${name.toUpperCase()}_VALUES: &[&str] = &[`);
    for (const v of values) {
      lines.push(`    "${v}",`);
    }
    lines.push("];");
    lines.push("");
  }

  rsEnum("JobStatus", getEnumValues(JobStatus));
  rsEnum("ClassificationConfidence", getEnumValues(ClassificationConfidence));
  rsEnum("CompanyCategory", getEnumValues(CompanyCategory));
  rsEnum("SourceType", getEnumValues(SourceType));
  rsEnum("ExtractMethod", getEnumValues(ExtractMethod));

  // Skill tags as a const array
  const tags = Object.keys(SKILL_TAXONOMY);
  lines.push(`/// Canonical skill taxonomy — ${tags.length} tags.`);
  lines.push(`pub const SKILL_TAGS: &[&str] = &[`);
  for (const tag of tags) {
    lines.push(`    "${tag}",`);
  }
  lines.push("];");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// JSON Schema generation (for documentation / non-TS validation)
// ---------------------------------------------------------------------------

function generateJsonSchema(): object {
  const enums: Record<string, readonly string[]> = {
    JobStatus: getEnumValues(JobStatus),
    ClassificationConfidence: getEnumValues(ClassificationConfidence),
    CompanyCategory: getEnumValues(CompanyCategory),
    SourceType: getEnumValues(SourceType),
    ExtractMethod: getEnumValues(ExtractMethod),
    ApplicationStatus: getEnumValues(ApplicationStatus),
    DeepPlannerStatus: getEnumValues(DeepPlannerStatus),
    SkillLevel: getEnumValues(SkillLevel),
  };

  return {
    ...HEADER_JSON,
    $schema: "http://json-schema.org/draft-07/schema#",
    title: "lead-gen shared contracts",
    definitions: {
      ...Object.fromEntries(
        Object.entries(enums).map(([name, values]) => [
          name,
          { type: "string", enum: [...values] },
        ]),
      ),
      SkillTaxonomy: {
        type: "object",
        description: `${Object.keys(SKILL_TAXONOMY).length} canonical skill tags`,
        properties: Object.fromEntries(
          Object.entries(SKILL_TAXONOMY).map(([tag, label]) => [
            tag,
            { type: "string", const: label },
          ]),
        ),
      },
    },
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const ROOT = resolve(import.meta.dirname!, "..");

// Python
const pyPath = resolve(ROOT, "workers/process-jobs/src/_generated_schema.py");
ensureDir(pyPath);
writeFileSync(pyPath, generatePython(), "utf-8");
console.log(`  ✓ Python: ${pyPath}`);

// Rust
const rsPath = resolve(ROOT, "workers/ashby-crawler/src/generated_schema.rs");
ensureDir(rsPath);
writeFileSync(rsPath, generateRust(), "utf-8");
console.log(`  ✓ Rust:   ${rsPath}`);

// JSON Schema
const jsonPath = resolve(ROOT, "src/schema/__generated__/contracts.json");
ensureDir(jsonPath);
writeFileSync(jsonPath, JSON.stringify(generateJsonSchema(), null, 2) + "\n", "utf-8");
console.log(`  ✓ JSON:   ${jsonPath}`);

console.log("\nDone. Run `pnpm codegen` to regenerate GraphQL types.");
