#!/usr/bin/env npx tsx
/**
 * Import research-paper authors from the 2025–2026 sales/lead-gen corpus
 * (generated by `cargo run -p research --bin leadgen-papers`) into the
 * `contacts` table, one contact per unique author. Each contact's `notes`
 * field contains formatted metadata for every paper that author co-wrote.
 *
 * Usage:
 *   pnpm tsx scripts/import-paper-authors.ts            # real insert
 *   pnpm tsx scripts/import-paper-authors.ts --dry-run  # no DB writes
 *   pnpm tsx scripts/import-paper-authors.ts --limit 50 # only first N authors
 *
 * Idempotent: conflicts on the unique `slug` index are ignored, so re-running
 * the script will not create duplicates (but will not refresh notes either —
 * pass --update to also UPDATE notes on existing rows).
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { readFileSync } from "fs";
import { resolve } from "path";
import { neon } from "@neondatabase/serverless";
import { createHash } from "crypto";

// ── CLI flags ────────────────────────────────────────────────────────────

const DRY_RUN = process.argv.includes("--dry-run");
const UPDATE = process.argv.includes("--update");
const FORCE = process.argv.includes("--force");
const FORCE_BULK = process.argv.includes("--force-bulk");
const LIMIT = (() => {
  const i = process.argv.indexOf("--limit");
  return i !== -1 ? parseInt(process.argv[i + 1], 10) : Infinity;
})();

// ── Entry guards ─────────────────────────────────────────────────────────
// Defense-in-depth so a stray `pnpm tsx scripts/import-paper-authors.ts`
// can't recreate the 1,404 dead-end contacts from 2026-04-22 again.
//
// Verified: with no flags / env vars set, this guard fires, prints the
// stderr line below, and exits 1 before any DB connection is opened.
const PAPER_IMPORT_ENABLED =
  process.env.LEADGEN_ALLOW_PAPER_IMPORT === "1" || FORCE;

// ── Types matching papers.json ───────────────────────────────────────────

interface Paper {
  title: string;
  abstract_text: string | null;
  authors: string[];
  affiliations: string[] | null;
  year: number | null;
  doi: string | null;
  citation_count: number | null;
  url: string | null;
  pdf_url: string | null;
  source: string;
  source_id: string;
  venue: string | null;
  published_date: string | null;
}

interface PaperEntry {
  paper: Paper;
  slug: string;
  tier: "core" | "broad";
  query: string;
  tags: string[];
}

// ── Name parsing ─────────────────────────────────────────────────────────

/** Normalize a full name to a dedup key: lowercase, strip punctuation, collapse whitespace. */
function normalizeName(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "") // strip combining diacritics
    .replace(/[^a-z\s-]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .join(" ");
}

/** Split "Jane Q. Public" → { first: "Jane Q.", last: "Public" }. */
function splitName(full: string): { first: string; last: string } {
  const cleaned = full.trim().replace(/\s+/g, " ");
  if (!cleaned) return { first: "Unknown", last: "Author" };
  const parts = cleaned.split(" ");
  if (parts.length === 1) return { first: parts[0], last: "" };
  const last = parts.pop()!;
  const first = parts.join(" ");
  return { first, last };
}

/** Generate a unique, URL-safe slug per author. */
function authorSlug(fullName: string): string {
  const base = fullName
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
  // 6-char hash collision breaker (same name, different person)
  const hash = createHash("sha1")
    .update(fullName)
    .digest("hex")
    .slice(0, 6);
  return `paper-author-${base || "anon"}-${hash}`;
}

/** Normalize a DOI by stripping any `https://doi.org/` prefix. */
function normalizeDoi(raw: string | null): string | null {
  if (!raw) return null;
  const s = raw.trim();
  const lower = s.toLowerCase();
  for (const prefix of ["https://doi.org/", "http://doi.org/", "doi.org/", "doi:"]) {
    if (lower.startsWith(prefix)) return s.slice(prefix.length).trim();
  }
  return s;
}

// ── Notes rendering ──────────────────────────────────────────────────────

function truncate(s: string, max = 600): string {
  if (s.length <= max) return s;
  return s.slice(0, max).trimEnd() + "…";
}

function renderNotes(author: string, entries: PaperEntry[]): string {
  const lines: string[] = [];
  lines.push(
    `Research-paper author, surfaced from the 2025–2026 sales & lead-gen corpus (800 papers, 5 academic sources).`,
  );
  lines.push("");
  lines.push(`Papers co-authored: **${entries.length}**.`);
  lines.push("");

  // Sort entries by citation count desc then year desc
  const sorted = [...entries].sort((a, b) => {
    const ca = a.paper.citation_count ?? 0;
    const cb = b.paper.citation_count ?? 0;
    if (ca !== cb) return cb - ca;
    return (b.paper.year ?? 0) - (a.paper.year ?? 0);
  });

  for (let i = 0; i < sorted.length; i++) {
    const e = sorted[i];
    const p = e.paper;
    const doi = normalizeDoi(p.doi);
    const doiLink = doi ? `https://doi.org/${doi}` : null;
    const year = p.year ?? "—";
    const venue = p.venue?.trim() || "";
    const cites = p.citation_count ?? 0;

    lines.push(`### ${i + 1}. ${p.title.trim()}`);
    lines.push("");
    const meta: string[] = [];
    meta.push(`Year: **${year}**`);
    if (venue) meta.push(`Venue: ${venue}`);
    meta.push(`Citations: ${cites}`);
    meta.push(`Source: ${p.source}`);
    meta.push(`Tier: ${e.tier}`);
    lines.push(`- ${meta.join(" · ")}`);
    if (doiLink) lines.push(`- DOI: [${doi}](${doiLink})`);
    if (p.url && p.url !== doiLink) lines.push(`- URL: ${p.url}`);
    if (p.pdf_url) lines.push(`- PDF: ${p.pdf_url}`);
    if (e.tags?.length) lines.push(`- Tags: \`${e.tags.join("`, `")}\``);
    lines.push(`- Seed query: *"${e.query}"*`);

    const coauthors = p.authors.filter((a) => a !== author);
    if (coauthors.length) {
      const head = coauthors.slice(0, 8).join(", ");
      const extra = coauthors.length > 8 ? ` (+${coauthors.length - 8} more)` : "";
      lines.push(`- Co-authors: ${head}${extra}`);
    }
    if (p.affiliations?.length) {
      const affs = p.affiliations.slice(0, 5).join(", ");
      const extra = p.affiliations.length > 5 ? ` (+${p.affiliations.length - 5} more)` : "";
      lines.push(`- Affiliations: ${affs}${extra}`);
    }

    if (p.abstract_text) {
      lines.push("");
      lines.push(`> ${truncate(p.abstract_text).replace(/\n+/g, " ")}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `_Imported by \`scripts/import-paper-authors.ts\` from \`apps/lead-gen/docs/papers/2025-2026-sales-leadgen/papers.json\`._`,
  );
  return lines.join("\n");
}

// ── Main ─────────────────────────────────────────────────────────────────

async function main() {
  // Entry guard — refuse to run unless explicitly opted in.
  if (!PAPER_IMPORT_ENABLED && !DRY_RUN) {
    process.stderr.write(
      "Refusing to run: paper-author import is gated. Set LEADGEN_ALLOW_PAPER_IMPORT=1 or pass --force.\n",
    );
    process.exit(1);
  }

  const jsonPath = resolve(
    "docs/papers/2025-2026-sales-leadgen/papers.json",
  );
  const raw = readFileSync(jsonPath, "utf8");
  const entries = JSON.parse(raw) as PaperEntry[];
  console.log(`Loaded ${entries.length} paper entries from ${jsonPath}`);

  // Group by normalized author name, preserving the canonical spelling
  // of the first occurrence for display / slug derivation.
  const byAuthor = new Map<string, { canonical: string; entries: PaperEntry[] }>();
  for (const e of entries) {
    for (const name of e.paper.authors ?? []) {
      const trimmed = name.trim();
      if (!trimmed) continue;
      const key = normalizeName(trimmed);
      if (!key) continue;
      const slot = byAuthor.get(key);
      if (slot) {
        slot.entries.push(e);
      } else {
        byAuthor.set(key, { canonical: trimmed, entries: [e] });
      }
    }
  }

  const authorsAll = Array.from(byAuthor.values());
  console.log(`Unique authors: ${authorsAll.length}`);

  // ── Per-author affiliation pre-filter ─────────────────────────────────
  // Drop authors whose source papers carry zero affiliation signal AND no
  // contact channel (email / linkedin / github). Without either, the
  // downstream enrichment graph has nothing to resolve and the contact
  // becomes a dead-end (see 2026-04-22 cohort, 1,404 unreachable rows).
  const beforeFilter = authorsAll.length;
  const authors: typeof authorsAll = [];
  for (const a of authorsAll) {
    const affUnion = new Set<string>();
    let hasChannel = false;
    for (const e of a.entries) {
      for (const aff of e.paper.affiliations ?? []) {
        const t = aff.trim();
        if (t) affUnion.add(t);
      }
      // The corpus type doesn't model contact-channel fields, but inspect
      // the raw paper object defensively in case a future ingestor adds them.
      const rawPaper = e.paper as unknown as Record<string, unknown>;
      const email = rawPaper.email;
      const linkedin = rawPaper.linkedin;
      const github = rawPaper.github_username;
      if (
        (typeof email === "string" && email.trim()) ||
        (typeof linkedin === "string" && linkedin.trim()) ||
        (typeof github === "string" && github.trim())
      ) {
        hasChannel = true;
      }
    }
    if (affUnion.size === 0 && !hasChannel) {
      const { first, last } = splitName(a.canonical);
      console.log(`[skip] ${first} ${last} — no affiliation, no contact channel`);
      continue;
    }
    authors.push(a);
  }
  const dropped = beforeFilter - authors.length;
  console.log(
    `Filtered ${beforeFilter} → ${authors.length} (${dropped} dropped: no signal)`,
  );

  // Stable-sort by paper count desc (most prolific first)
  authors.sort((a, b) => b.entries.length - a.entries.length);

  // Single-tag mode: every paper-author contact carries exactly one tag
  // ("papers"). Theme info still lives in the `notes` field per paper.
  const rows = authors.slice(0, LIMIT).map((a) => {
    const { first, last } = splitName(a.canonical);
    const slug = authorSlug(a.canonical);
    const notes = renderNotes(a.canonical, a.entries);
    const tags = JSON.stringify(["papers"]);
    return {
      slug,
      first,
      last,
      notes,
      tags,
      paperCount: a.entries.length,
      themeCount: 0,
    };
  });

  console.log(`Prepared ${rows.length} contact rows`);
  console.log(`  → top author has ${rows[0]?.paperCount ?? 0} papers`);
  console.log(`  → median notes length: ${medianNotesLen(rows)} chars`);
  console.log(`  → total notes payload: ${totalNotesLen(rows).toLocaleString()} chars`);
  console.log(`  → tag: ["papers"] (single tag for all)`);

  // Count cap — refuse to insert > 100 rows in one run unless --force-bulk.
  // Skip the cap on dry-runs since they don't write anything.
  if (!DRY_RUN && rows.length > 100 && !FORCE_BULK) {
    process.stderr.write(
      `Refusing to insert ${rows.length} contacts in one run (cap=100). Pass --force-bulk to override.\n`,
    );
    process.exit(1);
  }

  if (DRY_RUN) {
    console.log("\n--dry-run — sample row:\n");
    const sample = rows[0];
    if (sample) {
      console.log(`slug:  ${sample.slug}`);
      console.log(`first: ${sample.first}`);
      console.log(`last:  ${sample.last}`);
      console.log(`tags:  ${sample.tags}`);
      console.log(`notes preview:\n${sample.notes.slice(0, 600)}\n...`);
    }
    return;
  }

  const url = process.env.NEON_DATABASE_URL;
  if (!url) {
    throw new Error("NEON_DATABASE_URL not set — check .env.local");
  }
  const sql = neon(url);

  // Idempotent DDL — adds the column if it doesn't exist yet.
  console.log("\nEnsuring contacts.notes column exists…");
  await sql`ALTER TABLE contacts ADD COLUMN IF NOT EXISTS notes text`;

  // Batch-insert via UNNEST to keep the request payload bounded
  const BATCH = 100;
  let inserted = 0;
  let skipped = 0;
  let updated = 0;
  const insertedIds: number[] = [];

  for (let i = 0; i < rows.length; i += BATCH) {
    const chunk = rows.slice(i, i + BATCH);
    const slugs = chunk.map((r) => r.slug);
    const firsts = chunk.map((r) => r.first);
    const lasts = chunk.map((r) => r.last);
    const notes = chunk.map((r) => r.notes);
    const tags = chunk.map((r) => r.tags);

    // ON CONFLICT (slug) — either skip or update depending on flag.
    const result = UPDATE
      ? await sql`
          INSERT INTO contacts (slug, first_name, last_name, notes, tags)
          SELECT * FROM UNNEST(
            ${slugs}::text[],
            ${firsts}::text[],
            ${lasts}::text[],
            ${notes}::text[],
            ${tags}::text[]
          )
          ON CONFLICT (slug) DO UPDATE SET
            notes = EXCLUDED.notes,
            tags = EXCLUDED.tags,
            updated_at = now()::text
          RETURNING (xmax = 0) AS newly_inserted
        `
      : await sql`
          INSERT INTO contacts (slug, first_name, last_name, notes, tags)
          SELECT * FROM UNNEST(
            ${slugs}::text[],
            ${firsts}::text[],
            ${lasts}::text[],
            ${notes}::text[],
            ${tags}::text[]
          )
          ON CONFLICT (slug) DO NOTHING
          RETURNING id
        `;

    if (UPDATE) {
      const rs = result as Array<{ newly_inserted: boolean }>;
      const ins = rs.filter((r) => r.newly_inserted).length;
      const upd = rs.length - ins;
      inserted += ins;
      updated += upd;
      skipped += chunk.length - rs.length;
    } else {
      const rs = result as Array<{ id: number }>;
      inserted += rs.length;
      skipped += chunk.length - rs.length;
      for (const r of rs) {
        if (typeof r.id === "number") insertedIds.push(r.id);
      }
    }
    console.log(
      `  batch ${Math.floor(i / BATCH) + 1}/${Math.ceil(rows.length / BATCH)} — ins+upd so far: ${inserted}+${updated}, skipped: ${skipped}`,
    );
  }

  console.log(
    `\nDone. inserted=${inserted} updated=${updated} skipped=${skipped} total_prepared=${rows.length}`,
  );

  // Quick sanity check — match on the exact single-tag shape to avoid
  // confusion with legacy "paper-author" / "sales-leadgen-papers" strings.
  const [{ count: total }] = (await sql`
    SELECT COUNT(*)::int AS count FROM contacts
    WHERE tags::text LIKE '%"papers"%'
  `) as Array<{ count: number }>;
  console.log(`Contacts tagged "papers" in DB: ${total}`);

  // ── Auto-trigger enrichment (LangGraph) ─────────────────────────────────
  // Hand off to the Python `contact_enrich_paper_authors_batch` graph, which
  // drains the unenriched papers-tagged cohort server-side in a single HTTP
  // call — Teams A/B/C (classify_affiliation, classify_buyer_fit_node,
  // auto_flag_unreachable_node) run per contact and dead-ends get auto-flagged
  // for the 30-day deletion sweep. One round-trip, not 1,404.
  if (insertedIds.length === 0) {
    console.log("\nNo new contacts inserted; skipping enrichment trigger.");
    return;
  }
  await triggerBatchEnrichment(insertedIds.length);
}

// ── LangGraph trigger ──────────────────────────────────────────────────────
// Inline mini-client mirroring src/lib/langgraph-client.ts:runGraph (which
// isn't exported). We only need POST /runs/wait with optional bearer auth.
async function triggerBatchEnrichment(insertedCount: number): Promise<void> {
  const lgUrl = process.env.LANGGRAPH_URL || "http://127.0.0.1:8002";
  const token = process.env.LANGGRAPH_AUTH_TOKEN;
  const assistantId = "contact_enrich_paper_authors_batch";

  console.log(
    `\nTriggering ${assistantId} on ${lgUrl} (cohort: ${insertedCount} new + any prior unenriched)…`,
  );

  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (token) headers.Authorization = `Bearer ${token}`;

  const result = await Promise.allSettled([
    fetch(`${lgUrl}/runs/wait`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        assistant_id: assistantId,
        // The batch graph auto-picks unenriched papers-tagged contacts;
        // count/deadline_seconds are optional knobs (server defaults: drain
        // until empty / 8-min wall-clock). Pass an explicit cap aligned with
        // what we just inserted so the run terminates predictably.
        input: { count: insertedCount, deadline_seconds: 8 * 60 },
      }),
      // Container budget is ~10 min; allow 12 for HTTP framing.
      signal: AbortSignal.timeout(12 * 60_000),
    }),
  ]);

  const r = result[0];
  if (r.status === "rejected") {
    console.error(`Enrichment trigger failed: ${String(r.reason)}`);
    console.error("New contacts are inserted but unenriched — re-run later.");
    return;
  }
  const res = r.value;
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    console.error(`Enrichment HTTP ${res.status}: ${text.slice(0, 500)}`);
    console.error("New contacts are inserted but unenriched — re-run later.");
    return;
  }
  const body = (await res.json().catch(() => ({}))) as {
    enriched?: unknown[];
    resolve_counts?: Record<string, number>;
    stop_reason?: string;
  };
  const enriched = Array.isArray(body.enriched) ? body.enriched.length : 0;
  console.log(
    `Enriched: ${enriched} / ${insertedCount} (stop_reason=${body.stop_reason ?? "?"})`,
  );
  if (body.resolve_counts) {
    console.log(`  resolve_counts: ${JSON.stringify(body.resolve_counts)}`);
  }
}

function medianNotesLen(rows: Array<{ notes: string }>): number {
  if (!rows.length) return 0;
  const lens = rows.map((r) => r.notes.length).sort((a, b) => a - b);
  return lens[Math.floor(lens.length / 2)];
}
function totalNotesLen(rows: Array<{ notes: string }>): number {
  return rows.reduce((s, r) => s + r.notes.length, 0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
