"""Quote quality evaluation using deepeval's GEval metric.

Tests five dimensions of quote quality from LangGraph research output:
1. Attribution — each quote names its source (podcast, interview, article)
2. URLs — each quote includes a source URL
3. Authenticity — quotes sound like natural speech, not LLM-generated text
4. Substance — quotes contain meaningful insights, not platitudes
5. Distinctness — quotes cover different topics, not repetitive

Usage:
    pytest tests/test_metric_geval_quotes.py -v
    deepeval test run tests/test_metric_geval_quotes.py
"""

import json
import os

import pytest
from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from helpers import get_eval_model

pytestmark = pytest.mark.deepeval
skip_no_key = pytest.mark.skipif(
    not os.getenv("DEEPSEEK_API_KEY"), reason="No DEEPSEEK_API_KEY"
)

THRESHOLD = 0.5
MODEL = "deepseek/deepseek-chat"


# ── Test 1: Quotes have named attribution ────────────────────────────────


@skip_no_key
def test_quotes_have_attribution(sample_quotes):
    """Each quote must have a named source such as a podcast, interview, or article."""
    test_case = LLMTestCase(
        input="Collect notable quotes with source attribution for Harrison Chase",
        actual_output=json.dumps(sample_quotes),
    )
    metric = GEval(
        name="Quote Attribution",
        criteria=(
            "Every quote in the output must include a 'source' field that names "
            "a specific podcast, interview, article, or talk where the quote "
            "originated. Generic labels like 'unknown' or empty strings are not acceptable."
        ),
        evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT],
        threshold=THRESHOLD,
        model=get_eval_model(),
    )
    metric.measure(test_case)
    assert metric.score >= THRESHOLD, (
        f"Quote attribution score {metric.score:.2f} < {THRESHOLD}. "
        f"Reason: {metric.reason}"
    )


# ── Test 2: Quotes have source URLs ─────────────────────────────────────


@skip_no_key
def test_quotes_have_urls(sample_quotes):
    """Each quote must include a URL pointing to the original source."""
    test_case = LLMTestCase(
        input="Collect notable quotes with source URLs for Harrison Chase",
        actual_output=json.dumps(sample_quotes),
    )
    metric = GEval(
        name="Quote URLs",
        criteria=(
            "Every quote in the output must include a 'url' field containing "
            "a valid-looking URL (starting with http:// or https://) that points "
            "to the source material. Missing or empty URLs are not acceptable."
        ),
        evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT],
        threshold=THRESHOLD,
        model=get_eval_model(),
    )
    metric.measure(test_case)
    assert metric.score >= THRESHOLD, (
        f"Quote URL score {metric.score:.2f} < {THRESHOLD}. "
        f"Reason: {metric.reason}"
    )


# ── Test 3: Quotes sound authentic ──────────────────────────────────────


@skip_no_key
def test_quotes_sound_authentic(sample_quotes):
    """Quotes must sound like natural human speech, not AI-generated boilerplate."""
    test_case = LLMTestCase(
        input="Collect authentic verbatim quotes from Harrison Chase",
        actual_output=json.dumps(sample_quotes),
    )
    metric = GEval(
        name="Quote Authenticity",
        criteria=(
            "Each quote should read like natural spoken language from a real person. "
            "Look for conversational tone, specific details, personal perspective, "
            "and the kind of imperfect phrasing typical of interviews or talks. "
            "Penalize quotes that sound overly polished, formulaic, or like they "
            "were generated by a language model."
        ),
        evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT],
        threshold=THRESHOLD,
        model=get_eval_model(),
    )
    metric.measure(test_case)
    assert metric.score >= THRESHOLD, (
        f"Quote authenticity score {metric.score:.2f} < {THRESHOLD}. "
        f"Reason: {metric.reason}"
    )


# ── Test 4: Quotes are substantive ──────────────────────────────────────


@skip_no_key
def test_quotes_are_substantive(sample_quotes):
    """Quotes must contain meaningful insights, not generic platitudes."""
    test_case = LLMTestCase(
        input="Collect insightful, substantive quotes from Harrison Chase",
        actual_output=json.dumps(sample_quotes),
    )
    metric = GEval(
        name="Quote Substance",
        criteria=(
            "Each quote must convey a specific, meaningful insight about technology, "
            "strategy, or the person's domain of expertise. The quote should teach "
            "the reader something concrete or reveal the speaker's thinking. "
            "Penalize vague motivational statements, empty platitudes, or generic "
            "remarks that could apply to anyone (e.g., 'We want to make the world better')."
        ),
        evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT],
        threshold=THRESHOLD,
        model=get_eval_model(),
    )
    metric.measure(test_case)
    assert metric.score >= THRESHOLD, (
        f"Quote substance score {metric.score:.2f} < {THRESHOLD}. "
        f"Reason: {metric.reason}"
    )


# ── Test 5: Quotes are distinct ──────────────────────────────────────────


@skip_no_key
def test_quotes_are_distinct(sample_quotes):
    """Quotes must cover different topics and not be repetitive."""
    test_case = LLMTestCase(
        input="Collect diverse quotes covering different topics from Harrison Chase",
        actual_output=json.dumps(sample_quotes),
    )
    metric = GEval(
        name="Quote Distinctness",
        criteria=(
            "The set of quotes should cover distinct topics or perspectives. "
            "Each quote should add new information or address a different theme "
            "compared to the others. Penalize quotes that repeat the same idea "
            "in slightly different words, cover the same narrow topic, or are "
            "near-paraphrases of each other."
        ),
        evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT],
        threshold=THRESHOLD,
        model=get_eval_model(),
    )
    metric.measure(test_case)
    assert metric.score >= THRESHOLD, (
        f"Quote distinctness score {metric.score:.2f} < {THRESHOLD}. "
        f"Reason: {metric.reason}"
    )
