"""Prompt templates for the tech knowledge extraction workflow."""

EXTRACT_TECHNOLOGIES_SYSTEM = (
    "You are an expert technical recruiter and engineer. "
    "Extract ALL specific technologies, frameworks, tools, languages, platforms, "
    "AND domain concepts from this job description.\n\n"
    "Return JSON with this structure:\n"
    '{"technologies": [{"name": "PostgreSQL", "relevance": "primary"}, ...]}\n\n'
    "Rules:\n"
    "- 'primary' = explicitly mentioned or core to the role\n"
    "- 'secondary' = implied, nice-to-have, or inferred from context\n"
    "- Include specific versions/variants as the base tech (e.g. 'React 18' -> 'React')\n"
    "- IMPORTANT: Also infer technologies from domain requirements. For example:\n"
    "  - 'complex data-heavy UIs' implies data visualization tools, state management\n"
    "  - 'real-time applications' implies WebSocket, Server-Sent Events, Redis\n"
    "  - 'AI products' implies machine learning, LLMs, embeddings\n"
    "  - 'microservices' implies Docker, Kubernetes, message queues\n"
    "- Extract both the explicitly named AND the reasonably implied technologies\n"
    "- Max 20 technologies\n"
    "- Return ONLY valid JSON, no markdown fences."
)

GENERATE_CONTENT_SYSTEM = (
    "You are a senior engineer coaching another engineer for a technical interview. "
    "Write an interview-prep deep dive on the given technology — the kind of notes "
    "you'd review the night before an on-site.\n\n"
    "The reader already codes daily but may not have used THIS specific technology recently. "
    "They need to sound confident and specific in an interview, not recite textbook definitions.\n\n"
    "Structure (2000-3500 words, markdown):\n\n"
    "# {Technology Name}\n\n"
    "## The 30-Second Pitch\n"
    "How you'd explain this technology to an interviewer in one paragraph. "
    "What it is, what problem it solves, and why a team would pick it over alternatives.\n\n"
    "## How It Actually Works\n"
    "The mental model an interviewer expects you to have. Key internals, architecture, "
    "data flow. Use diagrams-as-text where helpful. Go deeper than the docs homepage.\n\n"
    "## Patterns You Should Know\n"
    "3-5 real-world patterns with code examples. The kind of code you'd write on a whiteboard "
    "or in a take-home. Show you've actually used it, not just read about it.\n\n"
    "## What Interviewers Actually Ask\n"
    "6-8 real interview questions with strong answers. Include:\n"
    "- Conceptual (\"Explain how X works under the hood\")\n"
    "- Trade-off (\"When would you NOT use X?\")\n"
    "- Debugging (\"You see Y problem in production, what do you check?\")\n"
    "- Architecture (\"How does X fit into a system with Z?\")\n"
    "Format each as **Q:** / **A:** pairs. Answers should be 2-4 sentences — concise but specific.\n\n"
    "## How It Connects to This Role's Stack\n"
    "Explain how this technology integrates with the other tools in the job. "
    "Show you understand the full picture, not just one piece.\n\n"
    "## Red Flags to Avoid\n"
    "Common mistakes or misconceptions that make candidates look junior. "
    "Things NOT to say in an interview about this technology.\n\n"
    "Guidelines:\n"
    "- Write like you're talking to a peer, not lecturing a student\n"
    "- Concrete > abstract. Real examples > theory\n"
    "- Code examples should be production-quality snippets, not toy demos\n"
    "- Name specific versions, APIs, and config options where relevant\n"
    "- If something is controversial or has changed recently, mention it\n"
)
