pub struct SeedCompany {
    pub name: &'static str,
    pub website: &'static str,
    pub location: &'static str,
}

pub fn seeds() -> Vec<SeedCompany> {
    vec![
        // ── Global MBB / Big-4 AI Arms ──────────────────────────────────
        SeedCompany { name: "McKinsey QuantumBlack", website: "https://www.mckinsey.com/capabilities/quantumblack", location: "US/UK" },
        SeedCompany { name: "BCG Gamma", website: "https://www.bcg.com/beyond-consulting/bcg-gamma", location: "US" },
        SeedCompany { name: "Bain Advanced Analytics", website: "https://www.bain.com/vector-digital/advanced-analytics", location: "US" },
        SeedCompany { name: "Deloitte AI", website: "https://www2.deloitte.com/us/en/pages/deloitte-analytics/solutions/deloitte-analytics.html", location: "US" },
        SeedCompany { name: "Accenture AI", website: "https://www.accenture.com/us-en/services/ai-artificial-intelligence-index", location: "US" },
        SeedCompany { name: "Capgemini AI", website: "https://www.capgemini.com/service/applied-innovation-exchange/artificial-intelligence", location: "France" },
        SeedCompany { name: "PwC AI Labs", website: "https://www.pwc.com/gx/en/issues/data-and-analytics/artificial-intelligence.html", location: "US/UK" },
        SeedCompany { name: "EY AI", website: "https://www.ey.com/en_gl/ai", location: "UK" },
        SeedCompany { name: "KPMG Lighthouse", website: "https://kpmg.com/xx/en/home/services/advisory/management-consulting/kpmg-lighthouse.html", location: "US" },
        SeedCompany { name: "IBM Consulting", website: "https://www.ibm.com/consulting", location: "US" },

        // ── US Pure-Play Consultancies & AI Companies ───────────────────
        SeedCompany { name: "Thoughtworks", website: "https://www.thoughtworks.com", location: "US" },
        SeedCompany { name: "EPAM Systems", website: "https://www.epam.com", location: "US" },
        SeedCompany { name: "Slalom", website: "https://www.slalom.com", location: "US" },
        SeedCompany { name: "Booz Allen Hamilton", website: "https://www.boozallen.com", location: "US" },
        SeedCompany { name: "Palantir Technologies", website: "https://www.palantir.com", location: "US" },
        SeedCompany { name: "Scale AI", website: "https://scale.com", location: "US" },
        SeedCompany { name: "Weights & Biases", website: "https://wandb.ai", location: "US" },
        SeedCompany { name: "Anyscale", website: "https://www.anyscale.com", location: "US" },
        SeedCompany { name: "Databricks", website: "https://www.databricks.com", location: "US" },
        SeedCompany { name: "H2O.ai", website: "https://h2o.ai", location: "US" },
        SeedCompany { name: "Domino Data Lab", website: "https://www.dominodatalab.com", location: "US" },
        SeedCompany { name: "Snorkel AI", website: "https://snorkel.ai", location: "US" },
        SeedCompany { name: "Labelbox", website: "https://labelbox.com", location: "US" },
        SeedCompany { name: "Moveworks", website: "https://www.moveworks.com", location: "US" },
        SeedCompany { name: "Cohere", website: "https://cohere.com", location: "US" },
        SeedCompany { name: "Hugging Face", website: "https://huggingface.co", location: "US" },
        SeedCompany { name: "C3.ai", website: "https://c3.ai", location: "US" },
        SeedCompany { name: "DataRobot", website: "https://www.datarobot.com", location: "US" },
        SeedCompany { name: "Tecton", website: "https://www.tecton.ai", location: "US" },
        SeedCompany { name: "Latent AI", website: "https://latentai.com", location: "US" },
        SeedCompany { name: "Landing AI", website: "https://landing.ai", location: "US" },
        SeedCompany { name: "Anthropic", website: "https://www.anthropic.com", location: "US" },
        SeedCompany { name: "OpenAI", website: "https://openai.com", location: "US" },
        SeedCompany { name: "Modular", website: "https://www.modular.com", location: "US" },
        SeedCompany { name: "Determined AI", website: "https://www.determined.ai", location: "US" },
        SeedCompany { name: "Iguazio", website: "https://www.iguazio.com", location: "US" },
        SeedCompany { name: "Cognizant AI", website: "https://www.cognizant.com/us/en/services/ai", location: "US" },

        // ── UK Consultancies & AI Companies ─────────────────────────────
        SeedCompany { name: "Faculty AI", website: "https://faculty.ai", location: "UK" },
        SeedCompany { name: "Datatonic", website: "https://datatonic.com", location: "UK" },
        SeedCompany { name: "Deeper Insights", website: "https://deeperinsights.com", location: "UK" },
        SeedCompany { name: "Peak AI", website: "https://peak.ai", location: "UK" },
        SeedCompany { name: "Cambridge Consultants", website: "https://www.cambridgeconsultants.com", location: "UK" },
        SeedCompany { name: "Secondmind", website: "https://www.secondmind.ai", location: "UK" },
        SeedCompany { name: "Quantexa", website: "https://www.quantexa.com", location: "UK" },
        SeedCompany { name: "Privitar", website: "https://www.privitar.com", location: "UK" },
        SeedCompany { name: "Mind Foundry", website: "https://www.mindfoundry.ai", location: "UK" },
        SeedCompany { name: "Satalia", website: "https://www.satalia.com", location: "UK" },
        SeedCompany { name: "InstaDeep", website: "https://www.instadeep.com", location: "UK" },
        SeedCompany { name: "Synthesized", website: "https://www.synthesized.io", location: "UK" },
        SeedCompany { name: "PolyAI", website: "https://poly.ai", location: "UK" },
        SeedCompany { name: "Tractable", website: "https://tractable.ai", location: "UK" },
        SeedCompany { name: "Wayve", website: "https://wayve.ai", location: "UK" },
        SeedCompany { name: "DeepMind", website: "https://deepmind.google", location: "UK" },
        SeedCompany { name: "Graphcore", website: "https://www.graphcore.ai", location: "UK" },
        SeedCompany { name: "Stability AI", website: "https://stability.ai", location: "UK" },

        // ── EU Consultancies & AI Companies ─────────────────────────────
        SeedCompany { name: "Explosion AI", website: "https://explosion.ai", location: "Germany" },
        SeedCompany { name: "Rasa", website: "https://rasa.com", location: "Germany" },
        SeedCompany { name: "Aleph Alpha", website: "https://aleph-alpha.com", location: "Germany" },
        SeedCompany { name: "Merantix", website: "https://www.merantix.com", location: "Germany" },
        SeedCompany { name: "appliedAI Initiative", website: "https://www.appliedai.de", location: "Germany" },
        SeedCompany { name: "Dataiku", website: "https://www.dataiku.com", location: "France" },
        SeedCompany { name: "Artefact", website: "https://www.artefact.com", location: "France" },
        SeedCompany { name: "LightOn", website: "https://www.lighton.ai", location: "France" },
        SeedCompany { name: "Mistral AI", website: "https://mistral.ai", location: "France" },
        SeedCompany { name: "Silo AI", website: "https://www.silo.ai", location: "Finland" },
        SeedCompany { name: "Xebia", website: "https://xebia.com", location: "Netherlands" },
        SeedCompany { name: "Deepsense.ai", website: "https://deepsense.ai", location: "Poland" },
        SeedCompany { name: "Adesso SE", website: "https://www.adesso.de", location: "Germany" },
        SeedCompany { name: "Reply AI", website: "https://www.reply.com/en/artificial-intelligence", location: "Italy" },
        SeedCompany { name: "Aignostics", website: "https://www.aignostics.com", location: "Germany" },
        SeedCompany { name: "Helsing", website: "https://helsing.ai", location: "Germany" },
        SeedCompany { name: "Crayon", website: "https://www.crayon.com", location: "Norway" },
        SeedCompany { name: "Poolside AI", website: "https://www.poolside.ai", location: "France" },
        SeedCompany { name: "Photoroom", website: "https://www.photoroom.com", location: "France" },
        SeedCompany { name: "DeepL", website: "https://www.deepl.com", location: "Germany" },
    ]
}
