// This file is auto-generated by GraphQL Code Generator.
// Do not edit manually. Run `pnpm codegen` to regenerate.

export const typeDefs = /* GraphQL */ `
schema {
  query: Query
  mutation: Mutation
}

type AnalyzeCompanyResponse {
  companyId: Int
  companyKey: String
  message: String
  success: Boolean!
}

type AnalyzePostsResult {
  analyzed: Int!
  errors: [String!]!
  failed: Int!
  success: Boolean!
}

type ApplyEmailPatternResult {
  contacts: [Contact!]!
  contactsUpdated: Int!
  message: String!
  pattern: String
  success: Boolean!
}

type ArchiveEmailResult {
  message: String!
  success: Boolean!
}

type BatchDetectIntentResult {
  errors: [String!]!
  processed: Int!
  signalsDetected: Int!
  success: Boolean!
}

type BatchOperationResult {
  affected: Int!
  message: String
  success: Boolean!
}

input BatchRecipientInput {
  companyId: Int
  contactId: Int
  email: String!
  name: String!
}

type CancelCompanyEmailsResult {
  cancelledCount: Int!
  failedCount: Int!
  message: String!
  success: Boolean!
}

type CancelEmailResult {
  error: String
  success: Boolean!
}

type ClassifyBatchResult {
  classified: Int!
  message: String!
  success: Boolean!
}

type ClassifyEmailResult {
  classification: String
  confidence: Float
  matchedContactId: Int
  success: Boolean!
}

type CompaniesResponse {
  companies: [Company!]!
  totalCount: Int!
}

type Company {
  ai_classification_confidence: Float!
  ai_classification_reason: String
  ai_tier: Int!
  blocked: Boolean!
  category: CompanyCategory!
  contacts: [Contact!]!
  created_at: String!
  """ML data quality assessment"""
  dataQuality: DataQualityScore!
  deep_analysis: String
  description: String
  email: String
  emailsList: [String!]!
  facts(field: String, limit: Int, offset: Int): [CompanyFact!]!
  facts_count: Int!
  githubUrl: String
  """ICP similarity score via embeddings (0-1)"""
  icpSimilarity: Float
  id: Int!
  industries: [String!]!
  industry: String
  intentScore: Float!
  intentScoreDetails: IntentScore
  intentScoreUpdatedAt: String
  intentSignalsCount: Int!
  job_board_url: String
  key: String!
  last_seen_capture_timestamp: String
  last_seen_crawl_id: String
  last_seen_source_url: String
  linkedin_url: String
  location: String
  logo_url: String
  name: String!
  """ML quality gate evaluation"""
  qualityGate: QualityGateResult!
  """ML-computed rank score (0-1)"""
  rankScore: Float
  score: Float!
  score_reasons: [String!]!
  service_taxonomy: [String!]!
  services: [String!]!
  size: String
  snapshots(limit: Int, offset: Int): [CompanySnapshot!]!
  snapshots_count: Int!
  tags: [String!]!
  updated_at: String!
  website: String
}

enum CompanyCategory {
  AGENCY
  CONSULTANCY
  PRODUCT
  STAFFING
  UNKNOWN
}

type CompanyContactEmail {
  contactFirstName: String!
  contactId: Int!
  contactLastName: String!
  contactPosition: String
  createdAt: String!
  deliveredAt: String
  errorMessage: String
  followupStatus: String
  fromEmail: String!
  id: Int!
  openedAt: String
  recipientName: String
  replyReceived: Boolean!
  resendId: String!
  scheduledAt: String
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

type CompanyFact {
  company_id: Int!
  confidence: Float!
  created_at: String!
  evidence: Evidence!
  field: String!
  id: Int!
  normalized_value: JSON
  value_json: JSON
  value_text: String
}

input CompanyFactInput {
  confidence: Float!
  evidence: EvidenceInput!
  field: String!
  normalized_value: JSON
  value_json: JSON
  value_text: String
}

input CompanyFilterInput {
  category: CompanyCategory
  min_ai_tier: Int
  min_score: Float
  service_taxonomy_any: [String!]
  text: String
}

input CompanyImportInput {
  description: String
  email: String
  linkedin_url: String
  location: String
  name: String!
  size: String
  website: String
}

enum CompanyOrderBy {
  CREATED_AT_DESC
  NAME_ASC
  SCORE_DESC
  UPDATED_AT_DESC
}

type CompanySnapshot {
  capture_timestamp: String
  company_id: Int!
  content_hash: String
  crawl_id: String
  created_at: String!
  evidence: Evidence!
  extracted: JSON
  fetched_at: String!
  http_status: Int
  id: Int!
  jsonld: JSON
  mime: String
  source_url: String!
  text_sample: String
}

type ComputeNextTouchScoresResult {
  contactsUpdated: Int!
  message: String!
  success: Boolean!
  topContacts: [ContactNextTouch!]!
}

type Contact {
  aiProfile: ContactAIProfile
  authenticityFlags: [String!]!
  authenticityScore: Float
  authenticityVerdict: String
  authorityScore: Float
  bouncedEmails: [String!]!
  company: String
  companyId: Int
  createdAt: String!
  deletionFlaggedAt: String
  deletionReasons: [String!]!
  deletionScore: Float
  department: String
  dmReasons: [String!]!
  doNotContact: Boolean!
  email: String
  emailVerified: Boolean
  emails: [String!]!
  firstName: String!
  githubHandle: String
  id: Int!
  isDecisionMaker: Boolean
  lastContactedAt: String
  lastName: String!
  linkedinUrl: String
  nbExecutionTimeMs: Int
  nbFlags: [String!]!
  nbResult: String
  nbRetryToken: String
  nbStatus: String
  nbSuggestedCorrection: String
  nextTouchScore: Float
  position: String
  seniority: String
  tags: [String!]!
  telegramHandle: String
  toBeDeleted: Boolean!
  updatedAt: String!
  userId: String
}

type ContactAIGitHubRepo {
  description: String
  name: String!
  stars: Int!
  topics: [String!]!
}

type ContactAIProfile {
  enrichedAt: String!
  experienceLevel: String!
  githubAiRepos: [ContactAIGitHubRepo!]!
  githubBio: String
  githubTopLanguages: [String!]!
  githubTotalStars: Int!
  linkedinBio: String
  linkedinHeadline: String
  researchAreas: [String!]!
  skills: [String!]!
  specialization: String
  synthesisConfidence: Float!
  synthesisRationale: String
  trigger: String!
}

type ContactEmail {
  attachments: JSON
  ccEmails: [String!]!
  companyId: Int
  contactId: Int!
  createdAt: String!
  deliveredAt: String
  errorMessage: String
  followupStatus: String
  fromEmail: String!
  headers: JSON
  htmlContent: String
  id: Int!
  idempotencyKey: String
  openedAt: String
  parentEmailId: Int
  recipientName: String
  replyReceived: Boolean!
  replyReceivedAt: String
  replyToEmails: [String!]!
  resendId: String!
  scheduledAt: String
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  tags: [String!]!
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

input ContactInput {
  company: String
  companyId: Int
  email: String
  emails: [String!]
  firstName: String!
  githubHandle: String
  lastName: String!
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

type ContactMLScore {
  authorityScore: Float!
  contactId: Int!
  department: String!
  dmReasons: [String!]!
  isDecisionMaker: Boolean!
  seniority: String!
}

type ContactNextTouch {
  contactId: Int!
  firstName: String!
  lastContactedAt: String
  lastName: String!
  nextTouchScore: Float!
  position: String
}

type ContactReminder {
  contactId: Int!
  createdAt: String!
  id: Int!
  note: String
  recurrence: String!
  remindAt: String!
  snoozedUntil: String
  status: String!
  updatedAt: String!
}

type ContactReminderWithContact {
  contact: Contact!
  reminder: ContactReminder!
}

type ContactsResult {
  contacts: [Contact!]!
  totalCount: Int!
}

input CreateCampaignInput {
  addAntiThreadHeader: Boolean
  addUnsubscribeHeaders: Boolean
  companyId: Int
  createdBy: String
  delayDays: JSON
  fromEmail: String
  mode: String
  name: String!
  recipientEmails: [String!]
  replyTo: String
  sequence: JSON
  totalEmailsPlanned: Int
  unsubscribeUrl: String
}

input CreateCompanyInput {
  ai_classification_confidence: Float
  ai_classification_reason: String
  ai_tier: Int
  category: CompanyCategory
  description: String
  email: String
  emails: [String!]
  github_url: String
  industries: [String!]
  industry: String
  key: String!
  linkedin_url: String
  location: String
  logo_url: String
  name: String!
  service_taxonomy: [String!]
  services: [String!]
  size: String
  tags: [String!]
  website: String
}

input CreateContactInput {
  companyId: Int
  email: String
  emails: [String!]
  firstName: String!
  githubHandle: String
  lastName: String
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

input CreateEmailTemplateInput {
  category: String
  description: String
  htmlContent: String
  name: String!
  subject: String
  tags: [String!]
  textContent: String
  variables: [String!]
}

input CreateReminderInput {
  contactId: Int!
  note: String
  recurrence: String
  remindAt: String!
}

type DataQualityScore {
  completeness: Float!
  composite: Float!
  freshness: Float!
  missingFields: [String!]!
  staleFields: [String!]!
}

scalar DateTime

type DeleteCampaignResult {
  message: String
  success: Boolean!
}

type DeleteCompaniesResult {
  deleted: Int!
  message: String!
  success: Boolean!
}

type DeleteCompanyResponse {
  message: String
  success: Boolean!
}

type DeleteContactResult {
  message: String!
  success: Boolean!
}

type DeleteEmailTemplateResult {
  message: String
  success: Boolean!
}

type DetectIntentResult {
  intentScore: Float
  message: String
  signalsDetected: Int!
  success: Boolean!
}

scalar EmailAddress

type EmailCampaign {
  addAntiThreadHeader: Boolean!
  addUnsubscribeHeaders: Boolean!
  companyId: Int
  createdAt: String!
  createdBy: String
  delayDays: JSON
  emailsFailed: Int!
  emailsScheduled: Int!
  emailsSent: Int!
  fromEmail: String
  id: String!
  mode: String
  name: String!
  recipientEmails: [String!]!
  replyTo: String
  sequence: JSON
  startAt: String
  status: String!
  totalEmailsPlanned: Int
  totalRecipients: Int!
  unsubscribeUrl: String
  updatedAt: String!
}

type EmailCampaignsResult {
  campaigns: [EmailCampaign!]!
  totalCount: Int!
}

type EmailPreview {
  drySendResult: String
  htmlContent: String!
  subject: String!
}

type EmailStats {
  bouncedThisMonth: Int!
  bouncedThisWeek: Int!
  bouncedToday: Int!
  deliveredThisMonth: Int!
  deliveredThisWeek: Int!
  deliveredToday: Int!
  openedThisMonth: Int!
  openedThisWeek: Int!
  openedToday: Int!
  scheduledFuture: Int!
  scheduledToday: Int!
  sentThisMonth: Int!
  sentThisWeek: Int!
  sentToday: Int!
  totalSent: Int!
}

type EmailTemplate {
  category: String
  createdAt: String!
  description: String
  htmlContent: String
  id: Int!
  isActive: Boolean!
  name: String!
  subject: String
  tags: [String!]!
  textContent: String
  updatedAt: String!
  userId: String
  variables: [String!]!
}

type EmailTemplatesResult {
  templates: [EmailTemplate!]!
  totalCount: Int!
}

type EnhanceAllContactsResult {
  companiesProcessed: Int!
  errors: [String!]!
  message: String!
  success: Boolean!
  totalContactsProcessed: Int!
  totalEmailsFound: Int!
}

type EnhanceCompanyResponse {
  companyId: Int
  companyKey: String
  message: String
  success: Boolean!
}

type EnrichAIContactResult {
  aiProfile: ContactAIProfile
  contactId: Int!
  message: String!
  success: Boolean!
}

type EnrichAIContactsBulkResult {
  enriched: Int!
  errors: [String!]!
  message: String!
  skipped: Int!
  success: Boolean!
}

type Evidence {
  capture_timestamp: String
  content_hash: String
  crawl_id: String
  extractor_version: String
  http_status: Int
  method: ExtractMethod!
  mime: String
  observed_at: String!
  source_type: SourceType!
  source_url: String!
  warc: WarcPointer
}

input EvidenceInput {
  capture_timestamp: String
  content_hash: String
  crawl_id: String
  extractor_version: String
  http_status: Int
  method: ExtractMethod!
  mime: String
  observed_at: String!
  source_type: SourceType!
  source_url: String!
  warc: WarcPointerInput
}

enum ExtractMethod {
  DOM
  HEURISTIC
  JSONLD
  LLM
  META
}

type ExtractedSkill {
  confidence: Float!
  label: String!
  tag: String!
}

type FindCompanyResult {
  company: Company
  found: Boolean!
}

type FindContactEmailResult {
  candidatesTried: Int!
  email: String
  emailFound: Boolean!
  message: String!
  success: Boolean!
  verified: Boolean
}

input FollowUpBatchInput {
  companyId: Int!
  customInstructions: String
  customSubject: String
  daysAfter: Int!
  sequenceNumber: String!
}

type FollowUpBatchResult {
  contactCount: Int!
  emailIds: [String!]!
  message: String!
  success: Boolean!
}

type FollowUpEmail {
  companyId: Int
  contactId: Int!
  createdAt: String!
  followupStatus: String
  fromEmail: String!
  id: Int!
  recipientName: String
  resendId: String!
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  toEmails: [String!]!
}

type FollowUpEmailsResult {
  emails: [FollowUpEmail!]!
  totalCount: Int!
}

input GenerateEmailInput {
  companyName: String
  purpose: String!
  recipientName: String!
  recipientRole: String
  templateId: Int
  tone: String
}

type GenerateEmailResult {
  html: String!
  subject: String!
  text: String!
}

type GenerateEmbeddingsResult {
  errors: [String!]!
  failed: Int!
  processed: Int!
  success: Boolean!
}

input GenerateReplyInput {
  additionalDetails: String
  includeCalendly: Boolean
  originalEmailContent: String!
  originalSender: String!
  replyTo: String
  replyType: String
  tone: String
}

type GenerateReplyResult {
  body: String!
  subject: String!
}

type ImportCompaniesResult {
  errors: [String!]!
  failed: Int!
  imported: Int!
  success: Boolean!
}

type ImportCompanyResult {
  company: Company
  contactsImported: Int!
  contactsSkipped: Int!
  errors: [String!]!
  success: Boolean!
}

input ImportCompanyWithContactsInput {
  companyName: String!
  contacts: [ImportContactInput!]!
  linkedinUrl: String
  skillFilter: [String!]
  website: String
}

input ImportContactInput {
  headline: String
  linkedinUrl: String
  name: String!
  workEmail: String
}

type ImportContactsResult {
  errors: [String!]!
  failed: Int!
  imported: Int!
  success: Boolean!
}

type ImportResendResult {
  companyMatchCount: Int!
  contactMatchCount: Int!
  durationMs: Int!
  error: String
  errorCount: Int!
  newCount: Int!
  skippedCount: Int!
  success: Boolean!
  totalFetched: Int!
  updatedCount: Int!
}

type IntentDashboard {
  companiesWithIntent: Int!
  recentSignals: [IntentSignal!]!
  signalsByType: [SignalTypeCount!]!
  topIntentCompanies: [Company!]!
  totalSignals: Int!
}

type IntentScore {
  budget: Float!
  growth: Float!
  hiring: Float!
  leadership: Float!
  overall: Float!
  product: Float!
  signalCount: Int!
  tech: Float!
  updatedAt: String
}

type IntentSignal {
  companyId: Int!
  confidence: Float!
  createdAt: String!
  decayDays: Int!
  decaysAt: String!
  detectedAt: String!
  evidence: [String!]!
  freshness: Float!
  id: Int!
  metadata: JSON
  modelVersion: String
  rawText: String!
  signalType: IntentSignalType!
  sourceType: String!
  sourceUrl: String
}

enum IntentSignalType {
  BUDGET_CYCLE
  GROWTH_SIGNAL
  HIRING_INTENT
  LEADERSHIP_CHANGE
  PRODUCT_LAUNCH
  TECH_ADOPTION
}

type IntentSignalsResponse {
  signals: [IntentSignal!]!
  totalCount: Int!
}

scalar JSON

type LinkedInPost {
  analyzedAt: String
  authorName: String
  authorUrl: String
  companyId: Int
  contactId: Int
  content: String
  createdAt: String!
  employmentType: String
  id: Int!
  location: String
  postedAt: String
  rawData: JSON
  scrapedAt: String!
  skills: [ExtractedSkill!]
  title: String
  type: LinkedInPostType!
  url: String!
}

enum LinkedInPostType {
  job
  post
}

type MLStats {
  companiesEmbedded: Int!
  lastEmbeddingAt: String
  modelsAvailable: [String!]!
  totalCompanies: Int!
}

type MarkRepliedResult {
  message: String
  success: Boolean!
}

type MergeCompaniesResult {
  keptCompanyId: Int
  merged: Int!
  message: String!
  success: Boolean!
}

type MergeDuplicateContactsResult {
  mergedCount: Int!
  message: String!
  removedCount: Int!
  success: Boolean!
}

type Mutation {
  add_company_facts(company_id: Int!, facts: [CompanyFactInput!]!): [CompanyFact!]!
  analyzeCompany(id: Int, key: String): AnalyzeCompanyResponse!
  analyzeLinkedInPosts(limit: Int, postIds: [Int!]): AnalyzePostsResult!
  applyEmailPattern(companyId: Int!): ApplyEmailPatternResult!
  archiveEmail(id: Int!): ArchiveEmailResult!
  batchDetectIntent(companyIds: [Int!]!): BatchDetectIntentResult!
  blockCompany(id: Int!): Company!
  cancelCompanyEmails(companyId: Int!): CancelCompanyEmailsResult!
  cancelScheduledEmail(resendId: String!): CancelEmailResult!
  classifyAllPending: ClassifyBatchResult!
  classifyReceivedEmail(id: Int!): ClassifyEmailResult!
  computeContactDeletionScores(companyId: Int): BatchOperationResult!
  computeNextTouchScores(companyId: Int!): ComputeNextTouchScoresResult!
  createCompany(input: CreateCompanyInput!): Company!
  createContact(input: CreateContactInput!): Contact!
  createDraftCampaign(input: CreateCampaignInput!): EmailCampaign!
  createEmailTemplate(input: CreateEmailTemplateInput!): EmailTemplate!
  createReminder(input: CreateReminderInput!): ContactReminder!
  deleteCampaign(id: String!): DeleteCampaignResult!
  deleteCompanies(companyIds: [Int!]!): DeleteCompaniesResult!
  deleteCompany(id: Int!): DeleteCompanyResponse!
  deleteContact(id: Int!): DeleteContactResult!
  deleteEmailTemplate(id: Int!): DeleteEmailTemplateResult!
  deleteLinkedInPost(id: Int!): Boolean!
  detectIntentSignals(companyId: Int!): DetectIntentResult!
  dismissReminder(id: Int!): ContactReminder!
  enhanceAllContacts: EnhanceAllContactsResult!
  enhanceCompany(id: Int, key: String): EnhanceCompanyResponse!
  enrichAIContactProfile(contactId: Int!): EnrichAIContactResult!
  enrichAIContactsForCompany(companyId: Int!): EnrichAIContactsBulkResult!
  findCompanyEmails(companyId: Int!): EnhanceAllContactsResult!
  findContactEmail(contactId: Int!): FindContactEmailResult!
  flagContactsForDeletion(threshold: Float): BatchOperationResult!
  """Generate and store embeddings for companies missing them. Admin only."""
  generateCompanyEmbeddings(batchSize: Int, companyIds: [Int!]): GenerateEmbeddingsResult!
  generateEmail(input: GenerateEmailInput!): GenerateEmailResult!
  generateReply(input: GenerateReplyInput!): GenerateReplyResult!
  importCompanies(companies: [CompanyImportInput!]!): ImportCompaniesResult!
  importCompanyWithContacts(input: ImportCompanyWithContactsInput!): ImportCompanyResult!
  importContacts(contacts: [ContactInput!]!): ImportContactsResult!
  importResendEmails(maxEmails: Int): ImportResendResult!
  ingest_company_snapshot(capture_timestamp: String, company_id: Int!, content_hash: String, crawl_id: String, evidence: EvidenceInput!, extracted: JSON, fetched_at: String!, http_status: Int, jsonld: JSON, mime: String, source_url: String!, text_sample: String): CompanySnapshot!
  launchEmailCampaign(id: String!): EmailCampaign!
  markContactEmailVerified(contactId: Int!, verified: Boolean!): Contact!
  markEmailReplied(resendId: String!): MarkRepliedResult!
  mergeDuplicateCompanies(companyIds: [Int!]!): MergeCompaniesResult!
  mergeDuplicateContacts(companyId: Int!): MergeDuplicateContactsResult!
  previewEmail(input: PreviewEmailInput!): EmailPreview!
  purgeDeletedContacts(companyId: Int): BatchOperationResult!
  refreshIntentScores: RefreshIntentResult!
  salescueAnalyze(modules: [SalescueModule!], text: String!): SalescueAnalyzeResult!
  scheduleBatchEmails(input: ScheduleBatchEmailsInput!): ScheduleBatchResult!
  scheduleFollowUpBatch(input: FollowUpBatchInput!): FollowUpBatchResult!
  scoreContactsML(companyId: Int!): ScoreContactsMLResult!
  sendEmail(input: SendEmailInput!): SendEmailResult!
  sendOutreachEmail(input: SendOutreachEmailInput!): SendOutreachEmailResult!
  sendScheduledEmailNow(resendId: String!): SendNowResult!
  snoozeReminder(days: Int!, id: Int!): ContactReminder!
  syncResendEmails(companyId: Int): SyncResendResult!
  unarchiveEmail(id: Int!): ArchiveEmailResult!
  unblockCompany(id: Int!): Company!
  unflagContactForDeletion(id: Int!): Contact!
  unverifyCompanyContacts(companyId: Int!): UnverifyContactsResult!
  updateCampaign(id: String!, input: UpdateCampaignInput!): EmailCampaign!
  updateCompany(id: Int!, input: UpdateCompanyInput!): Company!
  updateContact(id: Int!, input: UpdateContactInput!): Contact!
  updateEmailTemplate(id: Int!, input: UpdateEmailTemplateInput!): EmailTemplate!
  updateReminder(id: Int!, input: UpdateReminderInput!): ContactReminder!
  updateUserSettings(settings: UserSettingsInput!, userId: String!): UserSettings!
  upsertLinkedInPost(input: UpsertLinkedInPostInput!): LinkedInPost!
  upsertLinkedInPosts(inputs: [UpsertLinkedInPostInput!]!): UpsertLinkedInPostsResult!
  """
  Run fake account detection on all contacts for a company, optionally filtered by skills.
  """
  verifyCompanyContacts(companyId: Int!, skillFilter: [String!]): VerifyCompanyContactsResult!
  """
  Run fake account detection on a single contact. Enriches LinkedIn + GitHub, then scores.
  """
  verifyContactAuthenticity(contactId: Int!): VerifyAuthenticityResult!
  verifyContactEmail(contactId: Int!): VerifyEmailResult!
}

input PreviewEmailInput {
  content: String!
  drySend: Boolean
  recipientEmail: String!
  subject: String!
}

type QualityGateResult {
  adjustedScore: Float!
  flags: [String!]!
  pass: Boolean!
  recommendations: [String!]!
}

type Query {
  allCompanyTags: [String!]!
  companies(filter: CompanyFilterInput, limit: Int, offset: Int, order_by: CompanyOrderBy): CompaniesResponse!
  companiesByIntent(limit: Int, offset: Int, signalType: IntentSignalType, threshold: Float!): CompaniesResponse!
  """Find companies similar to a given company by ID"""
  companiesLike(companyId: Int!, limit: Int, minScore: Float): [SimilarCompanyResult!]!
  company(id: Int, key: String): Company
  companyContactEmails(companyId: Int!): [CompanyContactEmail!]!
  company_facts(company_id: Int!, field: String, limit: Int, offset: Int): [CompanyFact!]!
  company_snapshots(company_id: Int!, limit: Int, offset: Int): [CompanySnapshot!]!
  contact(id: Int!): Contact
  contactByEmail(email: String!): Contact
  contactEmails(contactId: Int!): [ContactEmail!]!
  contactReminders(contactId: Int!): [ContactReminder!]!
  contacts(companyId: Int, limit: Int, offset: Int, search: String): ContactsResult!
  dueReminders: [ContactReminderWithContact!]!
  emailCampaign(id: String!): EmailCampaign
  emailCampaigns(limit: Int, offset: Int, status: String): EmailCampaignsResult!
  emailStats: EmailStats!
  emailTemplate(id: Int!): EmailTemplate
  emailTemplates(category: String, limit: Int, offset: Int): EmailTemplatesResult!
  emailsNeedingFollowUp(limit: Int, offset: Int): FollowUpEmailsResult!
  findCompany(name: String, website: String): FindCompanyResult!
  intentDashboard: IntentDashboard!
  intentSignals(companyId: Int!, limit: Int, offset: Int, signalType: IntentSignalType): IntentSignalsResponse!
  linkedinPost(id: Int!): LinkedInPost
  linkedinPosts(companyId: Int, limit: Int, offset: Int, type: LinkedInPostType): [LinkedInPost!]!
  """ML model health and stats"""
  mlStats: MLStats!
  receivedEmail(id: Int!): ReceivedEmail
  receivedEmails(archived: Boolean, classification: String, limit: Int, offset: Int): ReceivedEmailsResult!
  """Next best companies to contact based on ML scoring"""
  recommendedCompanies(limit: Int, minScore: Float): [RecommendedCompany!]!
  """Best contacts to reach within a company"""
  recommendedContacts(companyId: Int!, limit: Int): [RankedContact!]!
  resendEmail(resendId: String!): ResendEmailDetail
  salescueEntities(text: String!): SalescueEntitiesResult!
  salescueHealth: SalescueHealth!
  salescueIcp(icp: String!, prospect: String!): SalescueICPResult!
  salescueIntent(text: String!): SalescueIntentResult!
  salescueObjection(text: String!): SalescueObjectionResult!
  salescueReply(text: String!, touchpoint: Int): SalescueReplyResult!
  salescueScore(text: String!): SalescueScoreResult!
  salescueSentiment(text: String!): SalescueSentimentResult!
  salescueSpam(text: String!): SalescueSpamResult!
  salescueSubject(subjects: [String!]!): SalescueSubjectResult!
  salescueTriggers(text: String!): SalescueTriggersResult!
  """
  Semantic similarity search: find companies matching a natural language query
  """
  similarCompanies(limit: Int, minAiTier: Int, minScore: Float, query: String!): [SimilarCompanyResult!]!
  similarPosts(limit: Int, minScore: Float, postId: Int!): [SimilarPost!]!
  userSettings(userId: String!): UserSettings
}

type RankedContact {
  contact: Contact!
  rankScore: Float!
  reasons: [String!]!
}

type ReceivedEmail {
  archivedAt: String
  attachments: JSON
  ccEmails: [String!]!
  classification: String
  classificationConfidence: Float
  classifiedAt: String
  createdAt: String!
  fromEmail: String
  htmlContent: String
  id: Int!
  matchedContactId: Int
  matchedOutboundId: Int
  messageId: String
  receivedAt: String!
  replyToEmails: [String!]!
  resendId: String!
  subject: String
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

type ReceivedEmailsResult {
  emails: [ReceivedEmail!]!
  totalCount: Int!
}

type RecommendedCompany {
  company: Company!
  reasons: [String!]!
  score: Float!
}

type RefreshIntentResult {
  companiesUpdated: Int!
  success: Boolean!
}

type ResendEmailDetail {
  bcc: [String!]
  cc: [String!]
  createdAt: String!
  from: String!
  html: String
  id: String!
  lastEvent: String
  scheduledAt: String
  subject: String
  text: String
  to: [String!]!
}

type SalescueAnalyzeResult {
  errors: [SalescueModuleError!]!
  modulesRun: Int!
  results: JSON!
  timings: JSON!
  totalTime: Float!
}

type SalescueAnomalyResult {
  anomalyScore: Float!
  anomalyType: String!
  channelAttribution: JSON!
  cosineSimilarity: Float!
  isAnomalous: Boolean!
  textPriorAdjustment: Float!
  typeConfidence: Float!
  zScore: Float!
}

type SalescueBanditAlternative {
  sampledReward: Float!
  subjectStyle: String!
  template: String!
  timing: String!
}

type SalescueBanditArm {
  subjectStyle: String!
  template: String!
  timing: String!
}

type SalescueBanditResult {
  alternatives: [SalescueBanditAlternative!]!
  armIndex: Int!
  bestArm: SalescueBanditArm!
  expectedReward: Float!
  explorationTemperature: Float!
  sampledReward: Float!
  totalArms: Int!
}

type SalescueCallResult {
  action: String!
  commitmentCount: Int!
  commitments: [SalescueCommitment!]!
  dealHealth: Int!
  modelConfidence: Float!
  momentum: String!
  negatedCommitmentCount: Int!
  turnScores: [Float!]!
  turnUncertainties: [Float!]!
  turningPoints: [SalescueTurningPoint!]!
}

type SalescueCoachingCard {
  avoid: [String!]!
  example: String!
  framework: String!
  steps: [String!]!
}

type SalescueCommitment {
  negated: Boolean!
  pattern: String!
  speaker: String!
  turn: Int!
  type: String!
}

type SalescueEmailgenResult {
  contextUsed: JSON!
  email: String!
  emailType: String!
  hasCallToAction: Boolean!
  promptTokens: Int!
  wordCount: Int!
}

type SalescueEntitiesResult {
  entities: [SalescueEntity!]!
  neuralCount: Int!
  regexCount: Int!
  typesFound: [String!]!
}

type SalescueEntity {
  confidence: Float!
  endChar: Int
  role: String!
  roleScores: JSON!
  source: String!
  startChar: Int
  text: String!
  type: String!
}

type SalescueGraphResult {
  edgeCount: Int
  graphLabel: String!
  graphScore: Float!
  graphSignals: [SalescueGraphSignal!]!
  labelConfidence: Float!
  nodeCount: Int
  note: String
  similarCompanies: [SalescueSimilarCompany!]!
}

type SalescueGraphSignal {
  strength: Float!
  type: String!
  with: String!
}

type SalescueHealth {
  device: String!
  moduleCount: Int!
  modules: [String!]!
  status: String!
  version: String!
}

type SalescueICPDimensionFit {
  distance: Float!
  fit: Float
  icpSpread: Float!
  status: String!
}

type SalescueICPResult {
  dealbreakers: [String!]!
  dimensions: JSON!
  missing: [String!]!
  qualified: Boolean!
  score: Float!
}

type SalescueIntentResult {
  confidence: Float!
  dataPoints: Int!
  distribution: JSON!
  stage: String!
  trajectory: SalescueIntentTrajectory
}

type SalescueIntentTrajectory {
  acceleration: Float!
  currentIntensity: Float!
  daysToPurchase: Int!
  direction: String!
  velocity: Float!
}

enum SalescueModule {
  ANOMALY
  BANDIT
  CALL
  EMAILGEN
  ENTITIES
  GRAPH
  ICP
  INTENT
  OBJECTION
  REPLY
  SCORE
  SENTIMENT
  SPAM
  SUBJECT
  SURVIVAL
  TRIGGERS
}

type SalescueModuleError {
  error: String!
  module: String!
}

type SalescueObjectionResult {
  category: String!
  categoryConfidence: Float!
  coaching: SalescueCoachingCard!
  objectionType: String!
  severity: Float!
  topTypes: JSON!
  typeConfidence: Float!
}

type SalescueReplyEvidence {
  label: String!
  text: String!
}

type SalescueReplyResult {
  active: JSON!
  alternativeConfigs: Int!
  configurationScore: Float!
  evidence: [SalescueReplyEvidence!]!
  primary: String!
  scores: JSON!
}

type SalescueScoreCategories {
  analytics: Float!
  automation: Float!
  engagement: Float!
  enrichment: Float!
  intent: Float!
  outreach: Float!
}

type SalescueScoreResult {
  categories: SalescueScoreCategories!
  confidence: Float!
  label: String!
  nSignalsDetected: Int!
  score: Int!
  signals: [SalescueScoreSignal!]!
}

type SalescueScoreSignal {
  attendedPositions: [Int!]!
  attributionType: String!
  category: String!
  causalImpact: Float!
  signal: String!
  strength: Float!
}

type SalescueSentimentEvidence {
  signal: String!
  text: String!
}

type SalescueSentimentResult {
  confidence: Float!
  contextGate: Float!
  evidence: [SalescueSentimentEvidence!]!
  intent: String!
  interactionWeight: Float!
  interpretation: String
  inverted: Boolean!
  sentiment: String!
}

type SalescueSimilarCompany {
  name: String!
  similarity: Float!
}

type SalescueSpamResult {
  aiRisk: Float!
  aspectScores: JSON!
  categoryScores: JSON!
  deliverability: Int!
  gateConfidence: Float!
  gateDecision: String!
  provider: String!
  providerScores: JSON!
  riskFactors: [String!]!
  riskLevel: String!
  spamCategory: String!
  spamScore: Float!
}

type SalescueSubjectRanking {
  rank: Int!
  score: Int!
  subject: String!
}

type SalescueSubjectResult {
  best: String!
  ranking: [SalescueSubjectRanking!]!
  worst: String!
}

type SalescueSurvivalResult {
  medianDaysToConversion: Float!
  pConvert30d: Float!
  pConvert90d: Float!
  riskConfidence: Float!
  riskGroup: String!
  survivalCurve: JSON!
  weibullParams: JSON!
}

type SalescueTriggerEvent {
  confidence: Float!
  displacementCi: [Float!]!
  displacementDays: Float!
  displacementUncertainty: Float!
  fresh: Boolean!
  freshness: String!
  temporalFeatures: SalescueTriggerTemporalFeatures!
  type: String!
}

type SalescueTriggerTemporalFeatures {
  pastSignal: Float!
  recentSignal: Float!
  todaySignal: Float!
}

type SalescueTriggersResult {
  events: [SalescueTriggerEvent!]!
  primary: SalescueTriggerEvent
}

type SalescueTurningPoint {
  delta: Float!
  direction: String!
  probability: Float!
  speaker: String!
  turn: Int!
  uncertainty: Float!
}

input ScheduleBatchEmailsInput {
  body: String!
  """Recipients with name and email"""
  recipients: [BatchRecipientInput!]!
  subject: String!
  """Use business day scheduling (Mon-Fri, 8am UTC, random delays)"""
  useScheduler: Boolean
}

type ScheduleBatchResult {
  failed: Int!
  firstSendDate: String
  lastSendDate: String
  message: String!
  scheduled: Int!
  schedulingPlan: String
  success: Boolean!
}

type ScoreContactsMLResult {
  contactsScored: Int!
  decisionMakersFound: Int!
  message: String!
  results: [ContactMLScore!]!
  success: Boolean!
}

input SendEmailInput {
  from: String
  html: String!
  replyTo: String
  scheduledAt: String
  subject: String!
  text: String
  to: String!
}

type SendEmailResult {
  error: String
  id: String
  success: Boolean!
}

type SendNowResult {
  error: String
  resendId: String
  success: Boolean!
}

input SendOutreachEmailInput {
  postText: String!
  postUrl: String
  recipientEmail: String
  recipientName: String!
  recipientRole: String
  tone: String
}

type SendOutreachEmailResult {
  emailId: String
  error: String
  subject: String
  success: Boolean!
}

type SignalTypeCount {
  count: Int!
  signalType: IntentSignalType!
}

type SimilarCompanyResult {
  company: Company!
  similarity: Float!
}

type SimilarPost {
  post: LinkedInPost!
  similarity: Float!
}

type SkillMatchResult {
  claimedSkills: [String!]!
  githubLanguages: [String!]!
  matched: Boolean!
}

enum SourceType {
  BRAVE_SEARCH
  COMMONCRAWL
  LIVE_FETCH
  MANUAL
  PARTNER
}

type SyncResendResult {
  error: String
  skippedCount: Int!
  success: Boolean!
  totalCount: Int!
  updatedCount: Int!
}

scalar URL

type UnverifyContactsResult {
  count: Int!
  success: Boolean!
}

input UpdateCampaignInput {
  addAntiThreadHeader: Boolean
  addUnsubscribeHeaders: Boolean
  delayDays: JSON
  fromEmail: String
  mode: String
  name: String
  recipientEmails: [String!]
  replyTo: String
  sequence: JSON
  startAt: String
  status: String
  totalEmailsPlanned: Int
  unsubscribeUrl: String
}

input UpdateCompanyInput {
  ai_classification_confidence: Float
  ai_classification_reason: String
  ai_tier: Int
  category: CompanyCategory
  description: String
  email: String
  emails: [String!]
  github_url: String
  industries: [String!]
  industry: String
  job_board_url: String
  key: String
  linkedin_url: String
  location: String
  logo_url: String
  name: String
  score: Float
  score_reasons: [String!]
  service_taxonomy: [String!]
  services: [String!]
  size: String
  tags: [String!]
  website: String
}

input UpdateContactInput {
  doNotContact: Boolean
  email: String
  emails: [String!]
  firstName: String
  githubHandle: String
  lastName: String
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

input UpdateEmailTemplateInput {
  category: String
  description: String
  htmlContent: String
  isActive: Boolean
  name: String
  subject: String
  tags: [String!]
  textContent: String
  variables: [String!]
}

input UpdateReminderInput {
  note: String
  recurrence: String
  remindAt: String
  status: String
}

scalar Upload

input UpsertLinkedInPostInput {
  authorName: String
  authorUrl: String
  companyId: Int
  contactId: Int
  content: String
  employmentType: String
  location: String
  postedAt: String
  rawData: JSON
  title: String
  type: LinkedInPostType!
  url: String!
}

type UpsertLinkedInPostsResult {
  errors: [String!]!
  inserted: Int!
  success: Boolean!
  updated: Int!
}

type UserSettings {
  created_at: String!
  daily_digest: Boolean!
  dark_mode: Boolean!
  email_notifications: Boolean!
  excluded_companies: [String!]
  id: Int!
  updated_at: String!
  user_id: String!
}

input UserSettingsInput {
  daily_digest: Boolean
  dark_mode: Boolean
  email_notifications: Boolean
  excluded_companies: [String!]
}

type VerifyAuthenticityResult {
  authenticityScore: Float!
  contactId: Int!
  flags: [String!]!
  recommendations: [String!]!
  skillMatch: SkillMatchResult
  success: Boolean!
  verdict: String!
}

type VerifyCompanyContactsResult {
  results: [VerifyAuthenticityResult!]!
  review: Int!
  success: Boolean!
  suspicious: Int!
  totalChecked: Int!
  verified: Int!
}

type VerifyEmailResult {
  flags: [String!]
  message: String!
  rawResult: String
  success: Boolean!
  suggestedCorrection: String
  verified: Boolean
}

type WarcPointer {
  digest: String
  filename: String!
  length: Int!
  offset: Int!
}

input WarcPointerInput {
  digest: String
  filename: String!
  length: Int!
  offset: Int!
}
`;