// This file is auto-generated by GraphQL Code Generator.
// Do not edit manually. Run `pnpm codegen` to regenerate.

export const typeDefs = /* GraphQL */ `
schema {
  query: Query
  mutation: Mutation
}

type ATSBoard {
  board_type: ATSBoardType!
  company_id: Int!
  confidence: Float!
  created_at: String!
  evidence: Evidence!
  first_seen_at: String!
  id: Int!
  is_active: Boolean!
  last_seen_at: String!
  updated_at: String!
  url: String!
  vendor: ATSVendor!
}

enum ATSBoardType {
  BOARD_API
  BOARD_WIDGET
  JOBS_PAGE
  UNKNOWN
}

input ATSBoardUpsertInput {
  board_type: ATSBoardType!
  confidence: Float!
  evidence: EvidenceInput!
  is_active: Boolean!
  last_seen_at: String!
  url: String!
  vendor: ATSVendor!
}

enum ATSVendor {
  ASHBY
  BREEZYHR
  GREENHOUSE
  ICIMS
  JAZZHR
  JOBVITE
  LEVER
  ORACLE_TALEO
  OTHER
  SAP_SUCCESSFACTORS
  SMARTRECRUITERS
  TEAMTAILOR
  WORKABLE
}

type AnalyzeCompanyResponse {
  companyId: Int
  companyKey: String
  message: String
  success: Boolean!
}

type ApplyEmailPatternResult {
  contacts: [Contact!]!
  contactsUpdated: Int!
  message: String!
  pattern: String
  success: Boolean!
}

type ArchiveEmailResult {
  message: String!
  success: Boolean!
}

type AshbyEnrichment {
  company_name: String
  enriched_at: String
  industry_tags: [String!]!
  size_signal: String
  tech_signals: [String!]!
}

input BatchRecipientInput {
  companyId: Int
  contactId: Int
  email: String!
  name: String!
}

type BlockJobsResult {
  message: String!
  success: Boolean!
}

type BlockedCompany {
  createdAt: String!
  id: Int!
  name: String!
  reason: String
}

type CancelCompanyEmailsResult {
  cancelledCount: Int!
  failedCount: Int!
  message: String!
  success: Boolean!
}

type CancelEmailResult {
  error: String
  success: Boolean!
}

type CompaniesResponse {
  companies: [Company!]!
  totalCount: Int!
}

type Company {
  ai_classification_confidence: Float!
  ai_classification_reason: String
  ai_tier: Int!
  ashby_enrichment: AshbyEnrichment
  ats_boards: [ATSBoard!]!
  category: CompanyCategory!
  contacts: [Contact!]!
  created_at: String!
  deep_analysis: String
  description: String
  email: String
  emailsList: [String!]!
  facts(field: String, limit: Int, offset: Int): [CompanyFact!]!
  facts_count: Int!
  githubUrl: String
  id: Int!
  industries: [String!]!
  industry: String
  job_board_url: String
  key: String!
  last_seen_capture_timestamp: String
  last_seen_crawl_id: String
  last_seen_source_url: String
  linkedin_url: String
  location: String
  logo_url: String
  name: String!
  score: Float!
  score_reasons: [String!]!
  service_taxonomy: [String!]!
  services: [String!]!
  size: String
  snapshots(limit: Int, offset: Int): [CompanySnapshot!]!
  snapshots_count: Int!
  tags: [String!]!
  updated_at: String!
  website: String
}

enum CompanyCategory {
  AGENCY
  CONSULTANCY
  DIRECTORY
  OTHER
  PRODUCT
  STAFFING
  UNKNOWN
}

type CompanyContactEmail {
  contactFirstName: String!
  contactId: Int!
  contactLastName: String!
  contactPosition: String
  createdAt: String!
  deliveredAt: String
  errorMessage: String
  followupStatus: String
  fromEmail: String!
  id: Int!
  openedAt: String
  recipientName: String
  replyReceived: Boolean!
  resendId: String!
  scheduledAt: String
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

type CompanyFact {
  company_id: Int!
  confidence: Float!
  created_at: String!
  evidence: Evidence!
  field: String!
  id: Int!
  normalized_value: JSON
  value_json: JSON
  value_text: String
}

input CompanyFactInput {
  confidence: Float!
  evidence: EvidenceInput!
  field: String!
  normalized_value: JSON
  value_json: JSON
  value_text: String
}

input CompanyFilterInput {
  category_in: [CompanyCategory!]
  has_ats_boards: Boolean
  min_ai_tier: Int
  min_score: Float
  service_taxonomy_any: [String!]
  text: String
}

input CompanyImportInput {
  description: String
  email: String
  linkedin_url: String
  location: String
  name: String!
  website: String
}

enum CompanyOrderBy {
  CREATED_AT_DESC
  NAME_ASC
  SCORE_DESC
  UPDATED_AT_DESC
}

type CompanySnapshot {
  capture_timestamp: String
  company_id: Int!
  content_hash: String
  crawl_id: String
  created_at: String!
  evidence: Evidence!
  extracted: JSON
  fetched_at: String!
  http_status: Int
  id: Int!
  jsonld: JSON
  mime: String
  source_url: String!
  text_sample: String
}

type Contact {
  bouncedEmails: [String!]!
  company: String
  companyId: Int
  createdAt: String!
  doNotContact: Boolean!
  email: String
  emailVerified: Boolean
  emails: [String!]!
  firstName: String!
  githubHandle: String
  id: Int!
  lastName: String!
  linkedinUrl: String
  nbExecutionTimeMs: Int
  nbFlags: [String!]!
  nbResult: String
  nbRetryToken: String
  nbStatus: String
  nbSuggestedCorrection: String
  position: String
  tags: [String!]!
  telegramHandle: String
  updatedAt: String!
  userId: String
}

type ContactEmail {
  attachments: JSON
  ccEmails: [String!]!
  companyId: Int
  contactId: Int!
  createdAt: String!
  deliveredAt: String
  errorMessage: String
  followupStatus: String
  fromEmail: String!
  headers: JSON
  htmlContent: String
  id: Int!
  idempotencyKey: String
  openedAt: String
  parentEmailId: Int
  recipientName: String
  replyReceived: Boolean!
  replyReceivedAt: String
  replyToEmails: [String!]!
  resendId: String!
  scheduledAt: String
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  tags: [String!]!
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

input ContactInput {
  company: String
  companyId: Int
  email: String
  emails: [String!]
  firstName: String!
  githubHandle: String
  lastName: String!
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

type ContactsResult {
  contacts: [Contact!]!
  totalCount: Int!
}

input CreateCampaignInput {
  addAntiThreadHeader: Boolean
  addUnsubscribeHeaders: Boolean
  companyId: Int
  createdBy: String
  delayDays: JSON
  fromEmail: String
  mode: String
  name: String!
  recipientEmails: [String!]
  replyTo: String
  sequence: JSON
  totalEmailsPlanned: Int
  unsubscribeUrl: String
}

input CreateCompanyInput {
  ai_classification_confidence: Float
  ai_classification_reason: String
  ai_tier: Int
  category: CompanyCategory
  description: String
  email: String
  emails: [String!]
  github_url: String
  industries: [String!]
  industry: String
  key: String!
  linkedin_url: String
  location: String
  logo_url: String
  name: String!
  service_taxonomy: [String!]
  services: [String!]
  size: String
  tags: [String!]
  website: String
}

input CreateContactInput {
  companyId: Int
  email: String
  emails: [String!]
  firstName: String!
  githubHandle: String
  lastName: String
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

input CreateEmailTemplateInput {
  category: String
  description: String
  htmlContent: String
  name: String!
  subject: String
  tags: [String!]
  textContent: String
  variables: [String!]
}

scalar DateTime

type DeleteBlockedCompanyResult {
  message: String
  success: Boolean!
}

type DeleteCampaignResult {
  message: String
  success: Boolean!
}

type DeleteCompaniesResult {
  deleted: Int!
  message: String!
  success: Boolean!
}

type DeleteCompanyResponse {
  message: String
  success: Boolean!
}

type DeleteContactResult {
  message: String!
  success: Boolean!
}

type DeleteEmailTemplateResult {
  message: String
  success: Boolean!
}

scalar EmailAddress

type EmailCampaign {
  addAntiThreadHeader: Boolean!
  addUnsubscribeHeaders: Boolean!
  companyId: Int
  createdAt: String!
  createdBy: String
  delayDays: JSON
  emailsFailed: Int!
  emailsScheduled: Int!
  emailsSent: Int!
  fromEmail: String
  id: String!
  mode: String
  name: String!
  recipientEmails: [String!]!
  replyTo: String
  sequence: JSON
  startAt: String
  status: String!
  totalEmailsPlanned: Int
  totalRecipients: Int!
  unsubscribeUrl: String
  updatedAt: String!
}

type EmailCampaignsResult {
  campaigns: [EmailCampaign!]!
  totalCount: Int!
}

type EmailPreview {
  drySendResult: String
  htmlContent: String!
  subject: String!
}

type EmailStats {
  bouncedThisMonth: Int!
  bouncedThisWeek: Int!
  bouncedToday: Int!
  deliveredThisMonth: Int!
  deliveredThisWeek: Int!
  deliveredToday: Int!
  openedThisMonth: Int!
  openedThisWeek: Int!
  openedToday: Int!
  scheduledFuture: Int!
  scheduledToday: Int!
  sentThisMonth: Int!
  sentThisWeek: Int!
  sentToday: Int!
  totalSent: Int!
}

type EmailTemplate {
  category: String
  createdAt: String!
  description: String
  htmlContent: String
  id: Int!
  isActive: Boolean!
  name: String!
  subject: String
  tags: [String!]!
  textContent: String
  updatedAt: String!
  userId: String
  variables: [String!]!
}

type EmailTemplatesResult {
  templates: [EmailTemplate!]!
  totalCount: Int!
}

type EnhanceAllContactsResult {
  companiesProcessed: Int!
  errors: [String!]!
  message: String!
  success: Boolean!
  totalContactsProcessed: Int!
  totalEmailsFound: Int!
}

type EnhanceCompanyResponse {
  companyId: Int
  companyKey: String
  message: String
  success: Boolean!
}

type Evidence {
  capture_timestamp: String
  content_hash: String
  crawl_id: String
  extractor_version: String
  http_status: Int
  method: ExtractMethod!
  mime: String
  observed_at: String!
  source_type: SourceType!
  source_url: String!
  warc: WarcPointer
}

input EvidenceInput {
  capture_timestamp: String
  content_hash: String
  crawl_id: String
  extractor_version: String
  http_status: Int
  method: ExtractMethod!
  mime: String
  observed_at: String!
  source_type: SourceType!
  source_url: String!
  warc: WarcPointerInput
}

enum ExtractMethod {
  DOM
  HEURISTIC
  JSONLD
  LLM
  META
}

type FindCompanyResult {
  company: Company
  found: Boolean!
}

type FindContactEmailResult {
  candidatesTried: Int!
  email: String
  emailFound: Boolean!
  message: String!
  success: Boolean!
  verified: Boolean
}

input FollowUpBatchInput {
  companyId: Int!
  customInstructions: String
  customSubject: String
  daysAfter: Int!
  sequenceNumber: String!
}

type FollowUpBatchResult {
  contactCount: Int!
  emailIds: [String!]!
  message: String!
  success: Boolean!
}

type FollowUpEmail {
  companyId: Int
  contactId: Int!
  createdAt: String!
  followupStatus: String
  fromEmail: String!
  id: Int!
  recipientName: String
  resendId: String!
  sentAt: String
  sequenceNumber: String
  sequenceType: String
  status: String!
  subject: String!
  toEmails: [String!]!
}

type FollowUpEmailsResult {
  emails: [FollowUpEmail!]!
  totalCount: Int!
}

input GenerateEmailInput {
  companyName: String
  purpose: String!
  recipientName: String!
  recipientRole: String
  templateId: Int
  tone: String
}

type GenerateEmailResult {
  html: String!
  subject: String!
  text: String!
}

input GenerateReplyInput {
  additionalDetails: String
  includeCalendly: Boolean
  originalEmailContent: String!
  originalSender: String!
  replyTo: String
  replyType: String
  tone: String
}

type GenerateReplyResult {
  body: String!
  subject: String!
}

type ImportCompaniesResult {
  errors: [String!]!
  failed: Int!
  imported: Int!
  success: Boolean!
}

type ImportCompanyResult {
  company: Company
  contactsImported: Int!
  contactsSkipped: Int!
  errors: [String!]!
  success: Boolean!
}

input ImportCompanyWithContactsInput {
  companyName: String!
  contacts: [ImportContactInput!]!
  website: String
}

input ImportContactInput {
  linkedinUrl: String
  name: String!
  workEmail: String
}

type ImportContactsResult {
  errors: [String!]!
  failed: Int!
  imported: Int!
  success: Boolean!
}

type ImportResendResult {
  companyMatchCount: Int!
  contactMatchCount: Int!
  durationMs: Int!
  error: String
  errorCount: Int!
  newCount: Int!
  skippedCount: Int!
  success: Boolean!
  totalFetched: Int!
  updatedCount: Int!
}

scalar JSON

type MarkRepliedResult {
  message: String
  success: Boolean!
}

type MergeCompaniesResult {
  keptCompanyId: Int
  merged: Int!
  message: String!
  success: Boolean!
}

type MergeDuplicateContactsResult {
  mergedCount: Int!
  message: String!
  removedCount: Int!
  success: Boolean!
}

type Mutation {
  add_company_facts(company_id: Int!, facts: [CompanyFactInput!]!): [CompanyFact!]!
  analyzeCompany(id: Int, key: String): AnalyzeCompanyResponse!
  applyEmailPattern(companyId: Int!): ApplyEmailPatternResult!
  archiveEmail(id: Int!): ArchiveEmailResult!
  blockCompany(name: String!, reason: String): BlockedCompany!
  blockJobsByCompany(companyName: String!): BlockJobsResult!
  cancelCompanyEmails(companyId: Int!): CancelCompanyEmailsResult!
  cancelScheduledEmail(resendId: String!): CancelEmailResult!
  createCompany(input: CreateCompanyInput!): Company!
  createContact(input: CreateContactInput!): Contact!
  createDraftCampaign(input: CreateCampaignInput!): EmailCampaign!
  createEmailTemplate(input: CreateEmailTemplateInput!): EmailTemplate!
  deleteCampaign(id: String!): DeleteCampaignResult!
  deleteCompanies(companyIds: [Int!]!): DeleteCompaniesResult!
  deleteCompany(id: Int!): DeleteCompanyResponse!
  deleteContact(id: Int!): DeleteContactResult!
  deleteEmailTemplate(id: Int!): DeleteEmailTemplateResult!
  enhanceAllContacts: EnhanceAllContactsResult!
  enhanceCompany(id: Int, key: String): EnhanceCompanyResponse!
  findCompanyEmails(companyId: Int!): EnhanceAllContactsResult!
  findContactEmail(contactId: Int!): FindContactEmailResult!
  generateEmail(input: GenerateEmailInput!): GenerateEmailResult!
  generateReply(input: GenerateReplyInput!): GenerateReplyResult!
  importCompanies(companies: [CompanyImportInput!]!): ImportCompaniesResult!
  importCompanyWithContacts(input: ImportCompanyWithContactsInput!): ImportCompanyResult!
  importContacts(contacts: [ContactInput!]!): ImportContactsResult!
  importResendEmails(maxEmails: Int): ImportResendResult!
  ingest_company_snapshot(capture_timestamp: String, company_id: Int!, content_hash: String, crawl_id: String, evidence: EvidenceInput!, extracted: JSON, fetched_at: String!, http_status: Int, jsonld: JSON, mime: String, source_url: String!, text_sample: String): CompanySnapshot!
  launchEmailCampaign(id: String!): EmailCampaign!
  markContactEmailVerified(contactId: Int!, verified: Boolean!): Contact!
  markEmailReplied(resendId: String!): MarkRepliedResult!
  mergeDuplicateCompanies(companyIds: [Int!]!): MergeCompaniesResult!
  mergeDuplicateContacts(companyId: Int!): MergeDuplicateContactsResult!
  previewEmail(input: PreviewEmailInput!): EmailPreview!
  scheduleBatchEmails(input: ScheduleBatchEmailsInput!): ScheduleBatchResult!
  scheduleFollowUpBatch(input: FollowUpBatchInput!): FollowUpBatchResult!
  sendEmail(input: SendEmailInput!): SendEmailResult!
  sendOutreachEmail(input: SendOutreachEmailInput!): SendOutreachEmailResult!
  sendScheduledEmailNow(resendId: String!): SendNowResult!
  syncResendEmails(companyId: Int): SyncResendResult!
  unarchiveEmail(id: Int!): ArchiveEmailResult!
  unblockCompany(id: Int!): DeleteBlockedCompanyResult!
  unverifyCompanyContacts(companyId: Int!): UnverifyContactsResult!
  updateCampaign(id: String!, input: UpdateCampaignInput!): EmailCampaign!
  updateCompany(id: Int!, input: UpdateCompanyInput!): Company!
  updateContact(id: Int!, input: UpdateContactInput!): Contact!
  updateEmailTemplate(id: Int!, input: UpdateEmailTemplateInput!): EmailTemplate!
  updateUserSettings(settings: UserSettingsInput!, userId: String!): UserSettings!
  upsert_company_ats_boards(boards: [ATSBoardUpsertInput!]!, company_id: Int!): [ATSBoard!]!
  verifyContactEmail(contactId: Int!): VerifyEmailResult!
}

input PreviewEmailInput {
  content: String!
  drySend: Boolean
  recipientEmail: String!
  subject: String!
}

type Query {
  allCompanyTags: [String!]!
  blockedCompanies: [BlockedCompany!]!
  companies(filter: CompanyFilterInput, limit: Int, offset: Int, order_by: CompanyOrderBy): CompaniesResponse!
  company(id: Int, key: String): Company
  companyContactEmails(companyId: Int!): [CompanyContactEmail!]!
  company_ats_boards(company_id: Int!): [ATSBoard!]!
  company_facts(company_id: Int!, field: String, limit: Int, offset: Int): [CompanyFact!]!
  company_snapshots(company_id: Int!, limit: Int, offset: Int): [CompanySnapshot!]!
  contact(id: Int!): Contact
  contactByEmail(email: String!): Contact
  contactEmails(contactId: Int!): [ContactEmail!]!
  contacts(companyId: Int, limit: Int, offset: Int, search: String): ContactsResult!
  emailCampaign(id: String!): EmailCampaign
  emailCampaigns(limit: Int, offset: Int, status: String): EmailCampaignsResult!
  emailStats: EmailStats!
  emailTemplate(id: Int!): EmailTemplate
  emailTemplates(category: String, limit: Int, offset: Int): EmailTemplatesResult!
  emailsNeedingFollowUp(limit: Int, offset: Int): FollowUpEmailsResult!
  findCompany(name: String, website: String): FindCompanyResult!
  receivedEmail(id: Int!): ReceivedEmail
  receivedEmails(archived: Boolean, limit: Int, offset: Int): ReceivedEmailsResult!
  resendEmail(resendId: String!): ResendEmailDetail
  userSettings(userId: String!): UserSettings
}

type ReceivedEmail {
  archivedAt: String
  attachments: JSON
  ccEmails: [String!]!
  createdAt: String!
  fromEmail: String
  htmlContent: String
  id: Int!
  messageId: String
  receivedAt: String!
  replyToEmails: [String!]!
  resendId: String!
  subject: String
  textContent: String
  toEmails: [String!]!
  updatedAt: String!
}

type ReceivedEmailsResult {
  emails: [ReceivedEmail!]!
  totalCount: Int!
}

type ResendEmailDetail {
  bcc: [String!]
  cc: [String!]
  createdAt: String!
  from: String!
  html: String
  id: String!
  lastEvent: String
  scheduledAt: String
  subject: String
  text: String
  to: [String!]!
}

input ScheduleBatchEmailsInput {
  body: String!
  """Recipients with name and email"""
  recipients: [BatchRecipientInput!]!
  subject: String!
  """Use business day scheduling (Mon-Fri, 8am UTC, random delays)"""
  useScheduler: Boolean
}

type ScheduleBatchResult {
  failed: Int!
  firstSendDate: String
  lastSendDate: String
  message: String!
  scheduled: Int!
  schedulingPlan: String
  success: Boolean!
}

input SendEmailInput {
  from: String
  html: String!
  replyTo: String
  scheduledAt: String
  subject: String!
  text: String
  to: String!
}

type SendEmailResult {
  error: String
  id: String
  success: Boolean!
}

type SendNowResult {
  error: String
  resendId: String
  success: Boolean!
}

input SendOutreachEmailInput {
  postText: String!
  postUrl: String
  recipientEmail: String
  recipientName: String!
  recipientRole: String
  tone: String
}

type SendOutreachEmailResult {
  emailId: String
  error: String
  subject: String
  success: Boolean!
}

enum SourceType {
  COMMONCRAWL
  LIVE_FETCH
  MANUAL
  PARTNER
}

type SyncResendResult {
  error: String
  skippedCount: Int!
  success: Boolean!
  totalCount: Int!
  updatedCount: Int!
}

scalar URL

type UnverifyContactsResult {
  count: Int!
  success: Boolean!
}

input UpdateCampaignInput {
  addAntiThreadHeader: Boolean
  addUnsubscribeHeaders: Boolean
  delayDays: JSON
  fromEmail: String
  mode: String
  name: String
  recipientEmails: [String!]
  replyTo: String
  sequence: JSON
  startAt: String
  status: String
  totalEmailsPlanned: Int
  unsubscribeUrl: String
}

input UpdateCompanyInput {
  ai_classification_confidence: Float
  ai_classification_reason: String
  ai_tier: Int
  category: CompanyCategory
  description: String
  email: String
  emails: [String!]
  github_url: String
  industries: [String!]
  industry: String
  job_board_url: String
  key: String
  linkedin_url: String
  location: String
  logo_url: String
  name: String
  score: Float
  score_reasons: [String!]
  service_taxonomy: [String!]
  services: [String!]
  size: String
  tags: [String!]
  website: String
}

input UpdateContactInput {
  doNotContact: Boolean
  email: String
  emails: [String!]
  firstName: String
  githubHandle: String
  lastName: String
  linkedinUrl: String
  position: String
  tags: [String!]
  telegramHandle: String
}

input UpdateEmailTemplateInput {
  category: String
  description: String
  htmlContent: String
  isActive: Boolean
  name: String
  subject: String
  tags: [String!]
  textContent: String
  variables: [String!]
}

scalar Upload

type UserSettings {
  created_at: String!
  daily_digest: Boolean!
  dark_mode: Boolean!
  email_notifications: Boolean!
  excluded_companies: [String!]
  id: Int!
  updated_at: String!
  user_id: String!
}

input UserSettingsInput {
  daily_digest: Boolean
  dark_mode: Boolean
  email_notifications: Boolean
  excluded_companies: [String!]
}

type VerifyEmailResult {
  flags: [String!]
  message: String!
  rawResult: String
  success: Boolean!
  suggestedCorrection: String
  verified: Boolean
}

type WarcPointer {
  digest: String
  filename: String!
  length: Int!
  offset: Int!
}

input WarcPointerInput {
  digest: String
  filename: String!
  length: Int!
  offset: Int!
}
`;