import {
  pgTable,
  text,
  integer,
  real,
  index,
  uniqueIndex,
  serial,
  boolean,
  vector,
  jsonb,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { sql, relations } from "drizzle-orm";

// Re-export Better Auth tables (user, session, account, verification)
export { user, session, account, verification } from "@ai-apps/auth/schema";

export const companies = pgTable("companies", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(), // Unique identifier (slug/domain)
  name: text("name").notNull(),
  logo_url: text("logo_url"),
  website: text("website"),
  description: text("description"),
  industry: text("industry"),
  size: text("size"), // e.g., "1-10", "11-50", "51-200", etc.
  location: text("location"),

  // Golden record fields
  canonical_domain: text("canonical_domain"),
  category: text("category", {
    enum: [
      "CONSULTANCY",
      "STAFFING",
      "AGENCY",
      "PRODUCT",
      "UNKNOWN",
    ],
  })
    .notNull()
    .default("UNKNOWN"),
  tags: text("tags"), // JSON array
  services: text("services"), // JSON array of human-readable service phrases
  service_taxonomy: text("service_taxonomy"), // JSON array of normalized taxonomy IDs
  industries: text("industries"), // JSON array for multi-industry

  linkedin_url: text("linkedin_url"),
  job_board_url: text("job_board_url"),

  score: real("score").notNull().default(0.5), // 0..1
  score_reasons: text("score_reasons"), // JSON array

  // AI company tier: 0 = not AI, 1 = ai_first, 2 = ai_native
  ai_tier: integer("ai_tier").notNull().default(0),
  ai_classification_reason: text("ai_classification_reason"),
  ai_classification_confidence: real("ai_classification_confidence").default(0.5),

  // Pipeline blocklist: blocked companies are hidden from UI and skipped by pipeline
  blocked: boolean("blocked").notNull().default(false),

  // Deep company analysis (Markdown, generated by Browser Rendering + DeepSeek)
  deep_analysis: text("deep_analysis"),

  // CRM fields
  email: text("email"),
  emails: text("emails"), // JSON array
  github_url: text("github_url"),

  // GitHub pattern analysis (populated by github-patterns crate)
  github_org: text("github_org"),                         // extracted org login
  github_ai_score: real("github_ai_score"),               // 0..1 AI adoption
  github_hiring_score: real("github_hiring_score"),       // 0..1 hiring signals
  github_activity_score: real("github_activity_score"),   // 0..1 commit/release velocity
  github_patterns: text("github_patterns"),               // full OrgPatterns JSON
  github_analyzed_at: text("github_analyzed_at"),         // ISO timestamp of last scan

  // HuggingFace Hub presence (populated by enrich_hf_hub.py)
  hf_org_name: text("hf_org_name"),                        // resolved HF org
  hf_presence_score: real("hf_presence_score").default(0),  // 0..100

  // Intent signal scoring (aggregated from intentSignals table)
  intent_score: real("intent_score").notNull().default(0), // 0..100
  intent_score_updated_at: text("intent_score_updated_at"),
  intent_signals_count: integer("intent_signals_count").notNull().default(0),
  intent_top_signal: text("intent_top_signal"), // JSON of strongest current signal

  // Common Crawl / last-seen metadata
  last_seen_crawl_id: text("last_seen_crawl_id"),
  last_seen_capture_timestamp: text("last_seen_capture_timestamp"),
  last_seen_source_url: text("last_seen_source_url"),

  // ML embeddings & scores (added via migration 0009_blue_fantastic_four.sql)
  embedding: vector("embedding", { dimensions: 384 }),
  rank_score: real("rank_score").default(0),
  rank_score_version: text("rank_score_version"),
  anomaly_score: real("anomaly_score"),
  graph_embedding: text("graph_embedding"),

  created_at: text("created_at")
    .notNull()
    .default(sql`now()::text`),
  updated_at: text("updated_at")
    .notNull()
    .default(sql`now()::text`),
}, (table) => ({
  createdAtIdx: index("idx_companies_created_at").on(table.created_at),
  updatedAtIdx: index("idx_companies_updated_at").on(table.updated_at),
}));

export type Company = typeof companies.$inferSelect;
export type NewCompany = typeof companies.$inferInsert;

export const userSettings = pgTable("user_settings", {
  id: serial("id").primaryKey(),
  user_id: text("user_id").notNull().unique(), // Better Auth user ID
  email_notifications: boolean("email_notifications")
    .notNull()
    .default(true),
  daily_digest: boolean("daily_digest")
    .notNull()
    .default(false),
  excluded_companies: text("excluded_companies"), // JSON array
  dark_mode: boolean("dark_mode")
    .notNull()
    .default(true),
  created_at: text("created_at")
    .notNull()
    .default(sql`now()::text`),
  updated_at: text("updated_at")
    .notNull()
    .default(sql`now()::text`),
});

export type UserSettings = typeof userSettings.$inferSelect;
export type NewUserSettings = typeof userSettings.$inferInsert;

// Company Facts (MDM/Evidence-based)
export const companyFacts = pgTable(
  "company_facts",
  {
    id: serial("id").primaryKey(),
    company_id: integer("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    field: text("field").notNull(), // e.g., "name", "services", "industries"
    value_json: text("value_json"), // JSON for arrays/objects
    value_text: text("value_text"), // convenience text
    normalized_value: text("normalized_value"), // JSON normalized form
    confidence: real("confidence").notNull(), // 0..1

    // Evidence/Provenance
    source_type: text("source_type", {
      enum: ["COMMONCRAWL", "LIVE_FETCH", "MANUAL", "PARTNER", "BRAVE_SEARCH"],
    }).notNull(),
    source_url: text("source_url").notNull(),
    crawl_id: text("crawl_id"),
    capture_timestamp: text("capture_timestamp"), // YYYYMMDDhhmmss
    observed_at: text("observed_at").notNull(),
    method: text("method", {
      enum: ["JSONLD", "META", "DOM", "HEURISTIC", "LLM"],
    }).notNull(),
    extractor_version: text("extractor_version"),
    http_status: integer("http_status"),
    mime: text("mime"),
    content_hash: text("content_hash"),

    // WARC pointer
    warc_filename: text("warc_filename"),
    warc_offset: integer("warc_offset"),
    warc_length: integer("warc_length"),
    warc_digest: text("warc_digest"),

    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_company_facts_company_field").on(table.company_id, table.field),
  ],
);

export type CompanyFact = typeof companyFacts.$inferSelect;
export type NewCompanyFact = typeof companyFacts.$inferInsert;

// Company Snapshots (Crawl storage for debugging/reprocessing)
export const companySnapshots = pgTable(
  "company_snapshots",
  {
    id: serial("id").primaryKey(),
    company_id: integer("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),

    source_url: text("source_url").notNull(),
    crawl_id: text("crawl_id"),
    capture_timestamp: text("capture_timestamp"),
    fetched_at: text("fetched_at").notNull(),

    http_status: integer("http_status"),
    mime: text("mime"),
    content_hash: text("content_hash"),

    text_sample: text("text_sample"), // First N chars
    jsonld: text("jsonld"), // JSON parsed JSON-LD
    extracted: text("extracted"), // JSON extractor output

    // Evidence
    source_type: text("source_type", {
      enum: ["COMMONCRAWL", "LIVE_FETCH", "MANUAL", "PARTNER", "BRAVE_SEARCH"],
    }).notNull(),
    method: text("method", {
      enum: ["JSONLD", "META", "DOM", "HEURISTIC", "LLM"],
    }).notNull(),
    extractor_version: text("extractor_version"),

    // WARC pointer
    warc_filename: text("warc_filename"),
    warc_offset: integer("warc_offset"),
    warc_length: integer("warc_length"),
    warc_digest: text("warc_digest"),

    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_company_snapshots_company_hash").on(table.company_id, table.content_hash),
  ],
);

export type CompanySnapshot = typeof companySnapshots.$inferSelect;
export type NewCompanySnapshot = typeof companySnapshots.$inferInsert;

// Contacts (from CRM — recruiters and company contacts)
export const contacts = pgTable(
  "contacts",
  {
    id: serial("id").primaryKey(),
    slug: text("slug"),
    first_name: text("first_name").notNull(),
    last_name: text("last_name").notNull(),
    linkedin_url: text("linkedin_url"),
    email: text("email"),
    emails: text("emails"), // JSON array
    company: text("company"),
    company_id: integer("company_id").references(() => companies.id, {
      onDelete: "set null",
    }),
    position: text("position"),
    user_id: text("user_id"),
    nb_status: text("nb_status"),
    nb_result: text("nb_result"),
    nb_flags: text("nb_flags"), // JSON array
    nb_suggested_correction: text("nb_suggested_correction"),
    nb_retry_token: text("nb_retry_token"),
    nb_execution_time_ms: integer("nb_execution_time_ms"),
    email_verified: boolean("email_verified").default(false),
    bounced_emails: text("bounced_emails"), // JSON array of known-bad email addresses
    github_handle: text("github_handle"),
    telegram_handle: text("telegram_handle"),
    do_not_contact: boolean("do_not_contact").default(false),
    tags: text("tags"), // JSON array
    // Cloudflare email routing: `{alias}@vadim.blog` forwards to contact.email
    forwarding_alias: text("forwarding_alias"),
    forwarding_alias_rule_id: text("forwarding_alias_rule_id"),
    // ML-derived fields (populated by classifyContact / scoreContactsML)
    seniority: text("seniority"),
    department: text("department"),
    is_decision_maker: boolean("is_decision_maker").default(false),
    authority_score: real("authority_score").default(0.0),
    dm_reasons: text("dm_reasons"), // JSON array
    // ML touch score (computed by computeNextTouchScores / scoreContactsML)
    next_touch_score: real("next_touch_score").default(0.0),
    last_contacted_at: text("last_contacted_at"),
    ai_profile: text("ai_profile"), // JSON: ContactAIProfile blob (set by enrichAIContactProfile mutation)
    // ML deletion scoring (computed by computeContactDeletionScores)
    to_be_deleted: boolean("to_be_deleted").notNull().default(false),
    deletion_score: real("deletion_score"),
    deletion_reasons: text("deletion_reasons"), // JSON array of reason strings
    deletion_flagged_at: text("deletion_flagged_at"),
    // Conversation lifecycle state (updated by webhook handler on reply classification)
    conversation_stage: text("conversation_stage"), // initial_sent | follow_up_1 | follow_up_2 | follow_up_3 | replied_interested | replied_info_request | replied_not_interested | meeting_scheduled | converted | closed
    // Fake account detection (populated by verifyContactAuthenticity mutation)
    authenticity_score: real("authenticity_score"),
    authenticity_verdict: text("authenticity_verdict"),
    authenticity_flags: text("authenticity_flags"), // JSON array
    verified_at: text("verified_at"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    slugIdx: uniqueIndex("idx_contacts_slug").on(table.slug),
    emailIdx: uniqueIndex("idx_contacts_email").on(table.email),
    companyIdIdx: index("idx_contacts_company_id").on(table.company_id),
    linkedinUrlIdx: index("idx_contacts_linkedin_url").on(table.linkedin_url),
    githubHandleIdx: uniqueIndex("idx_contacts_github_handle")
      .on(table.github_handle)
      .where(sql`github_handle IS NOT NULL`),
  }),
);

export type Contact = typeof contacts.$inferSelect;
export type NewContact = typeof contacts.$inferInsert;

// Contact Reminders (explicit dated reminders per contact)
export const reminders = pgTable(
  "reminders",
  {
    id: serial("id").primaryKey(),
    entity_type: text("entity_type").notNull(), // contact | company | ...
    entity_id: integer("entity_id").notNull(),
    remind_at: text("remind_at").notNull(),
    recurrence: text("recurrence").notNull().default("none"), // none | weekly | biweekly | monthly
    note: text("note"),
    status: text("status").notNull().default("pending"), // pending | snoozed | done
    snoozed_until: text("snoozed_until"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    entityIdx: index("idx_reminders_entity").on(table.entity_type, table.entity_id),
    remindAtIdx: index("idx_reminders_remind_at").on(table.remind_at),
    statusIdx: index("idx_reminders_status").on(table.status),
  }),
);

export type Reminder = typeof reminders.$inferSelect;
export type NewReminder = typeof reminders.$inferInsert;

// Contact Emails (outbound emails sent to a contact)
export const contactEmails = pgTable(
  "contact_emails",
  {
    id: serial("id").primaryKey(),
    contact_id: integer("contact_id")
      .notNull()
      .references(() => contacts.id, { onDelete: "cascade" }),
    resend_id: text("resend_id").notNull(),
    from_email: text("from_email").notNull(),
    to_emails: text("to_emails").notNull(), // JSON array
    subject: text("subject").notNull(),
    text_content: text("text_content"),
    status: text("status").notNull().default("sent"),
    sent_at: text("sent_at"),
    scheduled_at: text("scheduled_at"),
    delivered_at: text("delivered_at"),
    opened_at: text("opened_at"),
    recipient_name: text("recipient_name"),
    error_message: text("error_message"),
    // Follow-up sequence tracking
    parent_email_id: integer("parent_email_id"),
    sequence_type: text("sequence_type"), // "initial" | "followup_1" | "followup_2" | "followup_3"
    sequence_number: text("sequence_number"), // "0", "1", "2", "3"
    reply_received: boolean("reply_received").default(false),
    reply_received_at: text("reply_received_at"),
    followup_status: text("followup_status"), // "pending" | "completed"
    // Entity linking (for non-contact emails like company batches)
    company_id: integer("company_id").references(() => companies.id, { onDelete: "set null" }),
    // Extended fields (ported from CRM)
    cc_emails: text("cc_emails").default("[]"), // JSON array
    reply_to_emails: text("reply_to_emails").default("[]"), // JSON array
    html_content: text("html_content"),
    attachments: text("attachments").default("[]"), // JSON array
    tags: text("tags").default("[]"), // JSON array
    headers: text("headers").default("[]"), // JSON array
    idempotency_key: text("idempotency_key"),
    // Reply classification (populated when a received email is matched to this outbound)
    reply_classification: text("reply_classification"), // interested | not_interested | auto_reply | bounced | info_request | unsubscribe
    // Link to the received email this outbound is replying to
    in_reply_to_received_id: integer("in_reply_to_received_id")
      .references((): AnyPgColumn => receivedEmails.id, { onDelete: "set null" }),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    contactIdIdx: index("idx_contact_emails_contact_id").on(table.contact_id),
    resendIdIdx: index("idx_contact_emails_resend_id").on(table.resend_id),
    statusIdx: index("idx_contact_emails_status").on(table.status),
    companyIdIdx: index("idx_contact_emails_company_id").on(table.company_id),
    parentEmailIdIdx: index("idx_contact_emails_parent_email_id").on(table.parent_email_id),
    inReplyToReceivedIdx: index("idx_contact_emails_in_reply_to_received").on(table.in_reply_to_received_id),
  }),
);

export type ContactEmail = typeof contactEmails.$inferSelect;
export type NewContactEmail = typeof contactEmails.$inferInsert;


// Email Campaigns (CRM — automated email sequences)
export const emailCampaigns = pgTable(
  "email_campaigns",
  {
    id: text("id").primaryKey(), // campaign_<timestamp>_<random>
    company_id: integer("company_id").references(() => companies.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    status: text("status", {
      enum: ["draft", "pending", "running", "completed", "failed", "stopped"],
    }).notNull().default("draft"),
    sequence: text("sequence"), // JSON array of email steps
    delay_days: text("delay_days"), // JSON array of delays between steps
    start_at: text("start_at"),
    mode: text("mode"), // "sequential" | "blast"
    from_email: text("from_email"),
    reply_to: text("reply_to"),
    total_recipients: integer("total_recipients").notNull().default(0),
    emails_sent: integer("emails_sent").notNull().default(0),
    emails_scheduled: integer("emails_scheduled").notNull().default(0),
    emails_failed: integer("emails_failed").notNull().default(0),
    recipient_emails: text("recipient_emails"), // JSON array
    // Extended fields (ported from CRM)
    total_emails_planned: integer("total_emails_planned"),
    add_unsubscribe_headers: integer("add_unsubscribe_headers").notNull().default(0),
    unsubscribe_url: text("unsubscribe_url"),
    add_anti_thread_header: integer("add_anti_thread_header").notNull().default(0),
    created_by: text("created_by"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    companyIdIdx: index("idx_email_campaigns_company_id").on(table.company_id),
    statusIdx: index("idx_email_campaigns_status").on(table.status),
  }),
);

export type EmailCampaign = typeof emailCampaigns.$inferSelect;
export type NewEmailCampaign = typeof emailCampaigns.$inferInsert;

// Email Templates (CRM — reusable email templates)
export const emailTemplates = pgTable(
  "email_templates",
  {
    id: serial("id").primaryKey(),
    name: text("name").notNull(),
    description: text("description"),
    subject: text("subject"),
    html_content: text("html_content"),
    text_content: text("text_content"),
    category: text("category"),
    tags: text("tags"), // JSON array
    variables: text("variables"), // JSON array of variable names
    is_active: boolean("is_active").notNull().default(true),
    user_id: text("user_id"), // Template owner
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    categoryIdx: index("idx_email_templates_category").on(table.category),
  }),
);

export type EmailTemplate = typeof emailTemplates.$inferSelect;
export type NewEmailTemplate = typeof emailTemplates.$inferInsert;

// Received Emails (inbound emails persisted from Resend webhooks)
export const receivedEmails = pgTable(
  "received_emails",
  {
    id: serial("id").primaryKey(),
    resend_id: text("resend_id").unique(),
    source: text("source").notNull().default("email"), // email | linkedin_dm
    from_email: text("from_email"),
    to_emails: text("to_emails").notNull().default("[]"), // JSON array
    cc_emails: text("cc_emails").default("[]"), // JSON array
    reply_to_emails: text("reply_to_emails").default("[]"), // JSON array
    subject: text("subject"),
    message_id: text("message_id"),
    html_content: text("html_content"),
    text_content: text("text_content"),
    attachments: text("attachments").default("[]"), // JSON array
    received_at: text("received_at").notNull(),
    archived_at: text("archived_at"),
    // Reply classification (ML — logistic regression)
    classification: text("classification"), // interested | not_interested | auto_reply | bounced | info_request | unsubscribe
    classification_confidence: real("classification_confidence"),
    classified_at: text("classified_at"),
    // Contact matching
    matched_contact_id: integer("matched_contact_id").references(() => contacts.id, { onDelete: "set null" }),
    matched_outbound_id: integer("matched_outbound_id").references(
      (): AnyPgColumn => contactEmails.id,
      { onDelete: "set null" },
    ),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    fromEmailIdx: index("idx_received_emails_from").on(table.from_email),
    messageIdIdx: index("idx_received_emails_message_id").on(table.message_id),
    receivedAtIdx: index("idx_received_emails_received_at").on(table.received_at),
    resendIdIdx: index("idx_received_emails_resend_id").on(table.resend_id),
    classificationIdx: index("idx_received_emails_classification").on(table.classification),
  }),
);

export type ReceivedEmail = typeof receivedEmails.$inferSelect;
export type NewReceivedEmail = typeof receivedEmails.$inferInsert;

// LinkedIn Posts (unified table for posts and job listings — jobs have type='job')
export const linkedinPosts = pgTable(
  "linkedin_posts",
  {
    id: serial("id").primaryKey(),
    type: text("type", { enum: ["post", "job"] }).notNull().default("post"),
    url: text("url").notNull(),           // LinkedIn canonical URL (unique)

    company_id: integer("company_id").references(() => companies.id, { onDelete: "set null" }),
    contact_id: integer("contact_id").references(() => contacts.id, { onDelete: "set null" }),

    title: text("title"),                 // job title or post headline
    content: text("content"),            // full post text or job description
    author_name: text("author_name"),    // display name
    author_url: text("author_url"),      // author LinkedIn profile URL

    location: text("location"),          // job: location string
    employment_type: text("employment_type"), // job: full-time / contract / etc.

    posted_at: text("posted_at"),        // when posted on LinkedIn (ISO)
    scraped_at: text("scraped_at").notNull().default(sql`now()::text`),

    raw_data: text("raw_data"),          // JSON blob for anything extra

    // TechWolf model analysis (JobBERT-v2 + ConTeXT skill extraction)
    skills: text("skills"),              // JSON array of ExtractedSkill[]
    analyzed_at: text("analyzed_at"),    // ISO timestamp of last TechWolf analysis
    // job_embedding vector(768) added via migration — accessed with raw SQL

    // --- Voyager API fields ---
    voyager_urn: text("voyager_urn"),                       // LinkedIn URN e.g. urn:li:fsd_jobPosting:12345
    voyager_workplace_type: text("voyager_workplace_type"), // "remote" | "hybrid" | "on-site"
    voyager_salary_min: integer("voyager_salary_min"),
    voyager_salary_max: integer("voyager_salary_max"),
    voyager_salary_currency: text("voyager_salary_currency"), // ISO 4217: "USD", "EUR", etc.
    voyager_apply_url: text("voyager_apply_url"),            // external apply URL
    voyager_poster_urn: text("voyager_poster_urn"),          // URN of the person who posted
    voyager_listed_at: text("voyager_listed_at"),            // epoch ms or ISO when LinkedIn listed it
    voyager_reposted: boolean("voyager_reposted").default(false),

    created_at: text("created_at").notNull().default(sql`now()::text`),
  },
  (table) => [
    uniqueIndex("idx_linkedin_posts_url").on(table.url),
    index("idx_linkedin_posts_type").on(table.type),
    index("idx_linkedin_posts_company_id").on(table.company_id),
    index("idx_linkedin_posts_contact_id").on(table.contact_id),
    uniqueIndex("idx_linkedin_posts_voyager_urn").on(table.voyager_urn),
    index("idx_linkedin_posts_workplace_type").on(table.voyager_workplace_type),
  ],
);

export type LinkedInPost = typeof linkedinPosts.$inferSelect;
export type NewLinkedInPost = typeof linkedinPosts.$inferInsert;

// Opportunities (job listings / contracts tracked for application pipeline)
export const opportunities = pgTable(
  "opportunities",
  {
    id: text("id").primaryKey(), // opp_<timestamp>_<random>
    title: text("title").notNull(),
    url: text("url"),
    source: text("source"), // linkedin | website | referral | etc.
    status: text("status").notNull().default("open"), // open | applied | interviewing | offer | rejected | closed
    reward_usd: real("reward_usd"),
    reward_text: text("reward_text"), // human-readable comp (e.g. "€130k + bonus")
    start_date: text("start_date"),
    end_date: text("end_date"),
    deadline: text("deadline"),
    first_seen: text("first_seen"),
    last_seen: text("last_seen"),
    score: integer("score"), // 0-100 fit score
    raw_context: text("raw_context"), // full job description text
    metadata: text("metadata"), // JSON blob for extra structured data
    applied: boolean("applied").notNull().default(false),
    applied_at: text("applied_at"),
    application_status: text("application_status"),
    application_notes: text("application_notes"),
    tags: text("tags"), // JSON array
    company_id: integer("company_id").references(() => companies.id, { onDelete: "set null" }),
    contact_id: integer("contact_id").references(() => contacts.id, { onDelete: "set null" }),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    companyIdIdx: index("idx_opportunities_company_id").on(table.company_id),
    contactIdIdx: index("idx_opportunities_contact_id").on(table.contact_id),
    statusIdx: index("idx_opportunities_status").on(table.status),
  }),
);

export type Opportunity = typeof opportunities.$inferSelect;
export type NewOpportunity = typeof opportunities.$inferInsert;

// Intent Signals (company-level buying/hiring signals detected by finetuned Qwen)
export const intentSignals = pgTable(
  "intent_signals",
  {
    id: serial("id").primaryKey(),
    company_id: integer("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    signal_type: text("signal_type", {
      enum: [
        "hiring_intent",
        "tech_adoption",
        "growth_signal",
        "budget_cycle",
        "leadership_change",
        "product_launch",
      ],
    }).notNull(),
    source_type: text("source_type", {
      enum: [
        "job_posting",
        "web_content",
        "github_activity",
        "linkedin_post",
        "funding_event",
        "press_release",
        "company_snapshot",
      ],
    }).notNull(),
    source_url: text("source_url"),
    raw_text: text("raw_text").notNull(), // snippet that triggered detection
    evidence: text("evidence"), // JSON array of extracted evidence phrases
    confidence: real("confidence").notNull(), // 0..1
    detected_at: text("detected_at").notNull(), // ISO timestamp
    decays_at: text("decays_at").notNull(), // ISO timestamp = detected_at + decay_days
    decay_days: integer("decay_days").notNull(), // half-life for exponential decay
    metadata: text("metadata"), // JSON blob for signal-specific data
    model_version: text("model_version"), // adapter version or "logistic-v1"
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_intent_signals_company_type").on(table.company_id, table.signal_type),
    index("idx_intent_signals_company_detected").on(table.company_id, table.detected_at),
    index("idx_intent_signals_decays_at").on(table.decays_at),
  ],
);

export type IntentSignal = typeof intentSignals.$inferSelect;
export type NewIntentSignal = typeof intentSignals.$inferInsert;

// Voyager Job Counts (remote job count snapshots per company/query over time)
export const voyagerJobCounts = pgTable(
  "voyager_job_counts",
  {
    id: serial("id").primaryKey(),
    company_id: integer("company_id")
      .references(() => companies.id, { onDelete: "cascade" }),
    query: text("query").notNull(),               // search query used, e.g. "AI engineer remote"
    remote_count: integer("remote_count").notNull().default(0),
    total_count: integer("total_count").notNull().default(0),
    counted_at: text("counted_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_voyager_job_counts_company_id").on(table.company_id),
    index("idx_voyager_job_counts_query").on(table.query),
    index("idx_voyager_job_counts_counted_at").on(table.counted_at),
    index("idx_voyager_job_counts_company_query").on(table.company_id, table.query),
  ],
);

export type VoyagerJobCount = typeof voyagerJobCounts.$inferSelect;
export type NewVoyagerJobCount = typeof voyagerJobCounts.$inferInsert;

// Voyager Sessions (LinkedIn API session management — cookies + health tracking)
export const voyagerSessions = pgTable(
  "voyager_sessions",
  {
    id: serial("id").primaryKey(),
    session_id: text("session_id").notNull().unique(), // opaque identifier
    li_at: text("li_at").notNull(),                    // LinkedIn li_at cookie
    jsessionid: text("jsessionid").notNull(),          // JSESSIONID cookie
    csrf_token: text("csrf_token").notNull(),          // CSRF token
    user_agent: text("user_agent").notNull(),
    last_used: text("last_used")
      .notNull()
      .default(sql`now()::text`),
    request_count: integer("request_count").notNull().default(0),
    is_healthy: boolean("is_healthy").notNull().default(true),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_voyager_sessions_is_healthy").on(table.is_healthy),
    index("idx_voyager_sessions_last_used").on(table.last_used),
  ],
);

export type VoyagerSession = typeof voyagerSessions.$inferSelect;
export type NewVoyagerSession = typeof voyagerSessions.$inferInsert;

// Voyager Sync Log (tracks each sync operation — query, counts, timing, errors)
export const voyagerSyncLog = pgTable(
  "voyager_sync_log",
  {
    id: serial("id").primaryKey(),
    sync_id: text("sync_id").notNull().unique(),    // e.g. sync_<timestamp>_<random>
    query: text("query").notNull(),                  // search query used
    jobs_found: integer("jobs_found").notNull().default(0),
    jobs_new: integer("jobs_new").notNull().default(0),
    jobs_updated: integer("jobs_updated").notNull().default(0),
    started_at: text("started_at").notNull(),
    completed_at: text("completed_at"),
    errors: text("errors"),                          // JSON array of error strings
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_voyager_sync_log_started_at").on(table.started_at),
    index("idx_voyager_sync_log_query").on(table.query),
  ],
);

export type VoyagerSyncLog = typeof voyagerSyncLog.$inferSelect;
export type NewVoyagerSyncLog = typeof voyagerSyncLog.$inferInsert;

// Voyager Analytics Snapshots (daily aggregated market intelligence)
export const voyagerSnapshots = pgTable(
  "voyager_snapshots",
  {
    id: serial("id").primaryKey(),

    // Snapshot identity
    snapshot_date: text("snapshot_date").notNull(),  // YYYY-MM-DD
    query: text("query").notNull(),                  // search query / keyword

    // Core counts
    total_jobs: integer("total_jobs").notNull().default(0),
    remote_jobs: integer("remote_jobs").notNull().default(0),
    new_jobs_24h: integer("new_jobs_24h").notNull().default(0),
    reposted_jobs: integer("reposted_jobs").notNull().default(0),

    // Aggregated metrics (JSON)
    top_companies: text("top_companies"),             // JSON: { name, count, velocity }[]
    top_skills: text("top_skills"),                   // JSON: { skill, count, pctOfTotal }[]
    salary_data: text("salary_data"),                 // JSON: { min, max, median, currency, count }
    location_breakdown: text("location_breakdown"),   // JSON: { location, count, avgSalary? }[]
    industry_breakdown: text("industry_breakdown"),   // JSON: { industry, count, growthRate? }[]
    employment_types: text("employment_types"),       // JSON: { type, count }[]
    emerging_titles: text("emerging_titles"),         // JSON: { title, count, isNew }[]
    repost_analysis: text("repost_analysis"),         // JSON: { jobUrl, repostCount, daysSinceFirst }[]
    time_to_fill: text("time_to_fill"),              // JSON: { avgDays, medianDays, byIndustry }

    // Raw Voyager response metadata
    voyager_request_id: text("voyager_request_id"),
    raw_metadata: text("raw_metadata"),              // JSON blob for debugging

    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    uniqueIndex("idx_voyager_snapshots_date_query").on(table.snapshot_date, table.query),
    index("idx_voyager_snapshots_date").on(table.snapshot_date),
  ],
);

export type VoyagerSnapshot = typeof voyagerSnapshots.$inferSelect;
export type NewVoyagerSnapshot = typeof voyagerSnapshots.$inferInsert;

// ---------------------------------------------------------------------------
// Drizzle relations() declarations
// ---------------------------------------------------------------------------

export const companiesRelations = relations(companies, ({ many }) => ({
  companyFacts: many(companyFacts),
  companySnapshots: many(companySnapshots),
  contacts: many(contacts),
  emailCampaigns: many(emailCampaigns),
  linkedinPosts: many(linkedinPosts),
  intentSignals: many(intentSignals),
  voyagerJobCounts: many(voyagerJobCounts),
}));

export const companyFactsRelations = relations(companyFacts, ({ one }) => ({
  company: one(companies, {
    fields: [companyFacts.company_id],
    references: [companies.id],
  }),
}));

export const companySnapshotsRelations = relations(companySnapshots, ({ one }) => ({
  company: one(companies, {
    fields: [companySnapshots.company_id],
    references: [companies.id],
  }),
}));

export const contactsRelations = relations(contacts, ({ one, many }) => ({
  company: one(companies, {
    fields: [contacts.company_id],
    references: [companies.id],
  }),
  emails: many(contactEmails),
  linkedinPosts: many(linkedinPosts),
}));

export const contactEmailsRelations = relations(contactEmails, ({ one }) => ({
  contact: one(contacts, {
    fields: [contactEmails.contact_id],
    references: [contacts.id],
  }),
}));

export const emailCampaignsRelations = relations(emailCampaigns, ({ one }) => ({
  company: one(companies, {
    fields: [emailCampaigns.company_id],
    references: [companies.id],
  }),
}));

export const intentSignalsRelations = relations(intentSignals, ({ one }) => ({
  company: one(companies, {
    fields: [intentSignals.company_id],
    references: [companies.id],
  }),
}));

export const linkedinPostsRelations = relations(linkedinPosts, ({ one }) => ({
  company: one(companies, {
    fields: [linkedinPosts.company_id],
    references: [companies.id],
  }),
  contact: one(contacts, {
    fields: [linkedinPosts.contact_id],
    references: [contacts.id],
  }),
}));

export const voyagerJobCountsRelations = relations(voyagerJobCounts, ({ one }) => ({
  company: one(companies, {
    fields: [voyagerJobCounts.company_id],
    references: [companies.id],
  }),
}));

export const voyagerSnapshotsRelations = relations(voyagerSnapshots, () => ({}));

// Reply Drafts (auto-generated reply drafts for user approval)
export const replyDrafts = pgTable(
  "reply_drafts",
  {
    id: serial("id").primaryKey(),
    received_email_id: integer("received_email_id")
      .notNull()
      .references(() => receivedEmails.id, { onDelete: "cascade" }),
    contact_id: integer("contact_id")
      .notNull()
      .references(() => contacts.id, { onDelete: "cascade" }),
    status: text("status", {
      enum: ["pending", "approved", "sent", "dismissed"],
    }).notNull().default("pending"),
    draft_type: text("draft_type", {
      enum: ["reply", "follow_up"],
    }).notNull().default("reply"),
    subject: text("subject").notNull(),
    body_text: text("body_text").notNull(),
    body_html: text("body_html"),
    generation_model: text("generation_model"),
    thread_context: text("thread_context"), // JSON of the conversation thread used for generation
    approved_at: text("approved_at"),
    sent_at: text("sent_at"),
    sent_resend_id: text("sent_resend_id"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    receivedEmailIdIdx: index("idx_reply_drafts_received_email_id").on(table.received_email_id),
    contactIdIdx: index("idx_reply_drafts_contact_id").on(table.contact_id),
    statusIdx: index("idx_reply_drafts_status").on(table.status),
  }),
);

export type ReplyDraft = typeof replyDrafts.$inferSelect;
export type NewReplyDraft = typeof replyDrafts.$inferInsert;

export const replyDraftsRelations = relations(replyDrafts, ({ one }) => ({
  receivedEmail: one(receivedEmails, {
    fields: [replyDrafts.received_email_id],
    references: [receivedEmails.id],
  }),
  contact: one(contacts, {
    fields: [replyDrafts.contact_id],
    references: [contacts.id],
  }),
}));

// Messages (LinkedIn DMs, other non-email touchpoints)
export const messages = pgTable(
  "messages",
  {
    id: serial("id").primaryKey(),
    channel: text("channel").notNull(), // "linkedin" | "telegram" | "whatsapp" | "other"
    direction: text("direction").notNull(), // "inbound" | "outbound"
    contact_id: integer("contact_id").references(() => contacts.id, { onDelete: "cascade" }),
    company_id: integer("company_id").references(() => companies.id, { onDelete: "set null" }),
    // Link to outbound email that triggered this conversation
    contact_email_id: integer("contact_email_id").references(() => contactEmails.id, { onDelete: "set null" }),
    sender_name: text("sender_name"),
    sender_profile_url: text("sender_profile_url"),
    content: text("content"),
    subject: text("subject"), // optional — thread topic or first line
    sent_at: text("sent_at").notNull(),
    // Classification (same enum as received_emails)
    classification: text("classification"), // interested | not_interested | auto_reply | info_request
    classification_confidence: real("classification_confidence"),
    raw_data: text("raw_data"), // JSON blob for extra metadata
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    contactIdIdx: index("idx_messages_contact_id").on(table.contact_id),
    companyIdIdx: index("idx_messages_company_id").on(table.company_id),
    contactEmailIdIdx: index("idx_messages_contact_email_id").on(table.contact_email_id),
    channelIdx: index("idx_messages_channel").on(table.channel),
    directionIdx: index("idx_messages_direction").on(table.direction),
    sentAtIdx: index("idx_messages_sent_at").on(table.sent_at),
  }),
);

export type Message = typeof messages.$inferSelect;
export type NewMessage = typeof messages.$inferInsert;

export const messagesRelations = relations(messages, ({ one }) => ({
  contact: one(contacts, {
    fields: [messages.contact_id],
    references: [contacts.id],
  }),
  company: one(companies, {
    fields: [messages.company_id],
    references: [companies.id],
  }),
  contactEmail: one(contactEmails, {
    fields: [messages.contact_email_id],
    references: [contactEmails.id],
  }),
}));

// ── Crawl Logs (persisted BFS crawl traces from Chrome extension) ──

export const crawlLogs = pgTable("crawl_logs", {
  id: serial("id").primaryKey(),
  seed_url: text("seed_url").notNull(),
  company_slug: text("company_slug").notNull(),
  status: text("status", {
    enum: ["running", "completed", "cancelled", "error"],
  }).notNull().default("running"),
  saved: integer("saved").notNull().default(0),
  skipped: integer("skipped").notNull().default(0),
  filtered: integer("filtered").notNull().default(0),
  targets: integer("targets").notNull().default(0),
  visited: integer("visited").notNull().default(0),
  total_remote_jobs: integer("total_remote_jobs").notNull().default(0),
  duration_ms: integer("duration_ms").notNull().default(0),
  entries: text("entries"),             // JSON stringified string[]
  error: text("error"),
  started_at: text("started_at").notNull(),
  completed_at: text("completed_at"),
  created_at: text("created_at")
    .notNull()
    .default(sql`now()::text`),
}, (table) => [
  index("idx_crawl_logs_seed_url").on(table.seed_url),
  index("idx_crawl_logs_started_at").on(table.started_at),
  index("idx_crawl_logs_status").on(table.status),
]);

export type CrawlLog = typeof crawlLogs.$inferSelect;
export type NewCrawlLog = typeof crawlLogs.$inferInsert;

// ── Webhook Events (Resend webhook event log) ──

export const webhookEvents = pgTable("webhook_events", {
  id: serial("id").primaryKey(),
  event_type: text("event_type").notNull(),
  email_id: text("email_id"),
  from_email: text("from_email"),
  to_emails: text("to_emails"),
  subject: text("subject"),
  payload: text("payload"),
  http_status: integer("http_status"),
  error: text("error"),
  created_at: text("created_at")
    .notNull()
    .default(sql`now()::text`),
}, (table) => [
  index("idx_webhook_events_event_type").on(table.event_type),
  index("idx_webhook_events_email_id").on(table.email_id),
  index("idx_webhook_events_created_at").on(table.created_at),
]);

export type WebhookEvent = typeof webhookEvents.$inferSelect;
export type NewWebhookEvent = typeof webhookEvents.$inferInsert;

// ── Competitor Analysis ──

export const competitorAnalyses = pgTable(
  "competitor_analyses",
  {
    id: serial("id").primaryKey(),
    seed_product_name: text("seed_product_name").notNull(),
    seed_product_url: text("seed_product_url").notNull(),
    status: text("status", {
      enum: ["pending_approval", "scraping", "done", "failed"],
    }).notNull().default("pending_approval"),
    created_by: text("created_by"),
    error: text("error"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_competitor_analyses_status").on(table.status),
    index("idx_competitor_analyses_created_at").on(table.created_at),
  ],
);

export type CompetitorAnalysis = typeof competitorAnalyses.$inferSelect;
export type NewCompetitorAnalysis = typeof competitorAnalyses.$inferInsert;

export const competitors = pgTable(
  "competitors",
  {
    id: serial("id").primaryKey(),
    analysis_id: integer("analysis_id")
      .notNull()
      .references(() => competitorAnalyses.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    url: text("url").notNull(),
    domain: text("domain"),
    logo_url: text("logo_url"),
    description: text("description"),
    positioning_headline: text("positioning_headline"),
    positioning_tagline: text("positioning_tagline"),
    target_audience: text("target_audience"),
    status: text("status", {
      enum: ["suggested", "approved", "scraping", "done", "failed"],
    }).notNull().default("suggested"),
    scraped_at: text("scraped_at"),
    scrape_error: text("scrape_error"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_competitors_analysis_id").on(table.analysis_id),
    index("idx_competitors_status").on(table.status),
  ],
);

export type Competitor = typeof competitors.$inferSelect;
export type NewCompetitor = typeof competitors.$inferInsert;

export const competitorPricingTiers = pgTable(
  "competitor_pricing_tiers",
  {
    id: serial("id").primaryKey(),
    competitor_id: integer("competitor_id")
      .notNull()
      .references(() => competitors.id, { onDelete: "cascade" }),
    tier_name: text("tier_name").notNull(),
    monthly_price_usd: real("monthly_price_usd"),
    annual_price_usd: real("annual_price_usd"),
    seat_price_usd: real("seat_price_usd"),
    currency: text("currency").notNull().default("USD"),
    included_limits: jsonb("included_limits"),
    is_custom_quote: boolean("is_custom_quote").notNull().default(false),
    sort_order: integer("sort_order").notNull().default(0),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_competitor_pricing_tiers_competitor_id").on(table.competitor_id),
  ],
);

export type CompetitorPricingTier = typeof competitorPricingTiers.$inferSelect;
export type NewCompetitorPricingTier = typeof competitorPricingTiers.$inferInsert;

export const competitorFeatures = pgTable(
  "competitor_features",
  {
    id: serial("id").primaryKey(),
    competitor_id: integer("competitor_id")
      .notNull()
      .references(() => competitors.id, { onDelete: "cascade" }),
    tier_name: text("tier_name"),
    feature_text: text("feature_text").notNull(),
    category: text("category"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_competitor_features_competitor_id").on(table.competitor_id),
    index("idx_competitor_features_category").on(table.category),
  ],
);

export type CompetitorFeature = typeof competitorFeatures.$inferSelect;
export type NewCompetitorFeature = typeof competitorFeatures.$inferInsert;

export const competitorIntegrations = pgTable(
  "competitor_integrations",
  {
    id: serial("id").primaryKey(),
    competitor_id: integer("competitor_id")
      .notNull()
      .references(() => competitors.id, { onDelete: "cascade" }),
    integration_name: text("integration_name").notNull(),
    integration_url: text("integration_url"),
    category: text("category"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_competitor_integrations_competitor_id").on(table.competitor_id),
  ],
);

export type CompetitorIntegration = typeof competitorIntegrations.$inferSelect;
export type NewCompetitorIntegration = typeof competitorIntegrations.$inferInsert;

export const competitorAnalysesRelations = relations(competitorAnalyses, ({ many }) => ({
  competitors: many(competitors),
}));

export const competitorsRelations = relations(competitors, ({ one, many }) => ({
  analysis: one(competitorAnalyses, {
    fields: [competitors.analysis_id],
    references: [competitorAnalyses.id],
  }),
  pricingTiers: many(competitorPricingTiers),
  features: many(competitorFeatures),
  integrations: many(competitorIntegrations),
}));

export const competitorPricingTiersRelations = relations(competitorPricingTiers, ({ one }) => ({
  competitor: one(competitors, {
    fields: [competitorPricingTiers.competitor_id],
    references: [competitors.id],
  }),
}));

export const competitorFeaturesRelations = relations(competitorFeatures, ({ one }) => ({
  competitor: one(competitors, {
    fields: [competitorFeatures.competitor_id],
    references: [competitors.id],
  }),
}));

export const competitorIntegrationsRelations = relations(competitorIntegrations, ({ one }) => ({
  competitor: one(competitors, {
    fields: [competitorIntegrations.competitor_id],
    references: [competitors.id],
  }),
}));
