import { pgTable, text, integer, real, index, uniqueIndex, serial, boolean } from "drizzle-orm/pg-core";
import { sql, relations } from "drizzle-orm";

// Re-export Better Auth tables (user, session, account, verification)
export { user, session, account, verification } from "@ai-apps/auth/schema";

export const companies = pgTable("companies", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(), // Unique identifier (slug/domain)
  name: text("name").notNull(),
  logo_url: text("logo_url"),
  website: text("website"),
  description: text("description"),
  industry: text("industry"),
  size: text("size"), // e.g., "1-10", "11-50", "51-200", etc.
  location: text("location"),

  // Golden record fields
  canonical_domain: text("canonical_domain"),
  category: text("category", {
    enum: [
      "CONSULTANCY",
      "UNKNOWN",
    ],
  })
    .notNull()
    .default("UNKNOWN"),
  tags: text("tags"), // JSON array
  services: text("services"), // JSON array of human-readable service phrases
  service_taxonomy: text("service_taxonomy"), // JSON array of normalized taxonomy IDs
  industries: text("industries"), // JSON array for multi-industry

  linkedin_url: text("linkedin_url"),
  job_board_url: text("job_board_url"),

  score: real("score").notNull().default(0.5), // 0..1
  score_reasons: text("score_reasons"), // JSON array

  // AI company tier: 0 = not AI, 1 = ai_first, 2 = ai_native
  ai_tier: integer("ai_tier").notNull().default(0),
  ai_classification_reason: text("ai_classification_reason"),
  ai_classification_confidence: real("ai_classification_confidence").default(0.5),

  // Pipeline blocklist: blocked companies are hidden from UI and skipped by pipeline
  blocked: boolean("blocked").notNull().default(false),

  // Deep company analysis (Markdown, generated by Browser Rendering + DeepSeek)
  deep_analysis: text("deep_analysis"),

  // CRM fields
  email: text("email"),
  emails: text("emails"), // JSON array
  github_url: text("github_url"),

  // GitHub pattern analysis (populated by github-patterns crate)
  github_org: text("github_org"),                         // extracted org login
  github_ai_score: real("github_ai_score"),               // 0..1 AI adoption
  github_hiring_score: real("github_hiring_score"),       // 0..1 hiring signals
  github_activity_score: real("github_activity_score"),   // 0..1 commit/release velocity
  github_patterns: text("github_patterns"),               // full OrgPatterns JSON
  github_analyzed_at: text("github_analyzed_at"),         // ISO timestamp of last scan

  // Common Crawl / last-seen metadata
  last_seen_crawl_id: text("last_seen_crawl_id"),
  last_seen_capture_timestamp: text("last_seen_capture_timestamp"),
  last_seen_source_url: text("last_seen_source_url"),

  created_at: text("created_at")
    .notNull()
    .default(sql`now()::text`),
  updated_at: text("updated_at")
    .notNull()
    .default(sql`now()::text`),
});

export type Company = typeof companies.$inferSelect;
export type NewCompany = typeof companies.$inferInsert;

export const userSettings = pgTable("user_settings", {
  id: serial("id").primaryKey(),
  user_id: text("user_id").notNull().unique(), // Better Auth user ID
  email_notifications: boolean("email_notifications")
    .notNull()
    .default(true),
  daily_digest: boolean("daily_digest")
    .notNull()
    .default(false),
  excluded_companies: text("excluded_companies"), // JSON array
  dark_mode: boolean("dark_mode")
    .notNull()
    .default(true),
  created_at: text("created_at")
    .notNull()
    .default(sql`now()::text`),
  updated_at: text("updated_at")
    .notNull()
    .default(sql`now()::text`),
});

export type UserSettings = typeof userSettings.$inferSelect;
export type NewUserSettings = typeof userSettings.$inferInsert;

// Company Facts (MDM/Evidence-based)
export const companyFacts = pgTable(
  "company_facts",
  {
    id: serial("id").primaryKey(),
    company_id: integer("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    field: text("field").notNull(), // e.g., "name", "services", "industries"
    value_json: text("value_json"), // JSON for arrays/objects
    value_text: text("value_text"), // convenience text
    normalized_value: text("normalized_value"), // JSON normalized form
    confidence: real("confidence").notNull(), // 0..1

    // Evidence/Provenance
    source_type: text("source_type", {
      enum: ["COMMONCRAWL", "LIVE_FETCH", "MANUAL", "PARTNER"],
    }).notNull(),
    source_url: text("source_url").notNull(),
    crawl_id: text("crawl_id"),
    capture_timestamp: text("capture_timestamp"), // YYYYMMDDhhmmss
    observed_at: text("observed_at").notNull(),
    method: text("method", {
      enum: ["JSONLD", "META", "DOM", "HEURISTIC", "LLM"],
    }).notNull(),
    extractor_version: text("extractor_version"),
    http_status: integer("http_status"),
    mime: text("mime"),
    content_hash: text("content_hash"),

    // WARC pointer
    warc_filename: text("warc_filename"),
    warc_offset: integer("warc_offset"),
    warc_length: integer("warc_length"),
    warc_digest: text("warc_digest"),

    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_company_facts_company_field").on(table.company_id, table.field),
  ],
);

export type CompanyFact = typeof companyFacts.$inferSelect;
export type NewCompanyFact = typeof companyFacts.$inferInsert;

// Company Snapshots (Crawl storage for debugging/reprocessing)
export const companySnapshots = pgTable(
  "company_snapshots",
  {
    id: serial("id").primaryKey(),
    company_id: integer("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),

    source_url: text("source_url").notNull(),
    crawl_id: text("crawl_id"),
    capture_timestamp: text("capture_timestamp"),
    fetched_at: text("fetched_at").notNull(),

    http_status: integer("http_status"),
    mime: text("mime"),
    content_hash: text("content_hash"),

    text_sample: text("text_sample"), // First N chars
    jsonld: text("jsonld"), // JSON parsed JSON-LD
    extracted: text("extracted"), // JSON extractor output

    // Evidence
    source_type: text("source_type", {
      enum: ["COMMONCRAWL", "LIVE_FETCH", "MANUAL", "PARTNER"],
    }).notNull(),
    method: text("method", {
      enum: ["JSONLD", "META", "DOM", "HEURISTIC", "LLM"],
    }).notNull(),
    extractor_version: text("extractor_version"),

    // WARC pointer
    warc_filename: text("warc_filename"),
    warc_offset: integer("warc_offset"),
    warc_length: integer("warc_length"),
    warc_digest: text("warc_digest"),

    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => [
    index("idx_company_snapshots_company_hash").on(table.company_id, table.content_hash),
  ],
);

export type CompanySnapshot = typeof companySnapshots.$inferSelect;
export type NewCompanySnapshot = typeof companySnapshots.$inferInsert;

// Contacts (from CRM — recruiters and company contacts)
export const contacts = pgTable(
  "contacts",
  {
    id: serial("id").primaryKey(),
    first_name: text("first_name").notNull(),
    last_name: text("last_name").notNull(),
    linkedin_url: text("linkedin_url"),
    email: text("email"),
    emails: text("emails"), // JSON array
    company: text("company"),
    company_id: integer("company_id").references(() => companies.id, {
      onDelete: "set null",
    }),
    position: text("position"),
    user_id: text("user_id"),
    nb_status: text("nb_status"),
    nb_result: text("nb_result"),
    nb_flags: text("nb_flags"), // JSON array
    nb_suggested_correction: text("nb_suggested_correction"),
    nb_retry_token: text("nb_retry_token"),
    nb_execution_time_ms: integer("nb_execution_time_ms"),
    email_verified: boolean("email_verified").default(false),
    bounced_emails: text("bounced_emails"), // JSON array of known-bad email addresses
    github_handle: text("github_handle"),
    telegram_handle: text("telegram_handle"),
    do_not_contact: boolean("do_not_contact").default(false),
    tags: text("tags"), // JSON array
    // ML-derived fields (populated by classifyContact / scoreContactsML)
    seniority: text("seniority"),
    department: text("department"),
    is_decision_maker: boolean("is_decision_maker").default(false),
    authority_score: real("authority_score").default(0.0),
    dm_reasons: text("dm_reasons"), // JSON array
    // ML touch score (computed by computeNextTouchScores / scoreContactsML)
    next_touch_score: real("next_touch_score").default(0.0),
    last_contacted_at: text("last_contacted_at"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    emailIdx: index("idx_contacts_email").on(table.email),
    companyIdIdx: index("idx_contacts_company_id").on(table.company_id),
    linkedinUrlIdx: index("idx_contacts_linkedin_url").on(table.linkedin_url),
  }),
);

export type Contact = typeof contacts.$inferSelect;
export type NewContact = typeof contacts.$inferInsert;

// Contact Reminders (explicit dated reminders per contact)
export const contactReminders = pgTable(
  "contact_reminders",
  {
    id: serial("id").primaryKey(),
    contact_id: integer("contact_id")
      .notNull()
      .references(() => contacts.id, { onDelete: "cascade" }),
    remind_at: text("remind_at").notNull(),
    recurrence: text("recurrence").notNull().default("none"), // none | weekly | biweekly | monthly
    note: text("note"),
    status: text("status").notNull().default("pending"), // pending | snoozed | done
    snoozed_until: text("snoozed_until"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    contactIdIdx: index("idx_contact_reminders_contact_id").on(table.contact_id),
    remindAtIdx: index("idx_contact_reminders_remind_at").on(table.remind_at),
    statusIdx: index("idx_contact_reminders_status").on(table.status),
  }),
);

export type ContactReminder = typeof contactReminders.$inferSelect;
export type NewContactReminder = typeof contactReminders.$inferInsert;

// Contact Emails (outbound emails sent to a contact)
export const contactEmails = pgTable(
  "contact_emails",
  {
    id: serial("id").primaryKey(),
    contact_id: integer("contact_id")
      .notNull()
      .references(() => contacts.id, { onDelete: "cascade" }),
    resend_id: text("resend_id").notNull(),
    from_email: text("from_email").notNull(),
    to_emails: text("to_emails").notNull(), // JSON array
    subject: text("subject").notNull(),
    text_content: text("text_content"),
    status: text("status").notNull().default("sent"),
    sent_at: text("sent_at"),
    scheduled_at: text("scheduled_at"),
    delivered_at: text("delivered_at"),
    opened_at: text("opened_at"),
    recipient_name: text("recipient_name"),
    error_message: text("error_message"),
    // Follow-up sequence tracking
    parent_email_id: integer("parent_email_id"),
    sequence_type: text("sequence_type"), // "initial" | "followup_1" | "followup_2" | "followup_3"
    sequence_number: text("sequence_number"), // "0", "1", "2", "3"
    reply_received: boolean("reply_received").default(false),
    reply_received_at: text("reply_received_at"),
    followup_status: text("followup_status"), // "pending" | "completed"
    // Entity linking (for non-contact emails like company batches)
    company_id: integer("company_id").references(() => companies.id, { onDelete: "set null" }),
    // Extended fields (ported from CRM)
    cc_emails: text("cc_emails").default("[]"), // JSON array
    reply_to_emails: text("reply_to_emails").default("[]"), // JSON array
    html_content: text("html_content"),
    attachments: text("attachments").default("[]"), // JSON array
    tags: text("tags").default("[]"), // JSON array
    headers: text("headers").default("[]"), // JSON array
    idempotency_key: text("idempotency_key"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    contactIdIdx: index("idx_contact_emails_contact_id").on(table.contact_id),
    resendIdIdx: index("idx_contact_emails_resend_id").on(table.resend_id),
    statusIdx: index("idx_contact_emails_status").on(table.status),
    companyIdIdx: index("idx_contact_emails_company_id").on(table.company_id),
  }),
);

export type ContactEmail = typeof contactEmails.$inferSelect;
export type NewContactEmail = typeof contactEmails.$inferInsert;


// Email Campaigns (CRM — automated email sequences)
export const emailCampaigns = pgTable(
  "email_campaigns",
  {
    id: text("id").primaryKey(), // campaign_<timestamp>_<random>
    company_id: integer("company_id").references(() => companies.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    status: text("status", {
      enum: ["draft", "pending", "running", "completed", "failed", "stopped"],
    }).notNull().default("draft"),
    sequence: text("sequence"), // JSON array of email steps
    delay_days: text("delay_days"), // JSON array of delays between steps
    start_at: text("start_at"),
    mode: text("mode"), // "sequential" | "blast"
    from_email: text("from_email"),
    reply_to: text("reply_to"),
    total_recipients: integer("total_recipients").notNull().default(0),
    emails_sent: integer("emails_sent").notNull().default(0),
    emails_scheduled: integer("emails_scheduled").notNull().default(0),
    emails_failed: integer("emails_failed").notNull().default(0),
    recipient_emails: text("recipient_emails"), // JSON array
    // Extended fields (ported from CRM)
    total_emails_planned: integer("total_emails_planned"),
    add_unsubscribe_headers: integer("add_unsubscribe_headers").notNull().default(0),
    unsubscribe_url: text("unsubscribe_url"),
    add_anti_thread_header: integer("add_anti_thread_header").notNull().default(0),
    created_by: text("created_by"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    companyIdIdx: index("idx_email_campaigns_company_id").on(table.company_id),
    statusIdx: index("idx_email_campaigns_status").on(table.status),
  }),
);

export type EmailCampaign = typeof emailCampaigns.$inferSelect;
export type NewEmailCampaign = typeof emailCampaigns.$inferInsert;

// Email Templates (CRM — reusable email templates)
export const emailTemplates = pgTable(
  "email_templates",
  {
    id: serial("id").primaryKey(),
    name: text("name").notNull(),
    description: text("description"),
    subject: text("subject"),
    html_content: text("html_content"),
    text_content: text("text_content"),
    category: text("category"),
    tags: text("tags"), // JSON array
    variables: text("variables"), // JSON array of variable names
    is_active: boolean("is_active").notNull().default(true),
    user_id: text("user_id"), // Template owner
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    categoryIdx: index("idx_email_templates_category").on(table.category),
  }),
);

export type EmailTemplate = typeof emailTemplates.$inferSelect;
export type NewEmailTemplate = typeof emailTemplates.$inferInsert;

// Received Emails (inbound emails persisted from Resend webhooks)
export const receivedEmails = pgTable(
  "received_emails",
  {
    id: serial("id").primaryKey(),
    resend_id: text("resend_id").notNull().unique(),
    from_email: text("from_email"),
    to_emails: text("to_emails").notNull().default("[]"), // JSON array
    cc_emails: text("cc_emails").default("[]"), // JSON array
    reply_to_emails: text("reply_to_emails").default("[]"), // JSON array
    subject: text("subject"),
    message_id: text("message_id"),
    html_content: text("html_content"),
    text_content: text("text_content"),
    attachments: text("attachments").default("[]"), // JSON array
    received_at: text("received_at").notNull(),
    archived_at: text("archived_at"),
    created_at: text("created_at")
      .notNull()
      .default(sql`now()::text`),
    updated_at: text("updated_at")
      .notNull()
      .default(sql`now()::text`),
  },
  (table) => ({
    fromEmailIdx: index("idx_received_emails_from").on(table.from_email),
    messageIdIdx: index("idx_received_emails_message_id").on(table.message_id),
    receivedAtIdx: index("idx_received_emails_received_at").on(table.received_at),
    resendIdIdx: index("idx_received_emails_resend_id").on(table.resend_id),
  }),
);

export type ReceivedEmail = typeof receivedEmails.$inferSelect;
export type NewReceivedEmail = typeof receivedEmails.$inferInsert;

// ---------------------------------------------------------------------------
// Drizzle relations() declarations
// ---------------------------------------------------------------------------

export const companiesRelations = relations(companies, ({ many }) => ({
  companyFacts: many(companyFacts),
  companySnapshots: many(companySnapshots),
  contacts: many(contacts),
  emailCampaigns: many(emailCampaigns),
}));

export const companyFactsRelations = relations(companyFacts, ({ one }) => ({
  company: one(companies, {
    fields: [companyFacts.company_id],
    references: [companies.id],
  }),
}));

export const companySnapshotsRelations = relations(companySnapshots, ({ one }) => ({
  company: one(companies, {
    fields: [companySnapshots.company_id],
    references: [companies.id],
  }),
}));

export const contactsRelations = relations(contacts, ({ one, many }) => ({
  company: one(companies, {
    fields: [contacts.company_id],
    references: [companies.id],
  }),
  emails: many(contactEmails),
}));

export const contactEmailsRelations = relations(contactEmails, ({ one }) => ({
  contact: one(contacts, {
    fields: [contactEmails.contact_id],
    references: [contacts.id],
  }),
}));

export const emailCampaignsRelations = relations(emailCampaigns, ({ one }) => ({
  company: one(companies, {
    fields: [emailCampaigns.company_id],
    references: [companies.id],
  }),
}));
