import { readFileSync } from "fs";
import { join } from "path";

export type GitHubRepo = {
  name: string;
  description: string | null;
  url: string;
  stars: number;
  forks: number;
  language: string | null;
  topics: string[];
  updatedAt: string;
  createdAt: string;
};

export type GitHubProfile = {
  bio: string | null;
  publicRepos: number;
  followers: number;
  location: string | null;
  createdAt: string;
};

export type HFModel = {
  id: string;
  likes: number;
  downloads: number;
  tags: string[];
  pipelineTag: string | null;
  createdAt: string | null;
};

export type EnrichedData = {
  github: {
    profile: GitHubProfile | null;
    repos: GitHubRepo[];
    totalStars: number;
    languages: { name: string; count: number; color: string }[];
  } | null;
  huggingface: {
    models: HFModel[];
    totalDownloads: number;
    totalLikes: number;
  } | null;
  imageUrl: string | null;
};

const EMPTY: EnrichedData = { github: null, huggingface: null, imageUrl: null };

/**
 * Load pre-generated enrichment data for a person.
 * Generated by: python timeline_enrichment.py enrich <slug>
 */
export function getEnrichment(slug: string): EnrichedData {
  try {
    const raw = readFileSync(
      join(process.cwd(), "src", "lib", "enrichment", `${slug}.json`),
      "utf-8",
    );
    return JSON.parse(raw) as EnrichedData;
  } catch {
    return EMPTY;
  }
}

export function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return n.toString();
}
