-- ═══════════════════════════════════════
-- Knowledge App — Add course_reviews table
-- Course review scores generated by 10-expert LangGraph pipeline
-- ═══════════════════════════════════════

CREATE TABLE IF NOT EXISTS course_reviews (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id      uuid NOT NULL REFERENCES external_courses(id) ON DELETE CASCADE,
  -- Expert scores (0-10 integer each)
  pedagogy_score                integer CHECK (pedagogy_score BETWEEN 0 AND 10),
  technical_accuracy_score      integer CHECK (technical_accuracy_score BETWEEN 0 AND 10),
  content_depth_score           integer CHECK (content_depth_score BETWEEN 0 AND 10),
  practical_application_score   integer CHECK (practical_application_score BETWEEN 0 AND 10),
  instructor_clarity_score      integer CHECK (instructor_clarity_score BETWEEN 0 AND 10),
  curriculum_fit_score          integer CHECK (curriculum_fit_score BETWEEN 0 AND 10),
  prerequisites_score           integer CHECK (prerequisites_score BETWEEN 0 AND 10),
  ai_domain_relevance_score     integer CHECK (ai_domain_relevance_score BETWEEN 0 AND 10),
  community_health_score        integer CHECK (community_health_score BETWEEN 0 AND 10),
  value_proposition_score       integer CHECK (value_proposition_score BETWEEN 0 AND 10),
  -- Aggregated
  aggregate_score    real,
  verdict            text CHECK (verdict IN ('excellent','recommended','average','skip')),
  summary            text,
  expert_details     jsonb,
  model_version      text NOT NULL DEFAULT 'deepseek-chat',
  reviewed_at        timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS course_reviews_course_unique ON course_reviews (course_id);
CREATE INDEX IF NOT EXISTS course_reviews_course_idx ON course_reviews (course_id);
CREATE INDEX IF NOT EXISTS course_reviews_verdict_idx ON course_reviews (verdict) WHERE verdict IS NOT NULL;
CREATE INDEX IF NOT EXISTS course_reviews_score_idx ON course_reviews (aggregate_score DESC NULLS LAST);
