use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};

use crate::{Company, Contact, LeadScore};
use super::chunker::Chunk;
use super::crag::{CragEvaluator, RetrievalQuality};
use super::query_decomposer::QueryDecomposer;

// ---------------------------------------------------------------------------
// Output types
// ---------------------------------------------------------------------------

/// A brief summary of a single contact within a lead report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactSummary {
    pub name: String,
    pub title: String,
    /// Why this contact is relevant to the ICP (derived by the LLM).
    pub relevance: String,
}

/// A fully generated lead report for one company.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeadReport {
    pub company_name: String,
    pub executive_summary: String,
    pub key_contacts: Vec<ContactSummary>,
    pub icp_analysis: String,
    pub recommendations: Vec<String>,
    pub sources_used: Vec<String>,
    /// RFC 3339 timestamp marking when this report was generated.
    pub generated_at: String,
    /// Overall CRAG retrieval quality for the context chunks used: "Correct",
    /// "Ambiguous", or "Incorrect".
    pub retrieval_quality: String,
    /// Number of sub-queries generated by QueryDecomposer for this report.
    pub sub_queries_used: usize,
}

// ---------------------------------------------------------------------------
// Internal LLM response shape
// ---------------------------------------------------------------------------

/// Intermediate deserialization target for the structured LLM response.
#[derive(Deserialize)]
struct LlmReportResponse {
    executive_summary: String,
    key_contacts: Vec<LlmContactEntry>,
    icp_analysis: String,
    recommendations: Vec<String>,
}

#[derive(Deserialize)]
struct LlmContactEntry {
    name: String,
    title: String,
    relevance: String,
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/// Generates [`LeadReport`]s using a RAG pattern: retrieved context chunks are
/// injected into the LLM prompt to ground the model's output in factual data.
pub struct ReportGenerator {
    llm: crate::llm::LlmClient,
}

impl ReportGenerator {
    pub fn new(llm: crate::llm::LlmClient) -> Self {
        Self { llm }
    }

    /// Generate a structured lead report for `company`.
    ///
    /// Uses CRAG (Corrective RAG) quality filtering: chunks are evaluated via
    /// [`CragEvaluator`] and only Correct + Ambiguous chunks are passed to the
    /// LLM.  The implicit retrieval query is first decomposed into sub-queries
    /// by [`QueryDecomposer`] to improve multi-hop coverage.
    ///
    /// # Arguments
    /// * `company`        - The target company record.
    /// * `contacts`       - Known contacts at the company.
    /// * `scores`         - Lead scores for those contacts (matched by `contact_id`).
    /// * `context_chunks` - RAG-retrieved context chunks (e.g. from crawled pages).
    pub async fn generate(
        &self,
        company: &Company,
        contacts: &[Contact],
        scores: &[LeadScore],
        context_chunks: &[Chunk],
    ) -> Result<LeadReport> {
        // Step 1: Decompose the implicit query into sub-queries.
        let base_query = format!("who are the key contacts at {}", company.name);
        let decomposer = QueryDecomposer::new();
        let sub_queries = decomposer.decompose(&base_query);
        let sub_queries_used = sub_queries.len();

        // Step 2: Evaluate all chunks across all sub-queries using CRAG.
        // For each sub-query we score every chunk, then union the passing ones.
        let evaluator = CragEvaluator::new();

        // Collect (text, similarity_score) pairs; use chunk_index-normalised
        // position as a proxy similarity when no external embedding score is
        // available (0.5 baseline keeps ambiguous chunks in play).
        let chunk_inputs: Vec<(String, f64)> = context_chunks
            .iter()
            .map(|c| (c.text.clone(), 0.5_f64))
            .collect();

        // Evaluate per sub-query and keep the union of Correct + Ambiguous
        // chunk indices (deduplicated).
        let mut accepted_indices: std::collections::BTreeSet<usize> = std::collections::BTreeSet::new();
        let mut overall_quality = RetrievalQuality::Incorrect;

        for sub_query in &sub_queries {
            let batch = evaluator.evaluate_batch(sub_query, &chunk_inputs);
            // Track the best overall quality seen across sub-queries.
            match batch.overall_quality {
                RetrievalQuality::Correct => {
                    overall_quality = RetrievalQuality::Correct;
                }
                RetrievalQuality::Ambiguous if overall_quality == RetrievalQuality::Incorrect => {
                    overall_quality = RetrievalQuality::Ambiguous;
                }
                _ => {}
            }
            for (i, (quality, _confidence)) in batch.per_chunk.iter().enumerate() {
                if *quality != RetrievalQuality::Incorrect {
                    accepted_indices.insert(i);
                }
            }
        }

        // Step 3: Build the filtered chunk slice passed to the LLM prompt.
        let filtered_chunks: Vec<&Chunk> = if accepted_indices.is_empty() {
            // All chunks were rated Incorrect — fall back to the full set so
            // the LLM still has some context rather than nothing.
            context_chunks.iter().collect()
        } else {
            accepted_indices
                .iter()
                .filter_map(|&i| context_chunks.get(i))
                .collect()
        };

        let retrieval_quality_str = match overall_quality {
            RetrievalQuality::Correct => "Correct",
            RetrievalQuality::Ambiguous => "Ambiguous",
            RetrievalQuality::Incorrect => "Incorrect",
        }
        .to_string();

        // Step 4: Build prompt with only the high-quality chunks.
        let prompt = build_prompt(company, contacts, scores, &filtered_chunks);
        let raw = self.llm.complete(&prompt, 0.3).await?;
        let mut report = parse_report_response(&raw, company, contacts, scores)?;

        // Attach CRAG metadata.
        report.retrieval_quality = retrieval_quality_str;
        report.sub_queries_used = sub_queries_used;

        Ok(report)
    }
}

// ---------------------------------------------------------------------------
// Prompt construction
// ---------------------------------------------------------------------------

fn build_prompt(
    company: &Company,
    contacts: &[Contact],
    scores: &[LeadScore],
    context_chunks: &[&Chunk],
) -> String {
    // Build a score lookup for contacts.
    let score_map: std::collections::HashMap<&str, &LeadScore> =
        scores.iter().map(|s| (s.contact_id.as_str(), s)).collect();

    // Format retrieved context — use at most 8 chunks to keep prompt bounded.
    let context_text: String = context_chunks
        .iter()
        .take(8)
        .enumerate()
        .map(|(i, c)| format!("[Context {}] ({})\n{}", i + 1, c.section, c.text))
        .collect::<Vec<_>>()
        .join("\n\n");

    // Format contacts.
    let contacts_text: String = contacts
        .iter()
        .map(|c| {
            let score_str = score_map
                .get(c.id.as_str())
                .map(|s| format!(" [composite_score: {:.2}]", s.composite_score))
                .unwrap_or_default();
            format!(
                "- {} {} | {} | {}{}",
                c.first_name,
                c.last_name,
                c.title.as_deref().unwrap_or("Unknown Title"),
                c.department.as_deref().unwrap_or("Unknown Dept"),
                score_str,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    // Format company metadata.
    let company_meta = format!(
        "Name: {}\nDomain: {}\nIndustry: {}\nEmployees: {}\nLocation: {}\nTech Stack: {}\nDescription: {}",
        company.name,
        company.domain.as_deref().unwrap_or("—"),
        company.industry.as_deref().unwrap_or("Unknown"),
        company.employee_count.map(|n| n.to_string()).unwrap_or_else(|| "Unknown".to_string()),
        company.location.as_deref().unwrap_or("Unknown"),
        company.tech_stack.as_deref().unwrap_or("Unknown"),
        company.description.as_deref().unwrap_or("No description available."),
    );

    format!(
        r#"You are a B2B sales intelligence analyst. Generate a structured lead report.

## Company
{company_meta}

## Known Contacts
{contacts_text}

## Retrieved Context
{context_text}

## Instructions
Analyse the company and contacts above. Return ONLY valid JSON matching this schema exactly:

{{
  "executive_summary": "2-3 sentences: what the company does, why it is a good lead, and timing",
  "key_contacts": [
    {{"name": "Full Name", "title": "Job Title", "relevance": "why this person is the right ICP contact"}}
  ],
  "icp_analysis": "paragraph explaining ICP fit across size, industry, tech stack, and location signals",
  "recommendations": ["action item 1", "action item 2", "action item 3"]
}}

Rules:
- key_contacts must include only contacts listed above; omit those with no relevance.
- recommendations must be specific and actionable (mention names or features where possible).
- Do not include markdown, code fences, or any text outside the JSON object."#,
        company_meta = company_meta,
        contacts_text = if contacts_text.is_empty() { "No contacts available.".to_string() } else { contacts_text },
        context_text = if context_text.is_empty() { "No additional context retrieved.".to_string() } else { context_text },
    )
}

// ---------------------------------------------------------------------------
// Response parsing
// ---------------------------------------------------------------------------

fn parse_report_response(
    raw: &str,
    company: &Company,
    contacts: &[Contact],
    scores: &[LeadScore],
) -> Result<LeadReport> {
    let cleaned = clean_json_block(raw);

    // Attempt direct parse first.
    let parsed: LlmReportResponse = if let Ok(p) = serde_json::from_str(&cleaned) {
        p
    } else {
        // Try to extract the outermost JSON object.
        let start = cleaned.find('{').ok_or_else(|| anyhow!("no JSON object in LLM response"))?;
        let end = cleaned.rfind('}').ok_or_else(|| anyhow!("unclosed JSON object in LLM response"))?;
        serde_json::from_str(&cleaned[start..=end])
            .map_err(|e| anyhow!("failed to parse LLM report JSON: {e}\nraw: {}", &raw[..raw.len().min(500)]))?
    };

    // Collect source identifiers from scored contacts.
    let score_map: std::collections::HashMap<&str, &LeadScore> =
        scores.iter().map(|s| (s.contact_id.as_str(), s)).collect();
    let sources_used: Vec<String> = contacts
        .iter()
        .filter(|c| score_map.contains_key(c.id.as_str()))
        .filter_map(|c| c.company_id.clone())
        .chain(company.domain.iter().cloned())
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();

    let generated_at = chrono::Utc::now().to_rfc3339();

    Ok(LeadReport {
        company_name: company.name.clone(),
        executive_summary: parsed.executive_summary,
        key_contacts: parsed
            .key_contacts
            .into_iter()
            .map(|c| ContactSummary {
                name: c.name,
                title: c.title,
                relevance: c.relevance,
            })
            .collect(),
        icp_analysis: parsed.icp_analysis,
        recommendations: parsed.recommendations,
        sources_used,
        generated_at,
        // These two fields are populated by the caller (generate()) after CRAG
        // evaluation.  parse_report_response is intentionally kept pure so it
        // can be tested in isolation with stable defaults.
        retrieval_quality: "Ambiguous".to_string(),
        sub_queries_used: 1,
    })
}

/// Strip markdown code fences and surrounding whitespace from an LLM response.
fn clean_json_block(s: &str) -> String {
    let trimmed = s.trim();
    if trimmed.starts_with("```") {
        let without_start = trimmed
            .find('\n')
            .map(|p| &trimmed[p + 1..])
            .unwrap_or(trimmed);
        if let Some(end) = without_start.rfind("```") {
            return without_start[..end].trim().to_string();
        }
        return without_start.trim().to_string();
    }
    trimmed.to_string()
}

