// AUTO-GENERATED by scripts/generate-worker-types.ts
// Do NOT edit manually. Run `pnpm schema:generate` to regenerate.
//
// Source of truth: src/schema/contracts/


/// Auto-generated from src/schema/contracts/enums.ts
pub const JOBSTATUS_VALUES: &[&str] = &[
    "new",
    "enhanced",
    "role_match",
    "role_nomatch",
    "eu_remote",
    "non_eu",
    "error",
    "reported",
];

/// Auto-generated from src/schema/contracts/enums.ts
pub const CLASSIFICATIONCONFIDENCE_VALUES: &[&str] = &[
    "high",
    "medium",
    "low",
];

/// Auto-generated from src/schema/contracts/enums.ts
pub const ATSVENDOR_VALUES: &[&str] = &[
    "GREENHOUSE",
    "LEVER",
    "WORKABLE",
    "TEAMTAILOR",
    "ASHBY",
    "SMARTRECRUITERS",
    "JAZZHR",
    "BREEZYHR",
    "ICIMS",
    "JOBVITE",
    "SAP_SUCCESSFACTORS",
    "ORACLE_TALEO",
    "OTHER",
];

/// Auto-generated from src/schema/contracts/enums.ts
pub const ATSBOARDTYPE_VALUES: &[&str] = &[
    "JOBS_PAGE",
    "BOARD_API",
    "BOARD_WIDGET",
    "UNKNOWN",
];

/// Auto-generated from src/schema/contracts/enums.ts
pub const COMPANYCATEGORY_VALUES: &[&str] = &[
    "CONSULTANCY",
    "AGENCY",
    "STAFFING",
    "DIRECTORY",
    "PRODUCT",
    "OTHER",
    "UNKNOWN",
];

/// Auto-generated from src/schema/contracts/enums.ts
pub const SOURCETYPE_VALUES: &[&str] = &[
    "COMMONCRAWL",
    "LIVE_FETCH",
    "MANUAL",
    "PARTNER",
];

/// Auto-generated from src/schema/contracts/enums.ts
pub const EXTRACTMETHOD_VALUES: &[&str] = &[
    "JSONLD",
    "META",
    "DOM",
    "HEURISTIC",
    "LLM",
];

/// Vendor strings recognized by the ashby-crawler AtsProvider enum.
/// Keep AtsProvider::from_str in sync with this list.
pub const ATS_CRAWLER_PROVIDERS: &[&str] = &["ASHBY", "GREENHOUSE", "WORKABLE"];

/// Canonical skill taxonomy — 118 tags.
pub const SKILL_TAGS: &[&str] = &[
    "javascript",
    "typescript",
    "python",
    "java",
    "csharp",
    "ruby",
    "php",
    "go",
    "rust",
    "swift",
    "kotlin",
    "scala",
    "elixir",
    "react",
    "vue",
    "angular",
    "svelte",
    "nextjs",
    "nodejs",
    "express",
    "django",
    "flask",
    "laravel",
    "fastapi",
    "spring-boot",
    "react-native",
    "flutter",
    "ios",
    "android",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "elasticsearch",
    "cassandra",
    "dynamodb",
    "sqlite",
    "sql",
    "aws",
    "gcp",
    "azure",
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "jenkins",
    "ci-cd",
    "circleci",
    "serverless",
    "microservices",
    "rest-api",
    "graphql",
    "grpc",
    "websocket",
    "event-driven",
    "git",
    "linux",
    "agile",
    "tdd",
    "webpack",
    "jest",
    "pytest",
    "tailwind",
    "machine-learning",
    "deep-learning",
    "tensorflow",
    "pytorch",
    "pandas",
    "numpy",
    "scikit",
    "nlp",
    "computer-vision",
    "llm",
    "rag",
    "prompt-engineering",
    "fine-tuning",
    "embeddings",
    "transformers",
    "agents",
    "agentic-ai",
    "langchain",
    "langgraph",
    "openai",
    "anthropic",
    "vercel-ai-sdk",
    "vector-db",
    "pinecone",
    "weaviate",
    "chromadb",
    "mlops",
    "huggingface",
    "model-evaluation",
    "structured-output",
    "function-calling",
    "mastra",
    "langfuse",
    "cloudflare-workers",
    "cloudflare-workers-ai",
    "cloudflare-d1",
    "cloudflare-vectorize",
    "next-auth",
    "radix-ui",
    "shadcn-ui",
    "storybook",
    "playwright",
    "cypress",
    "vitest",
    "react-query",
    "zustand",
    "apollo-client",
    "remix",
    "astro",
    "drizzle-orm",
    "prisma",
    "trpc",
    "hono",
    "bun",
    "deno",
];
