/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "mutation DeleteBloodTest($id: UUID!) {\n  deleteFromblood_testsCollection(filter: {id: {eq: $id}}) {\n    affectedCount\n  }\n}\n\nmutation InsertBloodTest($user_id: UUID!, $file_name: String!, $file_path: String!, $status: String!, $test_date: Date) {\n  insertIntoblood_testsCollection(\n    objects: [{user_id: $user_id, file_name: $file_name, file_path: $file_path, status: $status, test_date: $test_date}]\n  ) {\n    records {\n      id\n      file_name\n      file_path\n      status\n      test_date\n    }\n  }\n}\n\nmutation InsertBloodMarkers($objects: [blood_markersInsertInput!]!) {\n  insertIntoblood_markersCollection(objects: $objects) {\n    records {\n      id\n    }\n  }\n}\n\nmutation UpdateBloodTestStatus($id: UUID!, $status: String!, $error_message: String) {\n  updateblood_testsCollection(\n    filter: {id: {eq: $id}}\n    set: {status: $status, error_message: $error_message}\n  ) {\n    records {\n      id\n      status\n    }\n  }\n}\n\nmutation InsertCondition($user_id: UUID!, $name: String!, $notes: String) {\n  insertIntoconditionsCollection(\n    objects: [{user_id: $user_id, name: $name, notes: $notes}]\n  ) {\n    records {\n      id\n      name\n    }\n  }\n}\n\nmutation DeleteCondition($id: UUID!) {\n  deleteFromconditionsCollection(filter: {id: {eq: $id}}) {\n    affectedCount\n  }\n}": typeof types.DeleteBloodTestDocument,
    "query GetBloodTests {\n  blood_testsCollection(orderBy: [{uploaded_at: DescNullsLast}]) {\n    edges {\n      node {\n        id\n        file_name\n        file_path\n        status\n        test_date\n        uploaded_at\n        error_message\n      }\n    }\n  }\n}\n\nquery GetBloodTest($id: UUID!) {\n  blood_testsCollection(filter: {id: {eq: $id}}) {\n    edges {\n      node {\n        id\n        file_name\n        file_path\n        status\n        test_date\n        uploaded_at\n        error_message\n        user_id\n      }\n    }\n  }\n  blood_markersCollection(\n    filter: {test_id: {eq: $id}}\n    orderBy: [{name: AscNullsLast}]\n  ) {\n    edges {\n      node {\n        id\n        name\n        value\n        unit\n        reference_range\n        flag\n      }\n    }\n  }\n}\n\nquery GetConditions {\n  conditionsCollection(orderBy: [{created_at: DescNullsLast}]) {\n    edges {\n      node {\n        id\n        name\n        notes\n        created_at\n      }\n    }\n  }\n}\n\nquery GetCondition($id: UUID!) {\n  conditionsCollection(filter: {id: {eq: $id}}) {\n    edges {\n      node {\n        id\n        name\n        notes\n        created_at\n        user_id\n      }\n    }\n  }\n}": typeof types.GetBloodTestsDocument,
};
const documents: Documents = {
    "mutation DeleteBloodTest($id: UUID!) {\n  deleteFromblood_testsCollection(filter: {id: {eq: $id}}) {\n    affectedCount\n  }\n}\n\nmutation InsertBloodTest($user_id: UUID!, $file_name: String!, $file_path: String!, $status: String!, $test_date: Date) {\n  insertIntoblood_testsCollection(\n    objects: [{user_id: $user_id, file_name: $file_name, file_path: $file_path, status: $status, test_date: $test_date}]\n  ) {\n    records {\n      id\n      file_name\n      file_path\n      status\n      test_date\n    }\n  }\n}\n\nmutation InsertBloodMarkers($objects: [blood_markersInsertInput!]!) {\n  insertIntoblood_markersCollection(objects: $objects) {\n    records {\n      id\n    }\n  }\n}\n\nmutation UpdateBloodTestStatus($id: UUID!, $status: String!, $error_message: String) {\n  updateblood_testsCollection(\n    filter: {id: {eq: $id}}\n    set: {status: $status, error_message: $error_message}\n  ) {\n    records {\n      id\n      status\n    }\n  }\n}\n\nmutation InsertCondition($user_id: UUID!, $name: String!, $notes: String) {\n  insertIntoconditionsCollection(\n    objects: [{user_id: $user_id, name: $name, notes: $notes}]\n  ) {\n    records {\n      id\n      name\n    }\n  }\n}\n\nmutation DeleteCondition($id: UUID!) {\n  deleteFromconditionsCollection(filter: {id: {eq: $id}}) {\n    affectedCount\n  }\n}": types.DeleteBloodTestDocument,
    "query GetBloodTests {\n  blood_testsCollection(orderBy: [{uploaded_at: DescNullsLast}]) {\n    edges {\n      node {\n        id\n        file_name\n        file_path\n        status\n        test_date\n        uploaded_at\n        error_message\n      }\n    }\n  }\n}\n\nquery GetBloodTest($id: UUID!) {\n  blood_testsCollection(filter: {id: {eq: $id}}) {\n    edges {\n      node {\n        id\n        file_name\n        file_path\n        status\n        test_date\n        uploaded_at\n        error_message\n        user_id\n      }\n    }\n  }\n  blood_markersCollection(\n    filter: {test_id: {eq: $id}}\n    orderBy: [{name: AscNullsLast}]\n  ) {\n    edges {\n      node {\n        id\n        name\n        value\n        unit\n        reference_range\n        flag\n      }\n    }\n  }\n}\n\nquery GetConditions {\n  conditionsCollection(orderBy: [{created_at: DescNullsLast}]) {\n    edges {\n      node {\n        id\n        name\n        notes\n        created_at\n      }\n    }\n  }\n}\n\nquery GetCondition($id: UUID!) {\n  conditionsCollection(filter: {id: {eq: $id}}) {\n    edges {\n      node {\n        id\n        name\n        notes\n        created_at\n        user_id\n      }\n    }\n  }\n}": types.GetBloodTestsDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation DeleteBloodTest($id: UUID!) {\n  deleteFromblood_testsCollection(filter: {id: {eq: $id}}) {\n    affectedCount\n  }\n}\n\nmutation InsertBloodTest($user_id: UUID!, $file_name: String!, $file_path: String!, $status: String!, $test_date: Date) {\n  insertIntoblood_testsCollection(\n    objects: [{user_id: $user_id, file_name: $file_name, file_path: $file_path, status: $status, test_date: $test_date}]\n  ) {\n    records {\n      id\n      file_name\n      file_path\n      status\n      test_date\n    }\n  }\n}\n\nmutation InsertBloodMarkers($objects: [blood_markersInsertInput!]!) {\n  insertIntoblood_markersCollection(objects: $objects) {\n    records {\n      id\n    }\n  }\n}\n\nmutation UpdateBloodTestStatus($id: UUID!, $status: String!, $error_message: String) {\n  updateblood_testsCollection(\n    filter: {id: {eq: $id}}\n    set: {status: $status, error_message: $error_message}\n  ) {\n    records {\n      id\n      status\n    }\n  }\n}\n\nmutation InsertCondition($user_id: UUID!, $name: String!, $notes: String) {\n  insertIntoconditionsCollection(\n    objects: [{user_id: $user_id, name: $name, notes: $notes}]\n  ) {\n    records {\n      id\n      name\n    }\n  }\n}\n\nmutation DeleteCondition($id: UUID!) {\n  deleteFromconditionsCollection(filter: {id: {eq: $id}}) {\n    affectedCount\n  }\n}"): (typeof documents)["mutation DeleteBloodTest($id: UUID!) {\n  deleteFromblood_testsCollection(filter: {id: {eq: $id}}) {\n    affectedCount\n  }\n}\n\nmutation InsertBloodTest($user_id: UUID!, $file_name: String!, $file_path: String!, $status: String!, $test_date: Date) {\n  insertIntoblood_testsCollection(\n    objects: [{user_id: $user_id, file_name: $file_name, file_path: $file_path, status: $status, test_date: $test_date}]\n  ) {\n    records {\n      id\n      file_name\n      file_path\n      status\n      test_date\n    }\n  }\n}\n\nmutation InsertBloodMarkers($objects: [blood_markersInsertInput!]!) {\n  insertIntoblood_markersCollection(objects: $objects) {\n    records {\n      id\n    }\n  }\n}\n\nmutation UpdateBloodTestStatus($id: UUID!, $status: String!, $error_message: String) {\n  updateblood_testsCollection(\n    filter: {id: {eq: $id}}\n    set: {status: $status, error_message: $error_message}\n  ) {\n    records {\n      id\n      status\n    }\n  }\n}\n\nmutation InsertCondition($user_id: UUID!, $name: String!, $notes: String) {\n  insertIntoconditionsCollection(\n    objects: [{user_id: $user_id, name: $name, notes: $notes}]\n  ) {\n    records {\n      id\n      name\n    }\n  }\n}\n\nmutation DeleteCondition($id: UUID!) {\n  deleteFromconditionsCollection(filter: {id: {eq: $id}}) {\n    affectedCount\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query GetBloodTests {\n  blood_testsCollection(orderBy: [{uploaded_at: DescNullsLast}]) {\n    edges {\n      node {\n        id\n        file_name\n        file_path\n        status\n        test_date\n        uploaded_at\n        error_message\n      }\n    }\n  }\n}\n\nquery GetBloodTest($id: UUID!) {\n  blood_testsCollection(filter: {id: {eq: $id}}) {\n    edges {\n      node {\n        id\n        file_name\n        file_path\n        status\n        test_date\n        uploaded_at\n        error_message\n        user_id\n      }\n    }\n  }\n  blood_markersCollection(\n    filter: {test_id: {eq: $id}}\n    orderBy: [{name: AscNullsLast}]\n  ) {\n    edges {\n      node {\n        id\n        name\n        value\n        unit\n        reference_range\n        flag\n      }\n    }\n  }\n}\n\nquery GetConditions {\n  conditionsCollection(orderBy: [{created_at: DescNullsLast}]) {\n    edges {\n      node {\n        id\n        name\n        notes\n        created_at\n      }\n    }\n  }\n}\n\nquery GetCondition($id: UUID!) {\n  conditionsCollection(filter: {id: {eq: $id}}) {\n    edges {\n      node {\n        id\n        name\n        notes\n        created_at\n        user_id\n      }\n    }\n  }\n}"): (typeof documents)["query GetBloodTests {\n  blood_testsCollection(orderBy: [{uploaded_at: DescNullsLast}]) {\n    edges {\n      node {\n        id\n        file_name\n        file_path\n        status\n        test_date\n        uploaded_at\n        error_message\n      }\n    }\n  }\n}\n\nquery GetBloodTest($id: UUID!) {\n  blood_testsCollection(filter: {id: {eq: $id}}) {\n    edges {\n      node {\n        id\n        file_name\n        file_path\n        status\n        test_date\n        uploaded_at\n        error_message\n        user_id\n      }\n    }\n  }\n  blood_markersCollection(\n    filter: {test_id: {eq: $id}}\n    orderBy: [{name: AscNullsLast}]\n  ) {\n    edges {\n      node {\n        id\n        name\n        value\n        unit\n        reference_range\n        flag\n      }\n    }\n  }\n}\n\nquery GetConditions {\n  conditionsCollection(orderBy: [{created_at: DescNullsLast}]) {\n    edges {\n      node {\n        id\n        name\n        notes\n        created_at\n      }\n    }\n  }\n}\n\nquery GetCondition($id: UUID!) {\n  conditionsCollection(filter: {id: {eq: $id}}) {\n    edges {\n      node {\n        id\n        name\n        notes\n        created_at\n        user_id\n      }\n    }\n  }\n}"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;